 
        <?php
        /* Generated by Sovdev 2 ERP CRUD Generator 2017-10-20 17:26:44 */
        /* Location: ./modules/reformulasi/controllers/mbr_revisi_change_control.php */
        /* Please DO NOT modify this information : */ 
         
        if ( ! defined('BASEPATH')) exit('No direct script access allowed');
        class mbr_revisi_change_control extends MX_Controller {
            function __construct() {
                parent::__construct();
                $this->load->library('auth');
                $this->db = $this->load->database('formulasi', false, true);
                $this->user = $this->auth->user();
            }
            function index($action = '') {
                $action = $this->input->get('action');
                //Bikin Object Baru Nama nya $grid      
                $grid = new Grid;
                $grid->setTitle('DRAFT MBR REVISI & CHANGE CONTROL');
                $grid->setTable('plc2.req_refor');      
                $grid->setUrl('mbr_revisi_change_control');

                //List Table
                $grid->addList('vNo_req_refor','nama_produk','vbatch_no','no_produk','vAlasan_refor'); 
                $grid->setSortBy('Req_refor_ID');
                $grid->setSortOrder('asc');  

                //List field
                $grid->addFields('no_produk','vNo_req_refor','vNo_deviasi','nama_produk','vbatch_no','cNIP','idept_id','tTanggal_usulan_refor','vAlasan_refor','uploadFile','iteam_pd','cApproval','cformulator','dTgl_rev_mbr','dPengajuan_cc','vNo_cc','dApproved_cc','uploadFileMBR','nextProses'); 

                $grid ->setSql("SELECT
                                        a.*
                                        , produk.*
                                        ,c.*
                                        ,d.*


                                        FROM (plc2.req_refor)
                                        JOIN plc2.req_refor a ON a.Req_refor_ID = plc2.req_refor.Req_refor_ID
                                        JOIN (  select * from (
                                                select a.idossier_upd_id as pk,a.vUpd_no as no_produk , a.vNama_usulan as nama_produk , '2' as iKey from dossier.dossier_upd a where a.lDeleted=0
                                                union 
                                                select b.iupb_id as pk ,b.vupb_nomor as no_produk, b.vupb_nama as nama_produk , '1' as iKey from plc2.plc2_upb b where b.lDeleted=0
                                            ) as produk) as produk on  produk.pk=a.iNo_usulan and produk.iKey = a.iKey
                                        JOIN hrd.employee c on c.cNip =  a.cNIP
                                        JOIN hrd.msdepartement d on d.iDeptID = a.idept_id
                            "); 

                //Setting Grid Width Name 
                /*
                    Kamu bisa merubah nama label dari sini, Contoh :
                    $grid->setLabel('nama field','nama field yang akan diubah');

                */
        
                $grid->setWidth('vNo_req_refor', '100');
                $grid->setAlign('vNo_req_refor', 'center');
                $grid->setLabel('vNo_req_refor','No. Request');
            
                $grid->setWidth('vNo_deviasi', '100');
                $grid->setAlign('vNo_deviasi', 'left');
                $grid->setLabel('vNo_deviasi','No. Deviasi');

                $grid->setWidth('nama_produk', '350');
                $grid->setAlign('nama_produk', 'left');
                $grid->setLabel('nama_produk','Nama Produk');

                $grid->setWidth('no_produk', '120');
                $grid->setAlign('no_produk', 'center');
                $grid->setLabel('no_produk','No. Usulan Produk');
            
                $grid->setWidth('iNo_usulan', '100');
                $grid->setAlign('iNo_usulan', 'left');
                $grid->setLabel('iNo_usulan','No. Usulan');
            
                $grid->setWidth('iKey', '100');
                $grid->setAlign('iKey', 'left');
                $grid->setLabel('iKey','Key');
            
                $grid->setWidth('vbatch_no', '100');
                $grid->setAlign('vbatch_no', 'center');
                $grid->setLabel('vbatch_no','No. Batch');

                $grid->setWidth('vName', '200');
                $grid->setAlign('vName', 'left');
                $grid->setLabel('vName','Requestor');
            
                $grid->setWidth('cNIP', '100');
                $grid->setAlign('cNIP', 'left');
                $grid->setLabel('cNIP','Nama Inisiator');
            
                $grid->setWidth('idept_id', '100');
                $grid->setAlign('idept_id', 'left');
                $grid->setLabel('idept_id','Departement');
            
                $grid->setWidth('tTanggal_usulan_refor', '100');
                $grid->setAlign('tTanggal_usulan_refor', 'left');
                $grid->setLabel('tTanggal_usulan_refor','Tgl Permintaan Refor Lokal');
            
                $grid->setWidth('vAlasan_refor', '300');
                $grid->setAlign('vAlasan_refor', 'left');
                $grid->setLabel('vAlasan_refor','Keterangan');
            
                $grid->setWidth('iteam_pd', '100');
                $grid->setAlign('iteam_pd', 'left');
                $grid->setLabel('iteam_pd','Team PD');
            
                $grid->setWidth('iSubmit', '100');
                $grid->setAlign('iSubmit', 'left');
                $grid->setLabel('iSubmit','Submit');
            
                $grid->setWidth('iStatus', '100');
                $grid->setAlign('iStatus', 'left');
                $grid->setLabel('iStatus','Status');
            
                $grid->setWidth('cApproval', '100');
                $grid->setAlign('cApproval', 'left');
                $grid->setLabel('cApproval','Approval Atasan Inisiator');
            
                $grid->setWidth('vRemark', '100');
                $grid->setAlign('vRemark', 'left');
                $grid->setLabel('vRemark','Remark');
            
                $grid->setWidth('dApproval', '100');
                $grid->setAlign('dApproval', 'left');
                $grid->setLabel('dApproval','Tanggal Approval');
            
                $grid->setWidth('cformulator', '100');
                $grid->setAlign('cformulator', 'left');
                $grid->setLabel('cformulator','PIC Formulator Refor');
            
                $grid->setWidth('istatus_terima_req', '100');
                $grid->setAlign('istatus_terima_req', 'left');
                $grid->setLabel('istatus_terima_req','Status Terima Request');
            
                $grid->setWidth('cApproved_terima', '100');
                $grid->setAlign('cApproved_terima', 'left');
                $grid->setLabel('cApproved_terima','Approved By');
            
                $grid->setWidth('dApproved_terima', '100');
                $grid->setAlign('dApproved_terima', 'left');
                $grid->setLabel('dApproved_terima','Tanggal Approve Terima');
            
                $grid->setWidth('vreason_terima', '100');
                $grid->setAlign('vreason_terima', 'left');
                $grid->setLabel('vreason_terima','Alasan Terima');
            
                $grid->setWidth('dTgl_rev_mbr', '100');
                $grid->setAlign('dTgl_rev_mbr', 'left');
                $grid->setLabel('dTgl_rev_mbr','Tanggal Revisi MBR');
            
                $grid->setWidth('vNo_cc', '100');
                $grid->setAlign('vNo_cc', 'left');
                $grid->setLabel('vNo_cc','No. Change Control');
            
                $grid->setWidth('dPengajuan_cc', '100');
                $grid->setAlign('dPengajuan_cc', 'left');
                $grid->setLabel('dPengajuan_cc','Tgl Pengajuan Change Control');
            
                $grid->setWidth('iStatus_cc', '100');
                $grid->setAlign('iStatus_cc', 'left');
                $grid->setLabel('iStatus_cc','Status Approve Change Control');
            
                $grid->setWidth('dApproved_cc', '100');
                $grid->setAlign('dApproved_cc', 'left');
                $grid->setLabel('dApproved_cc','Tgl Approve Change Control');
            
                $grid->setWidth('cApproved_cc', '100');
                $grid->setAlign('cApproved_cc', 'left');
                $grid->setLabel('cApproved_cc','CAPPROVED_CC');
            
                $grid->setWidth('dUji_BE', '100');
                $grid->setAlign('dUji_BE', 'left');
                $grid->setLabel('dUji_BE','DUJI_BE');
            
                $grid->setWidth('dSelesai_uji_BE', '100');
                $grid->setAlign('dSelesai_uji_BE', 'left');
                $grid->setLabel('dSelesai_uji_BE','DSELESAI_UJI_BE');
            
                $grid->setWidth('vNo_hasil_uji_BE', '100');
                $grid->setAlign('vNo_hasil_uji_BE', 'left');
                $grid->setLabel('vNo_hasil_uji_BE','VNO_HASIL_UJI_BE');
            
                $grid->setWidth('vHasil_uji_BE', '100');
                $grid->setAlign('vHasil_uji_BE', 'left');
                $grid->setLabel('vHasil_uji_BE','VHASIL_UJI_BE');
            
                $grid->setWidth('iStatus_uji_BE', '100');
                $grid->setAlign('iStatus_uji_BE', 'left');
                $grid->setLabel('iStatus_uji_BE','ISTATUS_UJI_BE');
            
                $grid->setWidth('dApproved_uji_BE', '100');
                $grid->setAlign('dApproved_uji_BE', 'left');
                $grid->setLabel('dApproved_uji_BE','DAPPROVED_UJI_BE');
            
                $grid->setWidth('cApproved_uji_BE', '100');
                $grid->setAlign('cApproved_uji_BE', 'left');
                $grid->setLabel('cApproved_uji_BE','CAPPROVED_UJI_BE');
            
                $grid->setWidth('dCreate', '100');
                $grid->setAlign('dCreate', 'left');
                $grid->setLabel('dCreate','DCREATE');
            
                $grid->setWidth('cCreated', '100');
                $grid->setAlign('cCreated', 'left');
                $grid->setLabel('cCreated','CCREATED');
            
                $grid->setWidth('dupdate', '100');
                $grid->setAlign('dupdate', 'left');
                $grid->setLabel('dupdate','DUPDATE');
            
                $grid->setWidth('cUpdate', '100');
                $grid->setAlign('cUpdate', 'left');
                $grid->setLabel('cUpdate','CUPDATE');
            
                $grid->setWidth('lDeleted', '100');
                $grid->setAlign('lDeleted', 'left');
                $grid->setLabel('lDeleted','LDELETED');

                $grid->setWidth('uploadFile', '100');
                $grid->setAlign('uploadFile', 'center');
                $grid->setLabel('uploadFile', 'Upload File Reformulasi');

                $grid->setWidth('uploadFileMBR', '100');
                $grid->setAlign('uploadFileMBR', 'center');
                $grid->setLabel('uploadFileMBR', 'Upload File MBR Revisi Change Control');

                $grid->setWidth('nextProses', '100');
                $grid->setAlign('nextProses', 'center');
                $grid->setLabel('nextProses', 'Next Proses');
            
                //Example modifikasi GRID ERP
                /*
                    - Set Query
                        $grid->setQuery('lDeleted = 0 ', null); 
                        $grid->setQuery('plc2_upb.iupb_id IN (select distinct(bk.iupb_id) from plc2.plc2_upb_spesifikasi_fg bk where bk.iappqa=2 and bk.ldeleted=0)', null);  

                    - Join Table
                        $grid->setJoinTable('hrd.employee', 'employee.cNip = pk_master.vnip', 'inner');

                    - Change Field Name
                        $grid->changeFieldType('ideleted','combobox','',array(''=>'Pilih',0=>'Aktif',1=>'Tidak aktif'));
                */

                 //set search
                $grid->setSearch('vNo_req_refor','cNIP','no_produk','vbatch_no');
                
                //set required
                $grid->setRequired('vNo_req_refor','vNo_deviasi','nama_produk','vbatch_no','cNIP','idept_id','vAlasan_refor','uploadFile','iteam_pd','iSubmit','iStatus','cApproval','vRemark','dApproval','cformulator','istatus_terima_req','cApproved_terima','dApproved_terima','vreason_terima','dTgl_rev_mbr','vNo_cc','dPengajuan_cc','iStatus_cc','dApproved_cc','cApproved_cc','dUji_BE','dSelesai_uji_BE','vNo_hasil_uji_BE','vHasil_uji_BE','iStatus_uji_BE','dApproved_uji_BE','cApproved_uji_BE','dCreate','cCreated','dupdate','cUpdate','lDeleted'); 

                $grid->setGridView('grid');

                switch ($action) {
                    case 'json':
                            $grid->getJsonData();
                            break;
                    case 'view':
                            $grid->render_form($this->input->get('id'), true);
                            break;
                    case 'create':
                            $grid->render_form();
                            break;
                    case 'createproses':
                        $isUpload = $this->input->get('isUpload');            
                        if($isUpload) { 
                            $lastId=$this->input->get('lastId');
                        
                            $path = realpath("files/reformulasi/");


                            //File Spesification

                            if(!file_exists($path."/"."mbr_revisi_cc/"."fileMBR/".$lastId)){
                                if (!mkdir($path."/"."mbr_revisi_cc/"."fileMBR/".$lastId, 0777, true)) { 
                                    // die('Failed upload, try again!');
                                    print_r('failed upload, try again');
                                    exit();
                                }
                            }

                            $fileketerangan = array();
                            foreach($_POST as $key=>$value) {                       
                                if ($key == 'fileketerangan_spesification_mbr_revisi_change_control_atc_') {
                                    foreach($value as $k=>$v) {
                                        $fileketerangan[$k] = $v;
                                    }
                                }
                            }

                    
                            $i=0;
                            foreach ($_FILES['fileid_upload_spesification_mbr_revisi_change_control_atc_']["error"] as $key => $error) {
                                if ($error == UPLOAD_ERR_OK) {
                                    $tmp_name = $_FILES['fileid_upload_spesification_mbr_revisi_change_control_atc_']["tmp_name"][$key];
                                    $name =str_replace(' ', '_', $_FILES['fileid_upload_spesification_mbr_revisi_change_control_atc_']["name"][$key]);
                                    $data['filename'] = $name;
                                    $data['dInsertDate'] = date('Y-m-d H:i:s');

                                        if(move_uploaded_file($tmp_name, $path."/"."mbr_revisi_cc/"."fileMBR/".$lastId."/".$name)) {
                                            $sql[]="INSERT INTO plc2.mbr_revisi_change_control_lampiran (imbr_revisi_change_control, vFilename, dCreate, cCreated, vKeterangan, lDeleted) 
                                                    VALUES (".$lastId.",'".$data['filename']."','".$data['dInsertDate']."','".$this->user->gNIP."','".$fileketerangan[$i]."', '0')";
                                            $i++;   
                                        }
                                        else{
                                            echo "Upload ke folder gagal";  
                                        }
                                }
                            }
                            foreach($sql as $q) {
                                try {
                                    $this->db->query($q);
                                }catch(Exception $e) {
                                die($e);
                                }
                            } 

                            $r['message']="Data Berhasil Disimpan"; 
                            $r['status'] = TRUE;
                            $r['last_id'] = $this->input->get('lastId');                    
                            echo json_encode($r);
                            }
                        else{
                            echo $grid->saved_form();
                        }
                break; 
                    case 'update':
                            $grid->render_form($this->input->get('id'));
                            break;
                    case 'updateproses':
                            echo $grid->updated_form();
                            break;
                    case 'delete':
                            echo $grid->delete_row();
                            break; 
                    /*
                        //Ini Merupakan Standart Case Untuk Approve

                        case 'approve':
                            echo $this->approve_view();
                            break;
                        case 'approve_process':
                            echo $this->approve_process();
                            break;
                        case 'reject':
                            echo $this->reject_view();
                            break;
                        case 'reject_process':
                            echo $this->reject_process();
                            break; 
                    */ 
                    default:
                            $grid->render_grid();
                            break;
                }
            }
            //Create Manipulate Field 

            //Jika Ingin Menambahkan Seting grid seperti button edit enable dalam kondisi tertentu
            /* 
            function listBox_Action($row, $actions) {
                if ($row->vNo_Or<>'' || $row->vNo_Or<>NULL) { 
                        unset($actions['edit']);
                }
                return $actions;
            } 
            */

            function whoAmI($nip){
                $sql = 'select b.vDescription as vdepartemen,a.*,b.* 
                        from hrd.employee a 
                        join hrd.msdepartement b on b.iDeptID=a.iDepartementID
                        where a.cNip ="'.$nip.'"
                        ';
                $data = $this->db->query($sql)->row_array();
                return $data;
            }
        
            function insertBox_mbr_revisi_change_control_vNo_req_refor($field, $id) {
                $return = "Auto Generated!!!";
                return $return;
            }
            function updateBox_mbr_revisi_change_control_vNo_req_refor($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                    $return = $value; 
                    $return .= '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';

                } 
                return $return;
            } 

            function insertBox_mbr_revisi_change_control_no_produk($field, $id) {
                $return = '<script>
                        $( "button.icon_pop" ).button({
                            icons: {
                                primary: "ui-icon-newwin"
                            },
                            text: false
                        })
                    </script>';


                $return .= '<input readonly type="text" name="'.$field.'"  id="'.$id.'" class="input_rows1 required" size="30" maxlength = "50" />';

                $return .= '&nbsp;<button class="icon_pop"  onclick="browse(\''.base_url().'processor/reformulasi/browse/upb/?field=mbr_revisi_change_control\',\'Daftar Buyyer\')" type="button">&nbsp;</button>';
                
                return $return;
            }

            function updateBox_mbr_revisi_change_control_no_produk($field, $id, $value, $rowData) {
                $sql = "SELECT
                        a.*
                        , produk.*
                        ,c.*
                        ,d.*
                        FROM (plc2.req_refor)
                        JOIN plc2.req_refor a ON a.Req_refor_ID = plc2.req_refor.Req_refor_ID
                        JOIN (  select * from (
                                select a.idossier_upd_id as pk,a.vUpd_no as no_produk , a.vNama_usulan as nama_produk , '2' as iKey from dossier.dossier_upd a where a.lDeleted=0
                                union 
                                select b.iupb_id as pk ,b.vupb_nomor as no_produk, b.vupb_nama as nama_produk , '1' as iKey from plc2.plc2_upb b where b.lDeleted=0
                            ) as produk) as produk on  produk.pk=a.iNo_usulan and produk.iKey = a.iKey
                        JOIN hrd.employee c on c.cNip =  a.cNIP
                        JOIN hrd.msdepartement d on d.iDeptID = a.idept_id 
                        WHERE a.Req_refor_ID = '".$rowData['Req_refor_ID']."'";
                $req = $this->db->query($sql)->row_array();
                if ($this->input->get('action') == 'view') {
                     $return= $req['no_produk']; 
                }else{
                    $return = $req['no_produk']; 
                    $return .= '<input readonly type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$req['no_produk'].'"/>';
                    $return .= '<input type="hidden" name="mbr_revisi_change_control_iNo_usulan"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$req['pk'].'"/>';
                    $return .= '<input type="hidden" name="mbr_revisi_change_control_iKey"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$req['iKey'].'"/>';

                } 
                return $return;
            } 

            function insertBox_mbr_revisi_change_control_nama_produk($field, $id) {
                $return = '<input readonly type="text" name="'.$field.'"  id="'.$id.'" class="input_rows1 required" size="30" maxlength = "50" />';
                
                return $return;
            }
            
            function updateBox_mbr_revisi_change_control_nama_produk($field, $id, $value, $rowData) {
                $sql = "SELECT
                        a.*
                        , produk.*
                        ,c.*
                        ,d.*
                        FROM (plc2.req_refor)
                        JOIN plc2.req_refor a ON a.Req_refor_ID = plc2.req_refor.Req_refor_ID
                        JOIN (  select * from (
                                select a.idossier_upd_id as pk,a.vUpd_no as no_produk , a.vNama_usulan as nama_produk , '2' as iKey from dossier.dossier_upd a where a.lDeleted=0
                                union 
                                select b.iupb_id as pk ,b.vupb_nomor as no_produk, b.vupb_nama as nama_produk , '1' as iKey from plc2.plc2_upb b where b.lDeleted=0
                            ) as produk) as produk on  produk.pk=a.iNo_usulan and produk.iKey = a.iKey
                        JOIN hrd.employee c on c.cNip =  a.cNIP
                        JOIN hrd.msdepartement d on d.iDeptID = a.idept_id 
                        WHERE a.Req_refor_ID = '".$rowData['Req_refor_ID']."'";
                $req = $this->db->query($sql)->row_array();
                if ($this->input->get('action') == 'view') {
                     $return= $req['nama_produk']; 
                }else{
                    $return = $req['nama_produk']; 
                    $return .= '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="50" value="'.$req['nama_produk'].'"/>';
                

                } 
                return $return;
            } 

            function insertBox_mbr_revisi_change_control_nextProses($field, $id) {
                $return = '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<input class="'.$id.'_1" type="checkbox" name="proses_next_1" value="1"><span class="'.$id.'_1"> Produksi Pilot</span><br>';
                $return .= '<input class="'.$id.'_2" type="checkbox" name="proses_next_2" value="1"><span class="'.$id.'_2"> Stabilita Pilot</span><br><div class="'.$id.'_btm">';
                $return .= '<input class="'.$id.'_3" type="checkbox" name="proses_next_3" value="1"><span class="'.$id.'_3"> Stab Pilot ACC</span>';
                $return .= '<input class="'.$id.'_4" type="checkbox" name="proses_next_4" value="1"><span class="'.$id.'_4"> Stab Pilot Intermediate</span>';
                $return .= '<input class="'.$id.'_5" type="checkbox" name="proses_next_5" value="1"><span class="'.$id.'_5"> Stab Pilot Realtime</span></div>';
                $return .= '<style>
                                .'.$id.'_1{color: green;}
                                .'.$id.'_2{color: blue;}
                                .'.$id.'_btm input{margin-left:10px;}
                                .'.$id.'_3, .'.$id.'_4, .'.$id.'_5{color: red;}
                            </style>';
                $return .= '<script>
                                $(".'.$id.'_btm").hide();
                                $(".'.$id.'_2").change(function() {
                                    if(this.checked) {
                                        $(".'.$id.'_btm").show();
                                    }else{
                                        $(".'.$id.'_btm").hide();
                                        $(".'.$id.'_3").prop("checked", false);
                                        $(".'.$id.'_4").prop("checked", false);
                                        $(".'.$id.'_5").prop("checked", false);
                                    }
                                });
                            </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_nextProses($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                    $return = '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1" size="30" />';
                    $return .= '<input class="'.$id.'_1" type="checkbox" name="next_1" value="1"><span class="'.$id.'_1"> Produksi Pilot</span><br>';
                    $return .= '<input class="'.$id.'_2" type="checkbox" name="next_2" value="1"><span class="'.$id.'_2"> Stabilita Pilot</span><br><div class="'.$id.'_btm">';
                    $return .= '<input class="'.$id.'_3" type="checkbox" name="next_3" value="1"><span class="'.$id.'_3"> Stab Pilot ACC</span>';
                    $return .= '<input class="'.$id.'_4" type="checkbox" name="next_4" value="1"><span class="'.$id.'_4"> Stab Pilot Intermediate</span>';
                    $return .= '<input class="'.$id.'_5" type="checkbox" name="next_5" value="1"><span class="'.$id.'_5"> Stab Pilot Realtime</span></div>';
                    $return .= '<style>
                                    .'.$id.'_1{color: green;}
                                    .'.$id.'_2{color: blue;}
                                    .'.$id.'_btm input{margin-left:10px;}
                                    .'.$id.'_3, .'.$id.'_4, .'.$id.'_5{color: red;}
                                </style>';
                    $return .= '<script>
                                    $(".'.$id.'_btm").hide();
                                    $(".'.$id.'_2").change(function() {
                                        if(this.checked) {
                                            $(".'.$id.'_btm").show();
                                        }else{
                                            $(".'.$id.'_btm").hide();
                                            $(".'.$id.'_3").prop("checked", false);
                                            $(".'.$id.'_4").prop("checked", false);
                                            $(".'.$id.'_5").prop("checked", false);
                                        }
                                    });
                                </script>';

                } 
                return $return;
            } 

            function insertBox_mbr_revisi_change_control_uploadFileMBR($field, $id) {
                $data['imbr_revisi_change_control'] =  '';
                $data['rows'] = array();
                $return = $this->load->view('setting_mbr_cc',$data,TRUE);
                return $return;
            }
            function updateBox_mbr_revisi_change_control_uploadFileMBR($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                    $data['imbr_revisi_change_control'] =  '';
                    $data['rows'] = array();
                    $return = $this->load->view('setting_mbr_cc',$data,TRUE);

                } 
                return $return;
            } 
            
            function insertBox_mbr_revisi_change_control_vNo_deviasi($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_vNo_deviasi($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                    $return = $value; 
                    $return .= '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_iNo_usulan($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_iNo_usulan($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_iKey($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_iKey($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_vbatch_no($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_vbatch_no($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                    $return = $value; 
                    $return .= '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_cNIP($field, $id) {
                $sql = "SELECT vName FROM hrd.employee WHERE cNip = '".$this->user->gNIP."'";
                $dt = $this->db->query($sql)->row_array();
                $return = $this->user->gNIP." || ".$dt['vName'];
                $return .= '<input type="hidden" name="'.$field.'"  id="'.$id.'" value="'.$this->user->gNIP.'"  class="input_rows1 required" size="30" maxlength = "50"/>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_cNIP($field, $id, $value, $rowData) {
                $sql = "SELECT vName FROM hrd.employee WHERE cNip = '".$value."' LIMIT 1";
                $emp = $this->db->query($sql)->row_array();
                if ($this->input->get('action') == 'view') {
                     $return= $value." || ".$emp['vName']; 
                }else{
                    $return = $value." || ".$emp['vName']; 
                    $return .= '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_idept_id($field, $id) {
                $iam = $this->whoAmI($this->user->gNIP);
                $return = $iam['vdepartemen']; 
                $return .= '<input type="hidden" name="'.$field.'"  id="'.$id.'" value="'.$iam['iDepartementID'].'"  class="input_rows1 required" size="30" />';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_idept_id($field, $id, $value, $rowData) {
                $sql = "SELECT vDescription FROM msdepartement WHERE iDeptID = '".$value."' LIMIT 1";
                $dept = $this->db->query($sql)->row_array();
                if ($this->input->get('action') == 'view') {
                     $return= $dept['vDescription']; 
                }else{
                    $return = $dept['vDescription']; 
                    $return .= '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_tTanggal_usulan_refor($field, $id) {
                $date = date('Y-m-d');
                $return = '<input readonly type="text" name="'.$field.'"  id="'.$id.'" value="'.$date.'"  class="input_rows1 required" size="30" />';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_tTanggal_usulan_refor($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = $value; 
                        $return .= '<input type="hidden" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_vAlasan_refor($field, $id) {
                $return = '<textarea name="'.$field.'" id="'.$id.'" class="required" style="width: 240px; height: 50px;" size="250"></textarea>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_vAlasan_refor($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= '<label title="Note">'.nl2br($value).'</label>'; 
                }else{
                    $return = '<textarea readonly type="hidden" name="'.$field.'" id="'.$id.'" class="required" style="width: 240px; height: 50px;" size="250" maxlength ="250">'.nl2br($value).'</textarea>';
                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_iteam_pd($field, $id) {
                $sql = "SELECT t.vteam
                        FROM plc2.plc2_upb_team t 
                        LEFT JOIN plc2.plc2_upb_team_item i ON t.iteam_id = i.iteam_id
                        WHERE t.ldeleted = 0 AND i.vnip = '".$this->user->gNIP."' AND i.ldeleted = 0";
                $teams = $this->db->query($sql)->row_array();
                $return = $teams['vteam'];
                $return .= '<input type="hidden" name="'.$field.'"  id="'.$id.'" value="'.$teams['iteam_id'].'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_iteam_pd($field, $id, $value, $rowData) {
                $sql = "SELECT * FROM plc2.plc2_upb_team WHERE iteam_id = '".$value."' AND ldeleted = '0';";
                $teams = $this->db->query($sql)->row_array();
                if ($this->input->get('action') == 'view') {
                     $return= $teams['vteam']; 
                }else{
                    $return = $teams['vteam']; 
                    $return .= '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_iSubmit($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_iSubmit($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_iStatus($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_iStatus($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_cApproval($field, $id) {
                $return = 'No Approval';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_cApproval($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_vRemark($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "200" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 200);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(200 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">200</span> karakter<br/>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_vRemark($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "200"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 200);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(200 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">200</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_dApproval($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"}); 
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_dApproval($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = '<input type="text" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_cformulator($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_cformulator($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_istatus_terima_req($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_istatus_terima_req($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_cApproved_terima($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_cApproved_terima($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_dApproved_terima($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"}); 
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_dApproved_terima($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = '<input type="text" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_vreason_terima($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "200" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 200);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(200 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">200</span> karakter<br/>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_vreason_terima($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "200"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 200);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(200 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">200</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_dTgl_rev_mbr($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"}); 
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_dTgl_rev_mbr($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = '<input type="text" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_vNo_cc($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_vNo_cc($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_dPengajuan_cc($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"}); 
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_dPengajuan_cc($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = '<input type="text" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_iStatus_cc($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_iStatus_cc($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_dApproved_cc($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"}); 
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_dApproved_cc($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = '<input type="text" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_cApproved_cc($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_cApproved_cc($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_dUji_BE($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"}); 
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_dUji_BE($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = '<input type="text" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_dSelesai_uji_BE($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"}); 
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_dSelesai_uji_BE($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = '<input type="text" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_vNo_hasil_uji_BE($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_vNo_hasil_uji_BE($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_vHasil_uji_BE($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_vHasil_uji_BE($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_iStatus_uji_BE($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_iStatus_uji_BE($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_dApproved_uji_BE($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"}); 
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_dApproved_uji_BE($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = '<input type="text" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_cApproved_uji_BE($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_cApproved_uji_BE($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_dCreate($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"}); 
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_dCreate($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = '<input type="text" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_cCreated($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_cCreated($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_dupdate($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"}); 
                             </script>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_dupdate($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = '<input type="text" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_cUpdate($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_mbr_revisi_change_control_cUpdate($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_mbr_revisi_change_control_lDeleted($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                            </script>';
                return $return;
            }

            function updateBox_mbr_revisi_change_control_lDeleted($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                } 
                return $return;
            }   
            
            /*
                //Ini Merupakan Standart Approve yang digunakan di erp
 
                function approve_view() {
                    $echo = '<script type="text/javascript">
                                 function submit_ajax(form_id) {
                                    return $.ajax({
                                        url: $("#"+form_id).attr("action"),
                                        type: $("#"+form_id).attr("method"),
                                        data: $("#"+form_id).serialize(),
                                        success: function(data) {
                                            var o = $.parseJSON(data);
                                            var last_id = o.last_id;
                                            var url = "'.base_url().'processor/reformulasi/mbr_revisi_change_control";                             
                                            if(o.status == true) { 
                                                $("#alert_dialog_form").dialog("close");
                                                     $.get(url+"?action=update&id="+last_id, function(data) {
                                                     $("div#form_mbr_revisi_change_control").html(data);
                                                     
                                                });
                                                
                                            }
                                                reload_grid("grid_mbr_revisi_change_control");
                                        }
                                        
                                     })
                                 }
                             </script>';
                    $echo .= '<h1>Approve</h1><br />';
                    $echo .= '<form id="form_mbr_revisi_change_control_approve" action="'.base_url().'processor/reformulasi/mbr_revisi_change_control?action=approve_process" method="post">';
                    $echo .= '<div style="vertical-align: top;">';
                    $echo .= 'Remark : 
                            <input type="hidden" name="Req_refor_ID" value="'.$this->input->get('Req_refor_ID').'" />
                            <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                            <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                            <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                            <textarea name="vRemark"></textarea>
                    <button type="button" onclick="submit_ajax(\'form_mbr_revisi_change_control\')">Approve</button>';
                        
                    $echo .= '</div>';
                    $echo .= '</form>';
                    return $echo;
                } 
 
                function approve_process() {
                    $post = $this->input->post();
                    $cNip= $this->user->gNIP;
                    $vName= $this->user->gName;
                    $Req_refor_ID = $post['Req_refor_ID'];
                    $vRemark = $post['vRemark'];
                    $lvl = $post['lvl'];
 
                    //Letakan Query Update approve disini

                    $data['status']  = true;
                    $data['last_id'] = $post['Req_refor_ID'];
                    return json_encode($data);
                }
            */

        
            /*
                //Ini Merupakan Standart Reject yang digunakan di erp

                function reject_view() {
                    $echo = '<script type="text/javascript">
                                 function submit_ajax(form_id) {
                                    var remark = $("#mbr_revisi_change_control_remark").val();
                                    if (remark=="") {
                                        alert("Remark tidak boleh kosong ");
                                        return
                                    }

                                    return $.ajax({
                                        url: $("#"+form_id).attr("action"),
                                        type: $("#"+form_id).attr("method"),
                                        data: $("#"+form_id).serialize(),
                                        success: function(data) {
                                            var o = $.parseJSON(data);
                                            var last_id = o.last_id;
                                            var url = "'.base_url().'processor/reformulasi/mbr_revisi_change_control";                             
                                            if(o.status == true) { 
                                                $("#alert_dialog_form").dialog("close");
                                                     $.get(url+"?action=update&id="+last_id, function(data) {
                                                     $("div#form_mbr_revisi_change_control").html(data);
                                                     
                                                });
                                                
                                            }
                                                reload_grid("grid_mbr_revisi_change_control");
                                        }
                                        
                                     })
                                 }
                             </script>';
                    $echo .= '<h1>Reject</h1><br />';
                    $echo .= '<form id="form_mbr_revisi_change_control_reject" action="'.base_url().'processor/reformulasi/mbr_revisi_change_control?action=reject_process" method="post">';
                    $echo .= '<div style="vertical-align: top;">';
                    $echo .= 'Remark : 
                            <input type="hidden" name="Req_refor_ID" value="'.$this->input->get('Req_refor_ID').'" />
                            <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                            <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                            <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                            <textarea name="vRemark" id="reject_mbr_revisi_change_control_remark"></textarea>
                    <button type="button" onclick="submit_ajax(\'form_mbr_revisi_change_control_reject\')">Reject</button>';
                        
                    $echo .= '</div>';
                    $echo .= '</form>';
                    return $echo;
                }


                
                function reject_process() {
                    $post = $this->input->post();
                    $cNip= $this->user->gNIP;
                    $vName= $this->user->gName;
                    $Req_refor_ID = $post['Req_refor_ID'];
                    $vRemark = $post['vRemark'];
                    $lvl = $post['lvl'];
 
                    //Letakan Query Update approve disini

                    $data['status']  = true;
                    $data['last_id'] = $post['Req_refor_ID'];
                    return json_encode($data);
                }
            */

        
            //Standart Setiap table harus memiliki dCreate , cCreated, dupdate, cUpdate
            function before_insert_processor($row, $postData) {
                $postData['dCreate'] = date('Y-m-d H:i:s');
                $postData['cCreated']=$this->user->gNIP;
                return $postData;

            }
            function before_update_processor($row, $postData) {
                $postData['dupdate'] = date('Y-m-d H:i:s');
                $postData['cUpdate'] = $this->user->gNIP;
                return $postData; 
            }    
        
            function after_insert_processor($fields, $id, $postData) {
                //Example After Insert
                /*
                $cNip = $this->sess_auth->gNIP; 
                $sql = 'Place Query In Here';
                $this->dbset->query($sql);
                */
            }
    
            function after_update_processor($fields, $id, $postData) {
                $produksi_pilot     = $postData['proses_next_1'];
                $stab_pilot_acc     = $postData['proses_next_3'];
                if ($stab_pilot_acc == 1){
                    $this->insertNextProsesStabilita($postData, 9);
                }
                $stab_pilot_intr    = $postData['proses_next_4'];
                if ($stab_pilot_intr == 1){
                    $this->insertNextProsesStabilita($postData, 10);
                }
                $stab_pilot_realt   = $postData['proses_next_5'];
                if ($stab_pilot_realt == 1){
                    $this->insertNextProsesStabilita($postData, 11);
                }


                //Example After Update
                /*
                $cNip = $this->sess_auth->gNIP; 
                $sql = 'Place Query In Here';
                $this->dbset->query($sql);
                */
            }
            function manipulate_update_button($buttons, $rowData) { 
                //Load Javascript In Here 
                if ($this->input->get('action') == 'view') {
                    unset($buttons['update']);
                }
                else{ 
                    
                }

                /*reference to schedulercheck/views/sourceModul */
                
                /*reference to schedulercheck/views/sourceJS */
                //$js = $this->load->view('standardJS');
                //$js = $this->load->view('numberJS');
                //$js = $this->load->view('uploadjs');

                
                return $buttons;
            }
            function manipulate_insert_button($buttons) { 
                //unset($buttons['save']);

                /*reference to schedulercheck/views/sourceModul */

                /*reference to schedulercheck/views/sourceJS */
                //$js = $this->load->view('standardJS');
                //$js = $this->load->view('numberJS');
                //$js = $this->load->view('uploadjs');
                
                return $buttons;
            }

            function insertNextProsesStabilita ($postData, $flow) {
                //get last version
                $lastVer = 0;
                $sql1 = "SELECT b.iVersi 
                        FROM pddetail.formula_process a
                        LEFT JOIN pddetail.formula_stabilita b ON a.iFormula_process = b.iFormula_process
                        WHERE a.iupb_id = '".$postData['no_produk']."' 
                        ORDER BY a.dCreate DESC LIMIT 1";
                $dtVer = $this->db->query($sql1)->row_array();
                if (!empty($dtVer)){
                    $lastVer = $dtVer['iVersi'];
                }

                //insert ke formula_process
                $sqlto_Back = "INSERT pddetail.`formula_process` (`iupb_id`,`iMaster_flow`,`cCreated`,dCreate,ij_product, irefor) VALUES ('".$postData['no_produk']."','".$flow."','".$postData['cNIP']."',SYSDATE(),'".$postData['iKey']-1."' , '1')";
                $this->db->query($sqlto_Back);
                $iFormula_process = $this->db->insert_id();

                $insertProses_detail = "INSERT INTO pddetail.`formula_process_detail`(iFormula_process, cPic, iProses_id, is_proses, dStart_time, cCreated, dCreate) VALUES ('".$iFormula_process."','".$postData['cNIP']."','1','1','".$dFinish_time."','".$postData['cNIP']."',SYSDATE())";
                $this->db->query($insertProses_detail);

                // //Insert to Formula
                $iFd ='INSERT INTO pddetail.`formula_stabilita` (iFormula_process,vNo_formula,iVersi,dCreate,cCreated) VALUES("'.$iFormula_process.'","'.$_POST['vNo_formula'].'","'.$lastVer.'",SYSDATE(),"'.$postData['cNIP'].'")';   
                $this->db->query($iFd);
            }

            //Output
            public function output(){
                $this->index($this->input->get('action'));
            }
        }