
        <?php
        /* Generated by Sovdev 2 ERP CRUD Generator 2018-04-12 14:54:15 */
        /* Location: ./modules/reformulasi/controllers/export_studi_literatur_ad.php */
        /* Please DO NOT modify this information : */

        if ( ! defined('BASEPATH')) exit('No direct script access allowed');
        class export_studi_literatur_ad extends MX_Controller {
            function __construct() {
                parent::__construct();
                $this->load->library('auth');
                $this->load->library('auth_export');

                $this->db = $this->load->database('formulasi', false, true);
                $this->user = $this->auth->user();
            }
            function index($action = '') {
                $action = $this->input->get('action');
                //Bikin Object Baru Nama nya $grid
                $grid = new Grid;
                $grid->setTitle('Studi Literatur AD');
                $grid->setTable('reformulasi.export_refor_studi_literatur_ad');
                $grid->setUrl('export_studi_literatur_ad');

                //List Table
                $grid->addList('export_req_refor.vno_export_req_refor','itemas.c_itnam','dmulaistudiAD','dselesaistudiAD','employee.vName','isubmitAd', 'iappAd');
                $grid->setSortBy('iexport_refor_studi_literatur_ad');
                $grid->setSortOrder('desc');

                //List field
                $grid->addFields('iexport_req_refor','dmulaistudiAD','dselesaistudiAD','cPicstudiAD','iUjiMikrofg','ifileliteratur','ifileliterturother','iappAd');

                //Setting Grid Width Name
                /*
                    Kamu bisa merubah nama label dari sini, Contoh :
                    $grid->setLabel('nama field','nama field yang akan diubah');

                */

                $grid->setWidth('export_req_refor.vno_export_req_refor', '80');
                $grid->setAlign('export_req_refor.vno_export_req_refor', 'left');
                $grid->setLabel('export_req_refor.vno_export_req_refor','No Req Refor');

                $grid->setWidth('ifileliteratur', '150');
                $grid->setAlign('ifileliteratur', 'left');
                $grid->setLabel('ifileliteratur','Upload File Study Literatur');

                $grid->setWidth('ifileliterturother', '150');
                $grid->setAlign('ifileliterturother', 'left');
                $grid->setLabel('ifileliterturother','Upload File Lainya');

                $grid->setWidth('iexport_req_refor', '150');
                $grid->setAlign('iexport_req_refor', 'left');
                $grid->setLabel('iexport_req_refor','Request Refor');

                $grid->setWidth('employee.vName', '150');
                $grid->setAlign('employee.vName', 'left');
                $grid->setLabel('employee.vName','PIC Study Literatur AD');



                $grid->setWidth('dCreate', '100');
                $grid->setAlign('dCreate', 'left');
                $grid->setLabel('dCreate','DCREATE');

                $grid->setWidth('itemas.c_itnam', '100');
                $grid->setAlign('itemas.c_itnam', 'left');
                $grid->setLabel('itemas.c_itnam','Nama Product');

                $grid->setWidth('cCreated', '100');
                $grid->setAlign('cCreated', 'left');
                $grid->setLabel('cCreated','CCREATED');

                $grid->setWidth('dupdate', '100');
                $grid->setAlign('dupdate', 'left');
                $grid->setLabel('dupdate','DUPDATE');

                $grid->setWidth('cUpdate', '100');
                $grid->setAlign('cUpdate', 'left');
                $grid->setLabel('cUpdate','CUPDATE');

                $grid->setWidth('dmulaistudiAD', '150');
                $grid->setAlign('dmulaistudiAD', 'left');
                $grid->setLabel('dmulaistudiAD','Tanggal Mulai Study Literatur AD');

                $grid->setWidth('dselesaistudiAD', '150');
                $grid->setAlign('dselesaistudiAD', 'left');
                $grid->setLabel('dselesaistudiAD','Tanggal Selesai Study Literatur AD');

                $grid->setWidth('cPicstudiAD', '100');
                $grid->setAlign('cPicstudiAD', 'left');
                $grid->setLabel('cPicstudiAD','PIC Study Literatur AD');

                $grid->setWidth('iUjiMikrofg', '150');
                $grid->setAlign('iUjiMikrofg', 'left');
                $grid->setLabel('iUjiMikrofg','Perlu Uji Mikro FG ?');

                $grid->setWidth('cappAd', '100');
                $grid->setAlign('cappAd', 'left');
                $grid->setLabel('cappAd','');

                $grid->setWidth('dappAd', '100');
                $grid->setAlign('dappAd', 'left');
                $grid->setLabel('dappAd','DAPPAD');

                $grid->setWidth('tappAd', '100');
                $grid->setAlign('tappAd', 'left');
                $grid->setLabel('tappAd','TAPPAD');

                $grid->setWidth('iappAd', '100');
                $grid->setAlign('iappAd', 'left');
                $grid->setLabel('iappAd','Approve by AD Manager');

                $grid->setWidth('isubmitAd', '100');
                $grid->setAlign('isubmitAd', 'left');
                $grid->setLabel('isubmitAd','Status Submited');

                $grid->setWidth('lDeleted', '100');
                $grid->setAlign('lDeleted', 'left');
                $grid->setLabel('lDeleted','LDELETED');

                //Example modifikasi GRID ERP
                /*
                    - Set Query
                        $grid->setQuery('lDeleted = 0 ', null);
                        $grid->setQuery('plc2_upb.iupb_id IN (select distinct(bk.iupb_id) from plc2.plc2_upb_spesifikasi_fg bk where bk.iappqa=2 and bk.ldeleted=0)', null);

                    - Join Table
                        $grid->setJoinTable('hrd.employee', 'employee.cNip = pk_master.vnip', 'inner');

                    - Change Field Name
                        $grid->changeFieldType('ideleted','combobox','',array(''=>'Pilih',0=>'Aktif',1=>'Tidak aktif'));
                */

                 //set search
                $grid->setJoinTable('reformulasi.export_req_refor', 'export_req_refor.iexport_req_refor = export_refor_studi_literatur_ad.iexport_req_refor', 'inner');
                $grid->setJoinTable('dossier.dossier_upd', 'dossier_upd.idossier_upd_id = export_req_refor.idossier_upd_id', 'inner');
                $grid->setJoinTable('sales.itemas', 'itemas.c_iteno = dossier_upd.iupb_id', 'inner');

                $grid->setJoinTable('hrd.employee', 'employee.cNip = export_refor_studi_literatur_ad.cPicstudiAD', 'inner');

                $grid->setSearch('export_req_refor.vno_export_req_refor','itemas.c_itnam','employee.vName');


                $grid->changeFieldType('isubmitAd','combobox','',array(0=>'Draft',1=>'Submitted'));

                //set required
                $grid->setQuery('export_refor_studi_literatur_ad.lDeleted',0);
                $grid->setRequired('iexport_req_refor','dmulaistudiAD','dselesaistudiAD','cPicstudiAD','iUjiMikrofg','iappAd','isubmitAd','lDeleted');

                $grid->setGridView('grid');

                switch ($action) {
                    case 'json':
                            $grid->getJsonData();
                            break;
                    case 'view':
                            $grid->render_form($this->input->get('id'), true);
                            break;
                    case 'create':
                            $grid->render_form();
                            break;
                    case 'createproses':
                            // echo $grid->saved_form();
                            // break;

                            $isUpload = $this->input->get('isUpload');
                            if($isUpload) {
                                $lastId=$this->input->get('lastId');
                                $path = realpath("files/reformulasi/");

                                /* Upload Trial */
                                if(!file_exists($path."/"."export/export_studi_literatur_ad"."/".$lastId)){
                                    if (!mkdir($path."/"."export/export_studi_literatur_ad"."/".$lastId, 0777, true)) {
                                        die('Failed upload, try again!');
                                    }
                                }
                                $fileketerangan = array();
                                foreach($_POST as $key=>$value) {
                                    if ($key == 'fileketerangan_export_studi_literatur_ad_file') {
                                        foreach($value as $k=>$v) {
                                            $fileketerangan[$k] = $v;
                                        }
                                    }
                                }
                                $i=0;
                                $sql = array();
                                foreach ($_FILES['fileid_export_studi_literatur_ad_file_upload_export_studi_literatur_ad_file']["error"] as $key => $error) {
                                    if ($error == UPLOAD_ERR_OK) {
                                        $tmp_name = $_FILES['fileid_export_studi_literatur_ad_file_upload_export_studi_literatur_ad_file']["tmp_name"][$key];
                                        $name =$_FILES['fileid_export_studi_literatur_ad_file_upload_export_studi_literatur_ad_file']["name"][$key];
                                        $data['filename'] = $name;
                                        $data['dInsertDate'] = date('Y-m-d H:i:s');

                                            if(move_uploaded_file($tmp_name, $path."/"."export/export_studi_literatur_ad"."/".$lastId."/".$name)) {

                                                $sql[]="INSERT INTO reformulasi.export_refor_studi_literatur_ad_file(iexport_refor_studi_literatur_ad,
                                                        vFilename, dCreate, cCreated, ijenisFolde,
                                                        tKeterangan)
                                                        VALUES (".$lastId.",'".$data['filename']."',
                                                            '".$data['dInsertDate']."','".$this->user->gNIP."',0,
                                                            '".$fileketerangan[$i]."')";

                                                $i++;
                                            }
                                            else{
                                                echo "Upload ke folder gagal";
                                            }
                                    }
                                }
                                foreach($sql as $q) {
                                    try {
                                        $this->db->query($q);
                                    }catch(Exception $e) {
                                    die($e);
                                    }
                                }

                                /*Other*/

                                if(!file_exists($path."/"."export/export_studi_literatur_ad_other"."/".$lastId)){
                                    if (!mkdir($path."/"."export/export_studi_literatur_ad_other"."/".$lastId, 0777, true)) {
                                        die('Failed upload, try again!');
                                    }
                                }
                                $fileketerangan = array();
                                foreach($_POST as $key=>$value) {
                                    if ($key == 'fileketerangan_export_studi_literatur_ad_other_file') {
                                        foreach($value as $k=>$v) {
                                            $fileketerangan[$k] = $v;
                                        }
                                    }
                                }
                                $i=0;
                                $sql = array();
                                foreach ($_FILES['fileid_export_studi_literatur_ad_other_file_upload_export_studi_literatur_ad_other_file']["error"] as $key => $error) {
                                    if ($error == UPLOAD_ERR_OK) {
                                        $tmp_name = $_FILES['fileid_export_studi_literatur_ad_other_file_upload_export_studi_literatur_ad_other_file']["tmp_name"][$key];
                                        $name =$_FILES['fileid_export_studi_literatur_ad_other_file_upload_export_studi_literatur_ad_other_file']["name"][$key];
                                        $data['filename'] = $name;
                                        $data['dInsertDate'] = date('Y-m-d H:i:s');

                                            if(move_uploaded_file($tmp_name, $path."/"."export/export_studi_literatur_ad_other"."/".$lastId."/".$name)) {

                                                $sql[]="INSERT INTO reformulasi.export_refor_studi_literatur_ad_file(iexport_refor_studi_literatur_ad,
                                                        vFilename, dCreate, cCreated, ijenisFolde,
                                                        tKeterangan)
                                                        VALUES (".$lastId.",'".$data['filename']."',
                                                            '".$data['dInsertDate']."','".$this->user->gNIP."',1,
                                                            '".$fileketerangan[$i]."')";

                                                $i++;
                                            }
                                            else{
                                                echo "Upload ke folder gagal";
                                            }
                                    }
                                }
                                foreach($sql as $q) {
                                    try {
                                        $this->db->query($q);
                                    }catch(Exception $e) {
                                    die($e);
                                    }
                                }


                            }else{
                                echo $grid->saved_form();
                            }
                            break;
                    case 'update':
                            $grid->render_form($this->input->get('id'));
                            break;
                    case 'updateproses':
                            $isUpload = $this->input->get('isUpload');
                            $lastId=$_POST['iexport_refor_studi_literatur_ad'];
                            if($isUpload) {
                               $path = realpath("files/reformulasi/");

                                /* Upload Trial */
                                if(!file_exists($path."/"."export/export_studi_literatur_ad"."/".$lastId)){
                                    if (!mkdir($path."/"."export/export_studi_literatur_ad"."/".$lastId, 0777, true)) {
                                        die('Failed upload, try again!');
                                    }
                                }
                                $fileketerangan = array();
                                foreach($_POST as $key=>$value) {
                                    if ($key == 'fileketerangan_export_studi_literatur_ad_file') {
                                        foreach($value as $k=>$v) {
                                            $fileketerangan[$k] = $v;
                                        }
                                    }
                                }
                                $i=0;
                                $sql = array();
                                foreach ($_FILES['fileid_export_studi_literatur_ad_file_upload_export_studi_literatur_ad_file']["error"] as $key => $error) {
                                    if ($error == UPLOAD_ERR_OK) {
                                        $tmp_name = $_FILES['fileid_export_studi_literatur_ad_file_upload_export_studi_literatur_ad_file']["tmp_name"][$key];
                                        $name =$_FILES['fileid_export_studi_literatur_ad_file_upload_export_studi_literatur_ad_file']["name"][$key];
                                        $data['filename'] = $name;
                                        $data['dInsertDate'] = date('Y-m-d H:i:s');

                                            if(move_uploaded_file($tmp_name, $path."/"."export/export_studi_literatur_ad"."/".$lastId."/".$name)) {

                                                $sql[]="INSERT INTO reformulasi.export_refor_studi_literatur_ad_file(iexport_refor_studi_literatur_ad,
                                                        vFilename, dCreate, cCreated, ijenisFolde,
                                                        tKeterangan)
                                                        VALUES (".$lastId.",'".$data['filename']."',
                                                            '".$data['dInsertDate']."','".$this->user->gNIP."',0,
                                                            '".$fileketerangan[$i]."')";

                                                $i++;
                                            }
                                            else{
                                                echo "Upload ke folder gagal";
                                            }
                                    }
                                }
                                foreach($sql as $q) {
                                    try {
                                        $this->db->query($q);
                                    }catch(Exception $e) {
                                    die($e);
                                    }
                                }

                                /*Other*/

                                if(!file_exists($path."/"."export/export_studi_literatur_ad_other"."/".$lastId)){
                                    if (!mkdir($path."/"."export/export_studi_literatur_ad_other"."/".$lastId, 0777, true)) {
                                        die('Failed upload, try again!');
                                    }
                                }
                                $fileketerangan = array();
                                foreach($_POST as $key=>$value) {
                                    if ($key == 'fileketerangan_export_studi_literatur_ad_other_file') {
                                        foreach($value as $k=>$v) {
                                            $fileketerangan[$k] = $v;
                                        }
                                    }
                                }
                                $i=0;
                                $sql = array();
                                foreach ($_FILES['fileid_export_studi_literatur_ad_other_file_upload_export_studi_literatur_ad_other_file']["error"] as $key => $error) {
                                    if ($error == UPLOAD_ERR_OK) {
                                        $tmp_name = $_FILES['fileid_export_studi_literatur_ad_other_file_upload_export_studi_literatur_ad_other_file']["tmp_name"][$key];
                                        $name =$_FILES['fileid_export_studi_literatur_ad_other_file_upload_export_studi_literatur_ad_other_file']["name"][$key];
                                        $data['filename'] = $name;
                                        $data['dInsertDate'] = date('Y-m-d H:i:s');

                                            if(move_uploaded_file($tmp_name, $path."/"."export/export_studi_literatur_ad_other"."/".$lastId."/".$name)) {

                                                $sql[]="INSERT INTO reformulasi.export_refor_studi_literatur_ad_file(iexport_refor_studi_literatur_ad,
                                                        vFilename, dCreate, cCreated, ijenisFolde,
                                                        tKeterangan)
                                                        VALUES (".$lastId.",'".$data['filename']."',
                                                            '".$data['dInsertDate']."','".$this->user->gNIP."',1,
                                                            '".$fileketerangan[$i]."')";

                                                $i++;
                                            }
                                            else{
                                                echo "Upload ke folder gagal";
                                            }
                                    }
                                }
                                foreach($sql as $q) {
                                    try {
                                        $this->db->query($q);
                                    }catch(Exception $e) {
                                    die($e);
                                    }
                                }

                            }else{
                                $fileid1='';
                                foreach($_POST as $key=>$value) {
                                    if ($key == 'fileid_export_studi_literatur_ad_file') {
                                        $i=0;
                                        foreach($value as $k=>$v) {
                                            if($i==0){
                                                $fileid1 .= "'".$v."'";
                                            }else{
                                                $fileid1 .= ",'".$v."'";
                                            }
                                            $i++;
                                        }
                                    }
                                }
                                $tgl= date('Y-m-d H:i:s');

                                $sql1="update reformulasi.export_refor_studi_literatur_ad_file set lDeleted=1,
                                    dupdate='".$tgl."', cUpdate='".$this->user->gNIP."' where
                                    iexport_refor_studi_literatur_ad='".$lastId."' and ijenisFolde=0 and
                                    iexport_refor_studi_literatur_ad_file not in (".$fileid1.")";
                                $this->db->query($sql1);


                                $fileid1='';
                                foreach($_POST as $key=>$value) {
                                    if ($key == 'fileid_export_studi_literatur_ad_other_file') {
                                        $i=0;
                                        foreach($value as $k=>$v) {
                                            if($i==0){
                                                $fileid1 .= "'".$v."'";
                                            }else{
                                                $fileid1 .= ",'".$v."'";
                                            }
                                            $i++;
                                        }
                                    }
                                }
                                $tgl= date('Y-m-d H:i:s');

                                $sql1="update reformulasi.export_refor_studi_literatur_ad_file set lDeleted=1,
                                    dupdate='".$tgl."', cUpdate='".$this->user->gNIP."' where
                                    iexport_refor_studi_literatur_ad='".$lastId."' and ijenisFolde=1 and
                                    iexport_refor_studi_literatur_ad_file not in (".$fileid1.")";
                                $this->db->query($sql1);

                                echo $grid->updated_form();
                            }
                            break;
                    case 'delete':
                            echo $grid->delete_row();
                            break;
                    case 'download1':
                            $this->download1($this->input->get('file'));
                            break;
                    case 'download2':
                            $this->download2($this->input->get('file'));
                            break;
                    case 'searchcNip':
                        echo $this->searchcNip();
                        break;

                        //Ini Merupakan Standart Case Untuk Approve

                        case 'approve':
                            echo $this->approve_view();
                            break;
                        case 'approve_process':
                            echo $this->approve_process();
                            break;
                        case 'reject':
                            echo $this->reject_view();
                            break;
                        case 'reject_process':
                            echo $this->reject_process();
                            break;

                    default:
                            $grid->render_grid();
                            break;
                }
            }
            //Create Manipulate Field

            //Jika Ingin Menambahkan Seting grid seperti button edit enable dalam kondisi tertentu

            function listBox_Action($row, $actions) {
                if ($row->iappAd<>0) {
                        unset($actions['edit']);
                }
                return $actions;
            }




            public function searchcNip() {
                $tgl        = date('Y-m-d');
                $term       = $this->input->get('term');

                $data = array();

                //$sql = "select cNip, vName from hrd.employee where (cNip like '%{$term}%') limit 1 ";
                $sql = "SELECT a.cNip,a.vName,a.iDivisionID,a.iDepartementId,a.ibagid,a.iArea,a.iPostId,
                        (SELECT vDescription FROM hrd.msdivision WHERE iDivID=a.iDivisionID) AS divisi,
                        (SELECT vDescription FROM hrd.msdepartement WHERE iDeptID=a.iDepartementId) AS departement,
                        (SELECT vDescription FROM hrd.bagian WHERE ibagid=a.ibagid) AS bagian,
                        (SELECT vAreaname FROM hrd.area WHERE iAreaID=a.iArea) AS vAreaname,
                        (SELECT vDescription FROM hrd.position WHERE iPostId=a.iPostId) AS jabatan,
                        (SELECT c.vDescription FROM hrd.position AS b LEFT JOIN hrd.lvlemp AS c ON c.iLvlEmp=b.iLvlID
                          WHERE b.iPostId=a.iPostID) AS lvlemply

                        FROM hrd.employee AS a WHERE
                        (a.dresign='0000-00-00' OR a.dresign>'".date('Y-m-d H:i:s')."') AND
                        (a.cNip LIKE '%{$term}%' OR a.vName LIKE '%{$term}%') limit 50";
                //echo $sql;exit;

                $query = $this->db->query($sql);
                if ($query->num_rows > 0) {
                    foreach($query->result_array() as $line) {
                        $row_array['id']        = trim($line['cNip']);
                        $row_array['value']     = trim($line['cNip']).' - '.trim($line['vName']);
                        $row_array['divisi']    = trim($line['divisi']);
                        $row_array['vAreaname'] = trim($line['vAreaname']);
                        $row_array['jabatan']   = trim($line['jabatan']);
                        $row_array['departement']   = trim($line['departement']);
                        $row_array['bagian']        = trim($line['bagian']);
                        $row_array['lvlemply']      = trim($line['lvlemply']);

                        $row_array['iDivisionID']   = trim($line['iDivisionID']);
                        $row_array['iDepartementId']    = trim($line['iDepartementId']);
                        $row_array['ibagid']        = trim($line['ibagid']);
                        $row_array['iArea']         = trim($line['iArea']);
                        $row_array['iPostId']       = trim($line['iPostId']);

                        array_push($data, $row_array);
                    }
                }

                echo json_encode($data);
                exit;
            }

            function listBox_export_studi_literatur_ad_iappAd($value) {
                if($value==0){$vstatus='Waiting for approval';}
                elseif($value==1){$vstatus='Rejected';}
                elseif($value==2){$vstatus='Approved';}
                return $vstatus;
            }

            function insertBox_export_studi_literatur_ad_iexport_req_refor($field, $id) {
                $uri = 'export_studi_literatur_ad';
                $o = "";
                $o   .= "<div style='
                                padding: 3px;
                                width: 500px;
                                border: 1px solid rgba(51, 23, 93, 0.2);
                                background-color: #FFF;'>";


                $o   .= "<table border='0' style='width: 100%;'>
                            <tbody>";
                $o  .="         <tr>
                                    <td width='20%'>No Request</td>
                                    <td>:</td>
                                    <td width='75%'>";
                $o .= '         <input type="hidden" name="'.$field.'"  id="'.$id.'"  class="'.$id.' input_rows1 required" size="30" />';
                $o .= '         <input readonly type="text" name="'.$uri.'_vno_export_req_refor"  id="'.$uri.'_vno_export_req_refor"  class="'.$uri.'_vno_export_req_refor required input_rows1" size="30" />';
                $o .= '         &nbsp;<button class="icon_pop"  onclick="browse(\''.base_url().'processor/reformulasi/browse/export/studi/literatur/ad/?field=export_studi_literatur_ad\',\'Request Reformulasi\')" type="button">Browse</button>';
                $o  .="             </td>
                                </tr>

                                <tr>
                                    <td width='20%'>Nama Produk</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_cIteno' id='".$uri."_cIteno'></span>
                                    </td>
                                </tr>


                                <tr>
                                    <td width='20%'>Nama Inisiator</td>
                                    <td>:</td>
                                    <td width='75%'>

                                        <span class='".$uri."_cInisiator' id='".$uri."_cInisiator'></span>
                                    </td>
                                </tr>

                                <tr>
                                    <td width='20%'>Dapartement</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_cdapart' id='".$uri."_cdapart'></span>
                                    </td>
                                </tr>

                                <tr>
                                    <td width='20%'>Alasan Refor</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_vAlasan_refor' id='".$uri."_vAlasan_refor'></span>
                                    </td>
                                </tr>



                                <tr>
                                    <td width='20%'>Tgl Permintaan Refor</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_dRequest' id='".$uri."_dRequest'></span>
                                    </td>
                                </tr>

                                <tr>
                                    <td width='20%'>Approval Atasan Inisiator</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_iStatus' id='".$id."_iStatus'></span>
                                    </td>
                                </tr>

                                <tr>
                                    <td width='20%'>PIC Formulator Refor</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_cFormulator' id='".$uri."_cFormulator'></span>
                                    </td>
                                </tr>

                            </tbody>
                        </table>";
                $o .= "    </div>";

                $o .= '<script>
                        $( "button.icon_pop" ).button({
                            icons: {
                                primary: "ui-icon-newwin"
                            },
                        })
                    </script>';


                return $o;
            }
            function updateBox_export_studi_literatur_ad_iexport_req_refor($field, $id, $value, $rowData) {
                $sql = "SELECT * FROM reformulasi.`export_req_refor` lr WHERE lr.`lDeleted` = 0 AND lr.`iexport_req_refor` = '".$value."'";
                $dt = $this->db->query($sql)->row_array();
                $_cIteno = '';
                $_vno_export_req_refor='';
                $_vBatch_no='';
                $_vAlasan_refor='';
                $_dRequest='';
                $_cIteno='';
                $_cInisiator='';
                $_cdapart='';
                $_iTeamPD='';
                $_iStatus='';
                $_cFormulator='';
                $_iupload_f = '';
                if(!empty($dt['iexport_req_refor'])){

                        $_vno_export_req_refor = $dt['vno_export_req_refor'];
                        $_vAlasan_refor = str_replace("'", "",str_replace('""', '', $dt['tAlasan_export']));
                        $_dRequest = $dt['dPermintaan_req_export'];

                        $itname = "SELECT i.`c_itnam`,i.c_iteno FROM sales.`itemas` i
                            JOIN `dossier`.`dossier_upd` d ON d.`iupb_id` = i.`c_iteno`
                            WHERE  d.`idossier_upd_id` =  '".$dt['idossier_upd_id']."'";
                        $c_itnam = $this->db->Query($itname)->row_array();
                        if(empty($c_itnam['c_itnam'])){
                            $c_itnam['c_itnam'] = '-';
                        }
                        $_cIteno = $c_itnam['c_iteno'].' - '.$c_itnam['c_itnam'];


                        $vn = "SELECT e.`vName` FROM hrd.`employee` e WHERE e.`cNip` = '".$dt['cInisiator_export']."'";
                                $vName = $this->db->query($vn)->row_array();
                        if(empty($vName['vName'])){
                            $vName['vName'] = '-';
                        }
                        $_cInisiator = $vName['vName'];


                        $dp = "SELECT m.`vDescription` FROM  hrd.`msdepartement` m
                                WHERE m.`iDeptID` = '".$dt['iDapartemen_export']."'";
                        $cdapart = $this->db->query($dp)->row_array();
                        if(empty($cdapart['vDescription'])){
                            $cdapart['vDescription'] = '-';
                        }
                        $_cdapart = $cdapart['vDescription'];



                        $ap = "SELECT e.`vName` FROM hrd.`employee` e WHERE e.`cNip` = '".$dt['cApproval_ats_inisiator']."'";
                        $app = $this->db->query($ap)->row_array();
                        if($dt['iApproval_ats_inisiator']==2){
                            if(empty($app['vName'])){
                                $app['vName'] = 'Approved'.' Tgl '.$dt['dApproval_ats_inisiator'];
                            }else{
                                $app['vName'] = 'Approved by '.$app['vName'].' Tgl '.$dt['dApproval_ats_inisiator'];
                            }
                        }else if($dt['iApproval_ats_inisiator']==1){
                            if(empty($app['vName'])){
                                $app['vName'] = 'Rejected'.' Tgl '.$dt['dApproval_ats_inisiator'];
                            }else{
                                $app['vName'] = 'Rejected by '.$app['vName'].' Tgl '.$dt['dApproval_ats_inisiator'];
                            }
                        }else{
                            $app['vName'] = 'Waiting Approval';
                        }

                        $_iStatus = $app['vName'];


                        $for = "SELECT e.`vName` FROM hrd.`employee` e WHERE e.`cNip` = '".$dt['cPicFormulator']."'";
                        $formu = $this->db->query($for)->row_array();
                        if(empty($formu['vName'])){
                            $formu['vName'] = '-';
                        }
                        $_cFormulator = $formu['vName'];
                }

                $uri = 'export_studi_literatur_ad';
                $o = "";
                $o   .= "<div style='
                                padding: 3px;
                                width: 500px;
                                border: 1px solid rgba(51, 23, 93, 0.2);
                                background-color: #FFF;'>";


                $o   .= "<table border='0' style='width: 100%;'>
                            <tbody>";
                $o  .="         <tr>
                                    <td width='20%'>No Request</td>
                                    <td>:</td>
                                    <td width='75%'>";
                $o .= '         <input type="hidden" name="'.$field.'"  id="'.$id.'"  class="'.$id.' input_rows1 required" size="30" value="'.$value.'"/>';
                $o .= '         <input readonly type="text" name="'.$uri.'_vno_export_req_refor"  id="'.$uri.'_vno_export_req_refor"  class="'.$uri.'_vno_export_req_refor required input_rows1" size="30" value="'.$_vno_export_req_refor.'"/>';
                if($rowData['isubmitAd']==0){
                    $o .= '         &nbsp;<button class="icon_pop"  onclick="browse(\''.base_url().'processor/reformulasi/browse/export/studi/literatur/ad/?field=export_studi_literatur_ad\',\'Request Reformulasi\')" type="button">Browse</button>';
                }
                $o  .="             </td>
                                </tr>

                                <tr>
                                    <td width='20%'>Nama Produk</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_cIteno' id='".$uri."_cIteno'>".$_cIteno."</span>
                                    </td>
                                </tr>



                                <tr>
                                    <td width='20%'>Nama Inisiator</td>
                                    <td>:</td>
                                    <td width='75%'>

                                        <span class='".$uri."_cInisiator' id='".$uri."_cInisiator'>".$_cInisiator."</span>
                                    </td>
                                </tr>

                                <tr>
                                    <td width='20%'>Dapartement</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_cdapart' id='".$uri."_cdapart'>".$_cdapart."</span>
                                    </td>
                                </tr>

                                <tr>
                                    <td width='20%'>Alasan Refor</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_vAlasan_refor' id='".$uri."_vAlasan_refor'>".$_vAlasan_refor."</span>
                                    </td>
                                </tr>

                                <tr>
                                    <td width='20%'>Tgl Permintaan Refor</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_dRequest' id='".$uri."_dRequest'>".$_dRequest."</span>
                                    </td>
                                </tr>

                                <tr>
                                    <td width='20%'>Approval Atasan Inisiator</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_iStatus' id='".$id."_iStatus'>".$_iStatus."</span>
                                    </td>
                                </tr>

                                <tr>
                                    <td width='20%'>PIC Formulator Refor</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_cFormulator' id='".$uri."_cFormulator'>".$_cFormulator."</span>
                                    </td>
                                </tr>

                            </tbody>
                        </table>";
                $o .= "    </div>";

                $o .= '<script>
                        $( "button.icon_pop" ).button({
                            icons: {
                                primary: "ui-icon-newwin"
                            },
                        })
                    </script>';


                return $o;
            }

            function insertBox_export_studi_literatur_ad_dCreate($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"});
                             </script>';
                return $return;
            }
            function updateBox_export_studi_literatur_ad_dCreate($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").datepicker({
                                    changeMonth:true,
                                    changeYear:true,
                                    dateFormat:"yy-mm-dd"
                                });
                             </script>';
                }
                return $return;
            }

            function insertBox_export_studi_literatur_ad_cCreated($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_export_studi_literatur_ad_cCreated($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 50) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                }
                return $return;
            }

            function insertBox_export_studi_literatur_ad_dupdate($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"});
                             </script>';
                return $return;
            }
            function updateBox_export_studi_literatur_ad_dupdate($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").datepicker({
                                    changeMonth:true,
                                    changeYear:true,
                                    dateFormat:"yy-mm-dd"
                                });
                             </script>';
                }
                return $return;
            }

            function insertBox_export_studi_literatur_ad_ifileliteratur($field, $id) {
                $data['rows']=array();
                $return = $this->load->view('export/export_studi_literatur_ad_file',$data,TRUE);
                $return .= '<input type="hidden" name="isdraft" id="isdraft" class="isdraft">';
                $return .= '<input type="hidden" name="iexport_refor_studi_literatur_ad" id="iexport_refor_studi_literatur_ad" class="iexport_refor_studi_literatur_ad">';

                return $return;
            }
            function updateBox_export_studi_literatur_ad_ifileliteratur($field, $id, $value, $rowData) {
                $sq = "SELECT * FROM reformulasi.`export_refor_studi_literatur_ad_file` ed WHERE ed.`ijenisFolde` = 0
                    AND ed.`lDeleted` = 0 AND ed.`iexport_refor_studi_literatur_ad` ='".$rowData['iexport_refor_studi_literatur_ad']."'";
                $data['rows']=$this->db->query($sq)->result_array();
                $data['isubmitAd']=$rowData['isubmitAd'];
                $return = $this->load->view('export/export_studi_literatur_ad_file',$data,TRUE);
                $return .= '<input type="hidden" name="isdraft" id="isdraft" class="isdraft">';
                 $return .= '<input type="hidden" name="iexport_refor_studi_literatur_ad" id="iexport_refor_studi_literatur_ad" class="iexport_refor_studi_literatur_ad" value="'.$rowData['iexport_refor_studi_literatur_ad'].'">';

                return $return;
            }

            function insertBox_export_studi_literatur_ad_ifileliterturother($field, $id) {
                $data['rows']=array();
                $return = $this->load->view('export/export_studi_literatur_ad_other_file',$data,TRUE);
                return $return;
            }
            function updateBox_export_studi_literatur_ad_ifileliterturother($field, $id, $value, $rowData) {
                $sq = "SELECT * FROM reformulasi.`export_refor_studi_literatur_ad_file` ed WHERE ed.`ijenisFolde` = 1
                    AND ed.`lDeleted` = 0 AND ed.`iexport_refor_studi_literatur_ad` ='".$rowData['iexport_refor_studi_literatur_ad']."'";
                $data['rows']=$this->db->query($sq)->result_array();
                $data['isubmitAd']=$rowData['isubmitAd'];
                $return = $this->load->view('export/export_studi_literatur_ad_other_file',$data,TRUE);
                return $return;
            }

            function insertBox_export_studi_literatur_ad_cUpdate($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_export_studi_literatur_ad_cUpdate($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 50) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                }
                return $return;
            }

            function insertBox_export_studi_literatur_ad_dmulaistudiAD($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"});
                             </script>';
                return $return;
            }
            function updateBox_export_studi_literatur_ad_dmulaistudiAD($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").datepicker({
                                    changeMonth:true,
                                    changeYear:true,
                                    dateFormat:"yy-mm-dd"
                                });
                             </script>';
                }
                return $return;
            }

            function insertBox_export_studi_literatur_ad_dselesaistudiAD($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"});
                             </script>';
                return $return;
            }
            function updateBox_export_studi_literatur_ad_dselesaistudiAD($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").datepicker({
                                    changeMonth:true,
                                    changeYear:true,
                                    dateFormat:"yy-mm-dd"
                                });
                             </script>';
                }
                return $return;
            }

            function insertBox_export_studi_literatur_ad_cPicstudiAD($field, $id) {
                // $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "10" />';
                // $return .= '<script>
                //                 $("#'.$id.'").keyup(function() {
                //                     var len = this.value.length;
                //                         if (len >= 250) {
                //                             this.value = this.value.substring(0, 10);
                //                         }
                //                     $("#maxlengthnote_'.$id.'").text(10 - len);
                //                 });
                //              </script>';
                // $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">10</span> karakter<br/>';
                // return $return;

                $url6 = base_url().'processor/reformulasi/export/studi/literatur/ad?action=searchcNip';
                $o = "<script type='text/javascript'>
                                $(document).ready(function() {
                                    $('#".$id."_').live('keyup', function(e) {
                                        var config = {
                                            source: '".$url6."',
                                            select: function(event, ui){
                                                $('#".$id."').val(ui.item.id);
                                                $('#".$id."_').val(ui.item.value);
                                                return false;
                                            },
                                            minLength: 2,
                                            autoFocus: true,
                                            };
                                        $('#".$id."_').autocomplete(config);
                                        $(this).keypress(function(e){
                                            if(e.which != 13) {
                                                $('#".$id."').val('');
                                            }
                                        });
                                        $(this).blur(function(){
                                            if($('#".$id."').val() == '') {
                                                $(this).val('');
                                            }
                                        });

                                    });

                                });
                          </script>";
                    $o   .= '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value=""/>';
                    $o   .= '<input type="text" name="'.$field.'_"  id="'.$id.'_"  class="input_rows1 required" size="30" maxlength = "50"  value=""/>';
                    return $o;
            }
            function updateBox_export_studi_literatur_ad_cPicstudiAD($field, $id, $value, $rowData) {
                $vn = "SELECT e.`vName` FROM hrd.`employee` e WHERE e.`cNip` = '".$value."'";
                $vName = $this->db->query($vn)->row_array();
                if(empty($vName['vName'])){
                    $vName['vName'] = '-';
                }
                if ($this->input->get('action') == 'view') {
                     $o= $value.' - '.$vName['vName'];
                }else{
                    $url6 = base_url().'processor/reformulasi/export/studi/literatur/ad?action=searchcNip';
                    $o = "<script type='text/javascript'>
                                    $(document).ready(function() {
                                        $('#".$id."_').live('keyup', function(e) {
                                            var config = {
                                                source: '".$url6."',
                                                select: function(event, ui){
                                                    $('#".$id."').val(ui.item.id);
                                                    $('#".$id."_').val(ui.item.value);
                                                    return false;
                                                },
                                                minLength: 2,
                                                autoFocus: true,
                                                };
                                            $('#".$id."_').autocomplete(config);
                                            $(this).keypress(function(e){
                                                if(e.which != 13) {
                                                    $('#".$id."').val('');
                                                }
                                            });
                                            $(this).blur(function(){
                                                if($('#".$id."').val() == '') {
                                                    $(this).val('');
                                                }
                                            });

                                        });

                                    });
                              </script>";
                    $o   .= '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                    $o   .= '<input type="text" name="'.$field.'_"  id="'.$id.'_"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.' - '.$vName['vName'].'"/>';
                }


                return $o;
            }

            function insertBox_export_studi_literatur_ad_iUjiMikrofg($field, $id) {
                $dt = array('0'=>'No','1'=>'Yes');
                $o = '<select class="input_rows1 required" name="'.$field.'" id="'.$id.'">';
                foreach ($dt as $t => $v) {
                    $o .= '<option value="'.$t.'">'.$v.'</option>';
                }
                $o .= '</select> <style>
                         #'.$id.'{
                             width:180px;
                        }
                      </style>';
                return $o;
            }
            function updateBox_export_studi_literatur_ad_iUjiMikrofg($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                    $dt = array(''=>'No','0'=>'No','1'=>'Yes');
                    $o = $dt[$value];
                } else {
                    $dt = array('0'=>'No','1'=>'Yes');
                    $o  = "<select name='".$field."' id='".$id."' class='required'>";
                    foreach ($dt as $t => $v) {
                           if ($value == $t) $selected = " selected";
                           else $selected = '';
                           $o .= "<option {$selected} value='".$t."'>".$v."</option>";
                        }
                    }
                $o .= '</select> <style>
                         #'.$id.'{
                             width:180px;
                        }
                      </style>';
                return $o;
            }

            function insertBox_export_studi_literatur_ad_cappAd($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "10" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 10);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(10 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">10</span> karakter<br/>';
                return $return;
            }
            function updateBox_export_studi_literatur_ad_cappAd($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "10"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 10) {
                                            this.value = this.value.substring(0, 10);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(10 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">10</span> karakter<br/>';

                }
                return $return;
            }

            function insertBox_export_studi_literatur_ad_dappAd($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"});
                             </script>';
                return $return;
            }
            function updateBox_export_studi_literatur_ad_dappAd($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").datepicker({
                                    changeMonth:true,
                                    changeYear:true,
                                    dateFormat:"yy-mm-dd"
                                });
                             </script>';
                }
                return $return;
            }

            function insertBox_export_studi_literatur_ad_tappAd($field, $id) {
                $return = '<textarea name="'.$field.'" id="'.$id.'" class="required" style="width: 240px; height: 50px;" size="250" maxlength ="250"></textarea>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 255);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(255 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">250</span> karakter<br/>';
                return $return;
            }
            function updateBox_export_studi_literatur_ad_tappAd($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= '<label title="Note">'.nl2br($value).'</label>';
                }else{
                    $return = '<textarea name="'.$field.'" id="'.$id.'" class="required" style="width: 240px; height: 50px;" size="250" maxlength ="250">'.nl2br($value).'</textarea>';
                }
                return $return;
            }

            function insertBox_export_studi_literatur_ad_iappAd($field, $id) {
                $return ='';
                $return .= '
                            <script type="text/javascript">
                                $("label[for=\''.$id.'\']").hide();
                                $("label[for=\''.$id.'\']").next().css("margin-left",0);
                            </script>
                        ';
                $return .= '<div></div>';
                return $return;
            }
            function updateBox_export_studi_literatur_ad_iappAd($field, $id, $value, $rowData) {

                if(($value <> 0) || (!empty($value))){
                    $sql_dtapp = "SELECT * FROM reformulasi.`export_refor_studi_literatur_ad` a
                        JOIN hrd.employee b on b.cNip=a.cappAd
                        WHERE a.`lDeleted` = 0 AND a.iexport_refor_studi_literatur_ad = '".$rowData['iexport_refor_studi_literatur_ad']."'";
                    $row = $this->db->query($sql_dtapp)->row_array();

                    if($value==2){
                        $st='<p style="">Approved';
                        $ret= $st.' oleh '.$row['vName'].' pada '.$row['dappAd'].'</br> Alasan: '.$row['tappAd'].'</p>';
                    }
                    elseif($value==1){
                        $st='<p style="color:red;">Rejected';
                        $ret= $st.' oleh '.$row['vName'].' pada '.$row['dappAd'].'</br> Alasan: '.$row['tappAd'].'</p>';
                    }
                }
                else{
                    $ret='Waiting for Approval';
                }
                $ret .= "<input type='hidden' name='".$field."' id='".$id."'  value='".$value."'/>";
                return '<i>'.$ret.'</i>';
            }

            function insertBox_export_studi_literatur_ad_isubmitAd($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_export_studi_literatur_ad_isubmitAd($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                }
                return $return;
            }

            function insertBox_export_studi_literatur_ad_lDeleted($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_export_studi_literatur_ad_lDeleted($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                }
                return $return;
            }


                //Ini Merupakan Standart Approve yang digunakan di erp

                function approve_view() {
                    $echo = '<script type="text/javascript">
                                 function submit_ajax(form_id) {
                                    return $.ajax({
                                        url: $("#"+form_id).attr("action"),
                                        type: $("#"+form_id).attr("method"),
                                        data: $("#"+form_id).serialize(),
                                        success: function(data) {
                                            var o = $.parseJSON(data);
                                            var last_id = o.last_id;
                                            var url = "'.base_url().'processor/reformulasi/export_studi_literatur_ad";
                                            if(o.status == true) {
                                                $("#alert_dialog_form").dialog("close");
                                                     $.get(url+"?action=update&id="+last_id, function(data) {
                                                     $("div#form_export_studi_literatur_ad").html(data);

                                                });

                                            }
                                                reload_grid("grid_export_studi_literatur_ad");
                                        }

                                     })
                                 }
                             </script>';
                    $echo .= '<h1>Approve</h1><br />';
                    $echo .= '<form id="form_export_studi_literatur_ad_approve" action="'.base_url().'processor/reformulasi/export_studi_literatur_ad?action=approve_process" method="post">';
                    $echo .= '<div style="vertical-align: top;">';
                    $echo .= 'Remark :
                            <input type="hidden" name="iexport_refor_studi_literatur_ad" value="'.$this->input->get('iexport_refor_studi_literatur_ad').'" />
                            <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                            <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                            <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                            <textarea name="vRemark"></textarea>
                      <button type="button" onclick="submit_ajax(\'form_export_studi_literatur_ad_approve\')">Confirm</button>';

                    $echo .= '</div>';
                    $echo .= '</form>';
                    return $echo;
                }

                function approve_process() {
                    $post = $this->input->post();
                    $cNip= $this->user->gNIP;
                    $vName= $this->user->gName;
                    $iexport_refor_studi_literatur_ad = $post['iexport_refor_studi_literatur_ad'];
                    $vRemark = $post['vRemark'];
                    $lvl = $post['lvl'];

                    $this->db->where('iexport_refor_studi_literatur_ad', $post['iexport_refor_studi_literatur_ad']);
                    $this->db->update('reformulasi.export_refor_studi_literatur_ad', array('iappAd'=>2,'cappAd'=>$cNip,'dappAd'=>date('Y-m-d H:i:s'),'tappAd'=>$vRemark));

                    $data['status']  = true;
                    $data['last_id'] = $post['iexport_refor_studi_literatur_ad'];
                    return json_encode($data);
                }




                //Ini Merupakan Standart Reject yang digunakan di erp

                function reject_view() {
                    $echo = '<script type="text/javascript">
                                 function submit_ajax(form_id) {
                                    var remark = $("#export_studi_literatur_ad_remark").val();
                                    if (remark=="") {
                                        alert("Remark tidak boleh kosong ");
                                        return
                                    }

                                    return $.ajax({
                                        url: $("#"+form_id).attr("action"),
                                        type: $("#"+form_id).attr("method"),
                                        data: $("#"+form_id).serialize(),
                                        success: function(data) {
                                            var o = $.parseJSON(data);
                                            var last_id = o.last_id;
                                            var url = "'.base_url().'processor/reformulasi/export_studi_literatur_ad";
                                            if(o.status == true) {
                                                $("#alert_dialog_form").dialog("close");
                                                     $.get(url+"?action=update&id="+last_id, function(data) {
                                                     $("div#form_export_studi_literatur_ad").html(data);

                                                });

                                            }
                                                reload_grid("grid_export_studi_literatur_ad");
                                        }

                                     })
                                 }
                             </script>';
                    $echo .= '<h1>Reject</h1><br />';
                    $echo .= '<form id="form_export_studi_literatur_ad_reject" action="'.base_url().'processor/reformulasi/export_studi_literatur_ad?action=reject_process" method="post">';
                    $echo .= '<div style="vertical-align: top;">';
                    $echo .= 'Remark :
                            <input type="hidden" name="iexport_refor_studi_literatur_ad" value="'.$this->input->get('iexport_refor_studi_literatur_ad').'" />
                            <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                            <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                            <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                            <textarea name="vRemark" id="reject_export_studi_literatur_ad_remark"></textarea>
                    <button type="button" onclick="submit_ajax(\'form_export_studi_literatur_ad_reject\')">Reject</button>';

                    $echo .= '</div>';
                    $echo .= '</form>';
                    return $echo;
                }



                function reject_process() {
                    $post = $this->input->post();
                    $cNip= $this->user->gNIP;
                    $vName= $this->user->gName;
                    $iexport_refor_studi_literatur_ad = $post['iexport_refor_studi_literatur_ad'];
                    $vRemark = $post['vRemark'];
                    $lvl = $post['lvl'];

                    $this->db->where('iexport_refor_studi_literatur_ad', $post['iexport_refor_studi_literatur_ad']);
                    $this->db->update('reformulasi.export_refor_studi_literatur_ad', array('iappAd'=>1,'cappAd'=>$cNip,'dappAd'=>date('Y-m-d H:i:s'),'tappAd'=>$vRemark));

                    //Letakan Query Update approve disini

                    $data['status']  = true;
                    $data['last_id'] = $post['iexport_refor_studi_literatur_ad'];
                    return json_encode($data);
                }



            //Standart Setiap table harus memiliki dCreate , cCreated, dupdate, cUpdate
            function before_insert_processor($row, $postData) {
                $postData['dCreate'] = date('Y-m-d H:i:s');
                $postData['cCreated']=$this->user->gNIP;

                if($postData['isdraft']==true){
                    $postData['isubmitAd']=0;
                }
                else{
                    $postData['isubmitAd']=1;
                }

                return $postData;


            }
            function before_update_processor($row, $postData) {
                $postData['dupdate'] = date('Y-m-d H:i:s');
                $postData['cUpdate'] = $this->user->gNIP;

                if($postData['isdraft']==true){
                    $postData['isubmitAd']=0;
                }
                else{
                    $postData['isubmitAd']=1;
                }

                return $postData;
            }

            function after_insert_processor($fields, $id, $postData) {
                //Example After Insert
                /*
                $cNip = $this->sess_auth->gNIP;
                $sql = 'Place Query In Here';
                $this->dbset->query($sql);
                */

                if($postData['isubmitAd']==1){
                        $sql = "SELECT em.`vName`, sa.`dmulaistudiAD`, sa.`dselesaistudiAD`, sa.`iTeamAd`,
                            e.`vno_export_req_refor` FROM reformulasi.`export_refor_studi_literatur_ad` sa
                            JOIN reformulasi.`export_req_refor` e ON sa.`iexport_req_refor` = e.`iexport_req_refor`
                            JOIN hrd.`employee` em ON em.`cNip` = sa.`cPicstudiAD`
                            WHERE sa.`lDeleted` = 0 AND sa.`iexport_refor_studi_literatur_ad` =  ".$id;
                        $mailDet = $this->db->query($sql)->row_array();

                        $sqlM = "SELECT r.`vnip` FROM `reformulasi`.`reformulasi_team` r
                                JOIN `reformulasi`.`export_req_refor` e ON e.`iTeamAndev` = r.`ireformulasi_team`
                                WHERE e.`iexport_req_refor` =  '".$postData['iexport_req_refor']."' LIMIT 1";
                        $tomail = $this->db->query($sqlM)->row_array();
                        $to = $tomail['vnip'];

                        $cc = $this->user->gNIP;
                        $subject="Submited Study Literatur AD ";
                        $content="
                        Diberitahukan bahwa telah ada Submited Modul Study Literatur AD,
                            dengan rincian sebagai berikut :<br><br>
                            <table border='0' style='width: 600px;'>
                                <tr>
                                        <td style='width: 110px;'><b>No Request Reformulasi </b></td><td style='width: 20px;'> : </td>
                                        <td>".$mailDet['vno_export_req_refor']."</td>
                                </tr>
                                <tr>
                                        <td><b>PIC Studi Literatur  </b></td><td> : </td>
                                        <td>".$mailDet['vName']."</td>
                                </tr>
                                <tr>
                                        <td><b>Tanggal Mulai Studi Literatur  </b></td><td> : </td>
                                        <td>".$mailDet['dmulaistudiAD']."</td>
                                </tr>
                                <tr>
                                        <td><b>Tanggal Mulai Studi Literatur  </b></td><td> : </td>
                                        <td>".$mailDet['dselesaistudiAD']."</td>
                                </tr>
                            </table>
                        <br/> <br/>
                        Demikian, mohon segera follow up  pada aplikasi ERP Reformulasi. Terimakasih.<br><br><br>
                        Post Master";
                        $this->sess_auth->send_message_erp($this->uri->segment_array(),$to, $cc, $subject, $content);
                }

            }

            function after_update_processor($fields, $id, $postData) {
                if($postData['isubmitAd']==1){
                        $sql = "SELECT em.`vName`, sa.`dmulaistudiAD`, sa.`dselesaistudiAD`, sa.`iTeamAd`,
                            e.`vno_export_req_refor` FROM reformulasi.`export_refor_studi_literatur_ad` sa
                            JOIN reformulasi.`export_req_refor` e ON sa.`iexport_req_refor` = e.`iexport_req_refor`
                            JOIN hrd.`employee` em ON em.`cNip` = sa.`cPicstudiAD`
                            WHERE sa.`lDeleted` = 0 AND sa.`iexport_refor_studi_literatur_ad` =  ".$id;
                        $mailDet = $this->db->query($sql)->row_array();


                        $sqlM = "SELECT r.`vnip` FROM `reformulasi`.`reformulasi_team` r
                                JOIN `reformulasi`.`export_req_refor` e ON e.`iTeamAndev` = r.`ireformulasi_team`
                                WHERE e.`iexport_req_refor` =  '".$postData['iexport_req_refor']."' LIMIT 1";
                        $tomail = $this->db->query($sqlM)->row_array();
                        $to = $tomail['vnip'];

                        $cc = $this->user->gNIP;
                        $subject="Submited Study Literatur AD ";
                        $content="
                        Diberitahukan bahwa telah ada Submited Modul Study Literatur AD,
                            dengan rincian sebagai berikut :<br><br>
                            <table border='0' style='width: 600px;'>
                                <tr>
                                        <td style='width: 110px;'><b>No Request Reformulasi </b></td><td style='width: 20px;'> : </td>
                                        <td>".$mailDet['vno_export_req_refor']."</td>
                                </tr>
                                <tr>
                                        <td><b>PIC Studi Literatur  </b></td><td> : </td>
                                        <td>".$mailDet['vName']."</td>
                                </tr>
                                <tr>
                                        <td><b>Tanggal Mulai Studi Literatur  </b></td><td> : </td>
                                        <td>".$mailDet['dmulaistudiAD']."</td>
                                </tr>
                                <tr>
                                        <td><b>Tanggal Mulai Studi Literatur  </b></td><td> : </td>
                                        <td>".$mailDet['dselesaistudiAD']."</td>
                                </tr>
                            </table>
                        <br/> <br/>
                        Demikian, mohon segera follow up  pada aplikasi ERP Reformulasi. Terimakasih.<br><br><br>
                        Post Master";
                        $this->sess_auth->send_message_erp($this->uri->segment_array(),$to, $cc, $subject, $content);
                }

            }



            function manipulate_insert_button($buttons) {
                unset($buttons['save']);
                $js = $this->load->view('export/js/export_studi_literatur_ad_js');

                $save_draft = '<button onclick="javascript:save_draft_btn_multiupload(\'export_studi_literatur_ad\', \''.base_url().'processor/reformulasi/export/studi/literatur/ad?draft=true\', this, true)" class="ui-button-text icon-save" id="button_save_draft_export_studi_literatur_ad_js">Save as Draft</button>';
                $save = '<button onclick="javascript:save_btn_multiupload(\'export_studi_literatur_ad\', \''.base_url().'processor/reformulasi/export/studi/literatur/ad?company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\', this)" class="ui-button-text icon-save" id="button_save_export_studi_literatur_ad_js">Save &amp Submit</button>';

                $buttons['save'] = $save_draft.$save.$js;

                return $buttons;
            }
            function manipulate_update_button($buttons, $rowData) {
                if ($this->input->get('action') == 'view') {
                    unset($buttons['update_back']);
                    unset($buttons['update']);
                }
                else{
                    $cNip= $this->user->gNIP;

                    $js = $this->load->view('export/js/export_studi_literatur_ad_js');
                    $update = '<button onclick="javascript:update_btn_back(\'export_studi_literatur_ad\', \''.base_url().'processor/reformulasi/export/studi/literatur/ad?company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\', this)" class="ui-button-text icon-save" id="button_update_export_studi_literatur_ad">Update & Submit</button>';
                    $updatedraft = '<button onclick="javascript:update_draft_btn(\'export_studi_literatur_ad\', \''.base_url().'processor/reformulasi/export/studi/literatur/ad?company_id='.$this->input->get('company_id').'&draft=true&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\', this, true)" class="ui-button-text icon-save" id="button_save_export_studi_literatur_ad">Update as Draft</button>';

                    //$approve = '<button onclick="javascript:load_popup(\''.base_url().'processor/reformulasi/export/studi/literatur/ad?action=approve&iexport_refor_studi_literatur_ad='.$rowData['iexport_refor_studi_literatur_ad'].'&cNip='.$cNip.'&lvl=1&status=1&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\')" class="ui-button-text icon-save" id="button_approve_export_studi_literatur_ad">Approve</button>';
                    $approve = '<button onclick="javascript:load_popup(\''.base_url().'processor/reformulasi/export/studi/literatur/ad?action=approve&iexport_refor_studi_literatur_ad='.$rowData['iexport_refor_studi_literatur_ad'].'&cNip='.$cNip.'&lvl=1&status=1&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\')" class="ui-button-text icon-save" id="button_approve_export_studi_literatur_ad">Confirm</button>';
                    $reject = '<button onclick="javascript:load_popup(\''.base_url().'processor/reformulasi/export/studi/literatur/ad?action=reject&iexport_refor_studi_literatur_ad='.$rowData['iexport_refor_studi_literatur_ad'].'&cNip='.$cNip.'&lvl=1&status=2&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\')" class="ui-button-text icon-save" id="button_reject_export_studi_literatur_ad">Reject</button>';


                    if($rowData['isubmitAd']==0){
                        // $x=$this->auth_export->dept();
                        // $team=$x['team'];
                        // if(in_array('AD', $team)){
                            $buttons['update'] = $updatedraft.$update.$js;
                        // }else{
                        //     unset($buttons['update_back']);
                        //     unset($buttons['update']);
                        // }

                    }else{
                        if($rowData['iappAd']==0 or empty($rowData['iappAd'])){

                             $sqlM = "SELECT r.`vnip` FROM `reformulasi`.`reformulasi_team` r
                                JOIN `reformulasi`.`export_req_refor` e ON e.`iTeamAndev` = r.`ireformulasi_team`
                                WHERE e.`iexport_req_refor` =  '".$rowData['iexport_req_refor']."' LIMIT 1";
                                $tomail = $this->db->query($sqlM)->row_array();
                                if($tomail['vnip']==$cNip){
                                    //$buttons['update'] = $approve.$reject.$js;
                                    $buttons['update'] = $approve.$js;
                                }else{
                                    unset($buttons['update_back']);
                                    unset($buttons['update']);
                                }

                            // if($this->auth_export->is_manager()){
                            //     $x=$this->auth_export->dept();
                            //     $manager=$x['manager'];
                            //     if(in_array('AD', $manager)){
                            //         $buttons['update'] = $approve.$reject.$js;
                            //     }else{
                            //         unset($buttons['update_back']);
                            //         unset($buttons['update']);
                            //     }

                            // }else{
                            //     unset($buttons['update_back']);
                            //     unset($buttons['update']);
                            // }
                        }else{
                            unset($buttons['update_back']);
                            unset($buttons['update']);
                        }


                    }

                }

                return $buttons;
            }

            function download1($vFilename) {
                $this->load->helper('download');
                $name = $vFilename;
                $id = $_GET['id'];
                $path = file_get_contents('./files/reformulasi/export/export_studi_literatur_ad/'.$id.'/'.$name);
                force_download($name, $path);
            }
            function download2($vFilename) {
                $this->load->helper('download');
                $name = $vFilename;
                $id = $_GET['id'];
                $path = file_get_contents('./files/reformulasi/export/export_studi_literatur_ad_other/'.$id.'/'.$name);
                force_download($name, $path);
            }
            //Output
            public function output(){
                $this->index($this->input->get('action'));
            }
        }
