
        <?php
        /* Generated by Sovdev 2 ERP CRUD Generator 2018-02-15 08:49:12 */
        /* Location: ./modules/reformulasi/controllers/export_req_refor.php */
        /* Please DO NOT modify this information : */

        if ( ! defined('BASEPATH')) exit('No direct script access allowed');
        class export_konfirm_req_refor extends MX_Controller {
            function __construct() {
                parent::__construct();
                $this->load->library('auth');
                $this->load->library('auth_export');
                $this->db = $this->load->database('formulasi', false, true);
                $this->user = $this->auth->user();
            }
            function index($action = '') {
                $action = $this->input->get('action');
                //Bikin Object Baru Nama nya $grid
                $grid = new Grid;
                $grid->setTitle('Konfirm Reformulasi Export');
                $grid->setTable('reformulasi.export_req_refor');
                $grid->setUrl('export_konfirm_req_refor');

                //List Table
                $grid->addList('vno_export_req_refor','dossier_upd.vUpd_no','itemas.c_iteno','dossier_upd.vNama_usulan','employee.vName','iSubmitPD');
                $grid->setSortBy('iexport_req_refor');
                $grid->setSortOrder('desc');

                //List field
                $grid->addFields('vno_export_req_refor','idossier_upd_id','cInisiator_export','insBB','vUploadfile','dPermintaan_bb_export','tAlasan_export','dPermintaan_req_export','iTeamPD','iTeamAndev','iUjibe','cPicFormulator');

                //Setting Grid Width Name
                /*
                    Kamu bisa merubah nama label dari sini, Contoh :
                    $grid->setLabel('nama field','nama field yang akan diubah');

                */

                $grid->setWidth('itemas.c_iteno', '80');
                $grid->setAlign('itemas.c_iteno', 'left');
                $grid->setLabel('itemas.c_iteno','Kode Product');

                $grid->setWidth('cPicFormulator','80');
                $grid->setAlign('cPicFormulator','left');
                $grid->setLabel('cPicFormulator','Pic Formulator');

                $grid->setWidth('iUjibe', '80');
                $grid->setAlign('iUjibe', 'left');
                $grid->setLabel('iUjibe','Perlu Uji BE ?');

                $grid->setWidth('insBB', '80');
                $grid->setAlign('insBB', 'left');
                $grid->setLabel('insBB','Permintaan Bahan Baku');

                $grid->setWidth('dossier_upd.vNama_usulan', '250');
                $grid->setAlign('dossier_upd.vNama_usulan', 'left');
                $grid->setLabel('dossier_upd.vNama_usulan','Nama Usulan Product');

                $grid->setWidth('vno_export_req_refor', '100');
                $grid->setAlign('vno_export_req_refor', 'left');
                $grid->setLabel('vno_export_req_refor','No Request');

                $grid->setWidth('idossier_upd_id', '100');
                $grid->setAlign('idossier_upd_id', 'left');
                $grid->setLabel('idossier_upd_id','Nomor UPD');

                $grid->setWidth('dossier_upd.vUpd_no', '80');
                $grid->setAlign('dossier_upd.vUpd_no', 'left');
                $grid->setLabel('dossier_upd.vUpd_no','Nomor UPD');

                $grid->setWidth('cInisiator_export', '100');
                $grid->setAlign('cInisiator_export', 'left');
                $grid->setLabel('cInisiator_export','Nama Inisiator');

                $grid->setWidth('employee.vName', '250');
                $grid->setAlign('employee.vName', 'left');
                $grid->setLabel('employee.vName','Nama Inisiator');



                $grid->setWidth('iDapartemen_export', '100');
                $grid->setAlign('iDapartemen_export', 'left');
                $grid->setLabel('iDapartemen_export','Dapartemen');

                $grid->setWidth('tAlasan_export', '100');
                $grid->setAlign('tAlasan_export', 'left');
                $grid->setLabel('tAlasan_export','Alasan Reformulasi');

                $grid->setWidth('dPermintaan_req_export', '100');
                $grid->setAlign('dPermintaan_req_export', 'left');
                $grid->setLabel('dPermintaan_req_export','Tanggal Permintaan Req Reformulasi');

                $grid->setWidth('dPermintaan_bb_export', '100');
                $grid->setAlign('dPermintaan_bb_export', 'left');
                $grid->setLabel('dPermintaan_bb_export','Tanggal Permintaaan Bahan Baku');

                $grid->setWidth('vUploadfile', '100');
                $grid->setAlign('vUploadfile', 'left');
                $grid->setLabel('vUploadfile','Upload File');

                $grid->setWidth('iTeamPD', '100');
                $grid->setAlign('iTeamPD', 'left');
                $grid->setLabel('iTeamPD','Team PD');

                $grid->setWidth('iTeamAndev', '100');
                $grid->setAlign('iTeamAndev', 'left');
                $grid->setLabel('iTeamAndev','Team Andev');

                $grid->setWidth('iSubmitPD', '100');
                $grid->setAlign('iSubmitPD', 'left');
                $grid->setLabel('iSubmitPD','Status Submit');

                $grid->setWidth('cApproval_ats_inisiator', '100');
                $grid->setAlign('cApproval_ats_inisiator', 'left');
                $grid->setLabel('cApproval_ats_inisiator','CAPPROVAL_ATS_INISIATOR');

                $grid->setWidth('vRemark_ats_inisiator', '100');
                $grid->setAlign('vRemark_ats_inisiator', 'left');
                $grid->setLabel('vRemark_ats_inisiator','VREMARK_ATS_INISIATOR');

                $grid->setWidth('dApproval_ats_inisiator', '100');
                $grid->setAlign('dApproval_ats_inisiator', 'left');
                $grid->setLabel('dApproval_ats_inisiator','DAPPROVAL_ATS_INISIATOR');

                $grid->setWidth('iApproval_ats_inisiator', '150');
                $grid->setAlign('iApproval_ats_inisiator', 'left');
                $grid->setLabel('iApproval_ats_inisiator','Approval Atasan Inisiator');

                $grid->setWidth('dCreate', '100');
                $grid->setAlign('dCreate', 'left');
                $grid->setLabel('dCreate','DCREATE');

                $grid->setWidth('cCreated', '100');
                $grid->setAlign('cCreated', 'left');
                $grid->setLabel('cCreated','CCREATED');

                $grid->setWidth('dupdate', '100');
                $grid->setAlign('dupdate', 'left');
                $grid->setLabel('dupdate','DUPDATE');

                $grid->setWidth('cUpdate', '100');
                $grid->setAlign('cUpdate', 'left');
                $grid->setLabel('cUpdate','CUPDATE');

                $grid->setWidth('lDeleted', '100');
                $grid->setAlign('lDeleted', 'left');
                $grid->setLabel('lDeleted','LDELETED');

                //Example modifikasi GRID ERP
                /*
                    - Set Query
                        $grid->setQuery('lDeleted = 0 ', null);
                        $grid->setQuery('plc2_upb.iupb_id IN (select distinct(bk.iupb_id) from plc2.plc2_upb_spesifikasi_fg bk where bk.iappqa=2 and bk.ldeleted=0)', null);

                    - Join Table
                        $grid->setJoinTable('hrd.employee', 'employee.cNip = pk_master.vnip', 'inner');

                    - Change Field Name
                        $grid->changeFieldType('ideleted','combobox','',array(''=>'Pilih',0=>'Aktif',1=>'Tidak aktif'));
                */

                $grid->changeFieldType('iSubmitPD','combobox','',array(0=>'Draft',1=>'Submitted'));
                $grid->setQuery('export_req_refor.lDeleted = 0 ', null);
                $grid->setQuery('export_req_refor.iApproval_ats_inisiator = 2 ', null);


                if($this->auth_export->is_manager()){
                    $x=$this->auth_export->dept();
                    $manager=$x['manager'];
                    if(in_array('PD', $manager)){
                        $grid->setQuery('export_req_refor.iTeamPD IN ('.$this->auth_export->my_teams().')', null);
                    }
                    else{$type='';}
                }
                else{
                    $x=$this->auth_export->dept();
                    $team=$x['team'];
                    if(in_array('PD', $team)){
                        $grid->setQuery('export_req_refor.iTeamPD IN ('.$this->auth_export->my_teams().')', null);

                    }
                    else{$type='';}
                }


                $grid->setJoinTable('dossier.dossier_upd', 'dossier_upd.idossier_upd_id = export_req_refor.idossier_upd_id', 'inner');
                $grid->setJoinTable('sales.itemas', 'itemas.c_iteno = dossier_upd.iupb_id', 'inner');
                $grid->setJoinTable('hrd.employee', 'employee.cNip = export_req_refor.cInisiator_export', 'inner');
                 //set search
                $grid->setSearch('vno_export_req_refor','dossier_upd.vUpd_no','employee.vName');

                //set required
                $grid->setRequired('cPicFormulator');//,'idossier_upd_id','cInisiator_export','iDapartemen_export','tAlasan_export','dPermintaan_req_export','dPermintaan_bb_export','iTeamPD','iTeamAndev');

                $grid->setGridView('grid');

                switch ($action) {
                    case 'json':
                            $grid->getJsonData();
                            break;
                    case 'searchcNip':
                        echo $this->searchcNip();
                        break;
                    case 'view':
                            $grid->render_form($this->input->get('id'), true);
                            break;
                    case 'create':
                            $grid->render_form();
                            break;
                    case 'getInisiator':
                            echo $this->getInisiator();
                            break;
                    case 'createproses':
                            echo $grid->saved_form();
                            break;
                    case 'update':
                            $grid->render_form($this->input->get('id'));
                            break;
                    case 'updateproses':
                            echo $grid->updated_form();
                            break;
                    case 'delete':
                            echo $grid->delete_row();
                            break;
                    default:
                            $grid->render_grid();
                            break;
                }
            }
            //Create Manipulate Field

            //Jika Ingin Menambahkan Seting grid seperti button edit enable dalam kondisi tertentu
            public function searchcNip() {
                    $tgl        = date('Y-m-d');
                    $term       = $this->input->get('term');
                    $iTeamPD    = $this->input->get('iTeamPD');
                    $data = array();

                    $sql = 'SELECT DISTINCT(pt.`vnip`), e.`vName`, m.`iDeptID`, m.`vDescription` FROM reformulasi.`reformulasi_team` p
                            JOIN reformulasi.`reformulasi_team_item` pt ON pt.`ireformulasi_team` = p.`ireformulasi_team`
                            JOIN hrd.`employee` e ON e.`cNip` = pt.`vnip`
                            JOIN hrd.`msdepartement` m ON m.`iDeptID` = e.iDepartementID
                            WHERE p.`ldeleted` = 0 AND pt.`ldeleted` = 0 AND p.`iTipe` = 2 AND pt.`vnip` IS NOT NULL
                            AND (e.`dresign` = "0000-00-00" OR  e.`dresign` > SYSDATE())
                            AND p.`ireformulasi_team` = "'.$iTeamPD.'"
                            AND (e.`cNip` like "%'.$term.'%" OR e.`vName`like "%'.$term.'%")';

                    //$sql = "select cNip, vName from hrd.employee where (cNip like '%{$term}%') limit 1 ";
                    // $sql = "SELECT a.cNip,a.vName,a.iDivisionID,a.iDepartementId,a.ibagid,a.iArea,a.iPostId,
                    //         (SELECT vDescription FROM hrd.msdivision WHERE iDivID=a.iDivisionID) AS divisi,
                    //         (SELECT vDescription FROM hrd.msdepartement WHERE iDeptID=a.iDepartementId) AS departement,
                    //         (SELECT vDescription FROM hrd.bagian WHERE ibagid=a.ibagid) AS bagian,
                    //         (SELECT vAreaname FROM hrd.area WHERE iAreaID=a.iArea) AS vAreaname,
                    //         (SELECT vDescription FROM hrd.position WHERE iPostId=a.iPostId) AS jabatan,
                    //         (SELECT c.vDescription FROM hrd.position AS b LEFT JOIN hrd.lvlemp AS c ON c.iLvlEmp=b.iLvlID
                    //           WHERE b.iPostId=a.iPostID) AS lvlemply

                    //         FROM hrd.employee AS a WHERE
                    //         (a.dresign='0000-00-00' OR a.dresign>'".date('Y-m-d H:i:s')."') AND
                    //         (a.cNip LIKE '%{$term}%' OR a.vName LIKE '%{$term}%') limit 50";
                    //echo $sql;exit;

                    $query = $this->db->query($sql);
                    if ($query->num_rows > 0) {
                        foreach($query->result_array() as $line) {
                            $row_array['id']        = trim($line['vnip']);
                            $row_array['value']     = trim($line['vnip']).' - '.trim($line['vName']);
                            // $row_array['divisi']    = trim($line['divisi']);
                            // $row_array['vAreaname'] = trim($line['vAreaname']);
                            // $row_array['jabatan']   = trim($line['jabatan']);
                            // $row_array['departement']   = trim($line['departement']);
                            // $row_array['bagian']        = trim($line['bagian']);
                            // $row_array['lvlemply']      = trim($line['lvlemply']);

                            // $row_array['iDivisionID']   = trim($line['iDivisionID']);
                            // $row_array['iDepartementId']    = trim($line['iDepartementId']);
                            // $row_array['ibagid']        = trim($line['ibagid']);
                            // $row_array['iArea']         = trim($line['iArea']);
                            // $row_array['iPostId']       = trim($line['iPostId']);
                            array_push($data, $row_array);
                        }
                    }

                    echo json_encode($data);
                    exit;
                }
            function listBox_Action($row, $actions) {
                $cNip= $this->user->gNIP;
                if ($row->iSubmitPD!=0) {
                    unset($actions['edit']);
                }
                return $actions;
            }

            function getInisiator() {
                $term = $this->input->get('term');
                $sql = 'SELECT DISTINCT(pt.`vnip`), p.`vtipe` ,p.`vteam`, e.`vName`, m.`iDeptID`, m.`vDescription` FROM reformulasi.`reformulasi_team` p
                            JOIN reformulasi.`reformulasi_team_item` pt ON pt.`ireformulasi_team` = p.`ireformulasi_team`
                            JOIN hrd.`employee` e ON e.`cNip` = pt.`vnip`
                            JOIN hrd.`msdepartement` m ON m.`iDeptID` = e.iDepartementID
                            WHERE p.`ldeleted` = 0 AND pt.`ldeleted` = 0 AND p.`iTipe` = 2 AND pt.`vnip` IS NOT NULL
                            AND (e.`dresign` = "0000-00-00" OR  e.`dresign` > SYSDATE())
                            AND (e.`cNip` like "%'.$term.'%" OR e.`vName`like "%'.$term.'%")';
                $dt=$this->db->query($sql);
                $data = array();
                if($dt->num_rows>0){
                    foreach($dt->result_array() as $line) {
                        $row_array['value'] = trim($line['vnip']).' - '.trim($line['vName']);
                        $row_array['dep_id'] = trim($line['iDeptID']);
                        $row_array['dep_v'] = trim($line['vDescription']);
                        $row_array['id']    = trim($line['vnip']);
                        array_push($data, $row_array);
                    }
                }
                echo json_encode($data);
                exit;
            }

            function listBox_export_konfirm_req_refor_iApproval_ats_inisiator($value) {
                if($value==0){$vstatus='Waiting for approval';}
                elseif($value==1){$vstatus='Rejected';}
                elseif($value==2){$vstatus='Approved';}
                return $vstatus;
            }

            function insertBox_export_konfirm_req_refor_vUploadfile($field, $id) {
                $data['rows']=array();
                $data['iSubmit'] = 0;
                $return = $this->load->view('export/export_req_refor_file',$data,TRUE);
                return $return;
            }
            function updateBox_export_konfirm_req_refor_vUploadfile($field, $id, $value, $rowData) {
                $sq = "SELECT * FROM reformulasi.`export_req_refor_file` lr WHERE lr.`lDeleted` = 0 AND
                lr.`iexport_req_refor` ='".$rowData['iexport_req_refor']."'";
                $data['rows']=$this->db->query($sq)->result_array();
                $data['iSubmit'] = $rowData['iSubmit'];
                $return = $this->load->view('export/export_req_refor_file',$data,TRUE);
                return $return;
            }

            function insertBox_export_konfirm_req_refor_insBB($field, $id) {
                $data['rows'] = array();
                $data['iSubmit'] = 0;
                $data['ikonfimref'] = 1;
                $data['browse_url'] = base_url().'processor/reformulasi/browse/bb';
                $return = $this->load->view('export/export_req_refor_bahan_baku',$data,TRUE);
                return $return;
            }
            function updateBox_export_konfirm_req_refor_insBB($field, $id, $value, $rowData) {
                $sql = "SELECT e.* FROM reformulasi.`export_request_sample_detail` e
                    JOIN reformulasi.`export_request_sample` r ON r.iexport_request_sample = e.iexport_request_sample
                    WHERE e.lDeleted = 0 AND r.lDeleted = 0 AND r.iexport_req_refor = '".$rowData['iexport_req_refor']."'";
                $data['rows'] = $this->db->query($sql)->result_array();
                $data['iSubmit'] = $rowData['iSubmit'];
                $data['ikonfimref'] = 1;
                $data['browse_url'] = base_url().'processor/reformulasi/browse/bb';
                $return = $this->load->view('export/export_req_refor_bahan_baku',$data,TRUE);
                return $return;
            }


            function insertBox_export_konfirm_req_refor_vno_export_req_refor($field, $id) {
                $return = '<i>Auto Generated</i>';
                $return .= '<input type="hidden" name="isdraft" id="isdraft" class="isdraft">';
                $return .= '<input type="hidden" name="iexport_req_refor" id="iexport_req_refor" class="iexport_req_refor">';

                return $return;
            }
            function updateBox_export_konfirm_req_refor_vno_export_req_refor($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<input type="hidden" name="isdraft" id="isdraft" class="isdraft">';
                $return .= '<input type="hidden" name="iexport_req_refor" id="iexport_req_refor" class="iexport_req_refor" value="'.$rowData['iexport_req_refor'].'">';

                $return .= $value;

                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_idossier_upd_id($field, $id) {

                $uri = 'export_req_refor';
                $o = "";
                $o   .= "<div style='
                                padding: 3px;
                                width: 500px;
                                border: 1px solid rgba(51, 23, 93, 0.2);
                                background-color: #FFF;'>";


                $o   .= "<table border='0' style='width: 100%;'>
                            <tbody>";
                $o  .="         <tr>
                                    <td width='20%'>Nomor UPD</td>
                                    <td>:</td>
                                    <td width='75%'>";
                $o .= '         <input type="hidden" name="'.$field.'"  id="'.$id.'"  class="'.$id.' input_rows1 required" size="30" />';
                $o .= '         <input readonly type="text" name="'.$uri.'_vUpd_no"  id="'.$uri.'_vUpd_no"  class="'.$uri.'_vUpd_no required input_rows1" size="30" />';
                $o .= '         &nbsp;<button class="icon_pop"  onclick="browse(\''.base_url().'processor/reformulasi/browse/dossier/upd?field=export_req_refor\',\'Request Reformulasi\')" type="button">Browse</button>';
                $o  .="             </td>
                                </tr>

                                <tr>
                                    <td width='20%'>Nama Usulan Product</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_vNama_usulan' id='".$uri."_vNama_usulan'></span>
                                    </td>
                                </tr>


                                <tr>
                                    <td width='20%'>Kode Product & Product Existing</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_c_iteno' id='".$uri."_c_iteno'></span>
                                    </td>
                                </tr>

                            </tbody>
                        </table>";
                $o .= "    </div>";

                $o .= '<script>
                        $( "button.icon_pop" ).button({
                            icons: {
                                primary: "ui-icon-newwin"
                            },
                        })
                    </script>';


                return $o;

            }
            function updateBox_export_konfirm_req_refor_idossier_upd_id($field, $id, $value, $rowData) {
                $sql = "SELECT d.`idossier_upd_id`, d.vUpd_no, d.`vNama_usulan`, i.`c_iteno`, i.`c_itnam` FROM dossier.`dossier_upd` d
                        JOIN sales.`itemas` i ON i.`c_iteno` = d.`iupb_id`
                        WHERE d.`lDeleted` = 0 AND i.`lDeleted` = 0 AND d.`idossier_upd_id` = ".$value." LIMIT 1";
                $dt = $this->db->query($sql)->row_array();

                if(empty($dt['vUpd_no'])){
                    $dt['vUpd_no'] = '-';
                }
                if(empty($dt['vNama_usulan'])){
                    $dt['vNama_usulan'] = '-';
                }
                if(empty($dt['c_iteno'])){
                    $dt['c_iteno'] = '-';
                }
                if(empty($dt['c_itnam'])){
                    $dt['c_itnam'] = '-';
                }


                $uri = 'export_req_refor';
                $o = "";
                $o   .= "<div style='
                                padding: 3px;
                                width: 500px;
                                border: 1px solid rgba(51, 23, 93, 0.2);
                                background-color: #FFF;'>";


                $o   .= "<table border='0' style='width: 100%;'>
                            <tbody>";
                $o  .="         <tr>
                                    <td width='20%'>Nomor UPD</td>
                                    <td>:</td>
                                    <td width='75%'>";
                $o .= '         <input type="hidden" name="'.$field.'"  id="'.$id.'"  class="'.$id.' input_rows1 required" size="30" value="'.$value.'" />';
                $o .= '         <input readonly type="text" name="'.$uri.'_vUpd_no"  id="'.$uri.'_vUpd_no"  class="'.$uri.'_vUpd_no required input_rows1" size="30" value="'.$dt['vUpd_no'].'"/>';

                if($rowData['iSubmit']==0){
                    $o .= '         &nbsp;<button class="icon_pop"  onclick="browse(\''.base_url().'processor/reformulasi/browse/dossier/upd?field=export_req_refor\',\'Request Reformulasi\')" type="button">Browse</button>';
                }

                $o  .="             </td>
                                </tr>

                                <tr>
                                    <td width='20%'>Nama Usulan Product</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_vNama_usulan' id='".$uri."_vNama_usulan'>".$dt['vNama_usulan']."</span>
                                    </td>
                                </tr>


                                <tr>
                                    <td width='20%'>Kode Product & Product Existing</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_c_iteno' id='".$uri."_c_iteno'>".$dt['c_iteno']."-".$dt['c_itnam']."</span>
                                    </td>
                                </tr>

                            </tbody>
                        </table>";
                $o .= "    </div>";

                $o .= '<script>
                        $( "button.icon_pop" ).button({
                            icons: {
                                primary: "ui-icon-newwin"
                            },
                        })
                    </script>';


                return $o;
            }






            function insertBox_export_konfirm_req_refor_cInisiator_export($field, $id) {
                $url1 = base_url().'processor/reformulasi/export/konfirm/req/refor?action=getInisiator';

                $uri = 'export_req_refor';
                $o = "";
                $o   .= "<div style='
                                padding: 3px;
                                width: 500px;
                                border: 1px solid rgba(51, 23, 93, 0.2);
                                background-color: #FFF;'>";


                $o   .= "<table border='0' style='width: 100%;'>
                            <tbody>";
                $o  .="         <tr>
                                    <td width='20%'>Nama Inisiator</td>
                                    <td>:</td>
                                    <td width='75%'>";
                $o .= '         <input type="hidden" name="'.$field.'"  id="'.$id.'"  class="'.$id.' input_rows1 required" size="30" />';
                $o .= '         <input type="hidden" name="'.$uri.'_iDapartemen_export"  id="'.$uri.'_iDapartemen_export"  class="'.$uri.'_iDapartemen_export required input_rows1" size="30" />';
                $o .= '         <input type="text" name="'.$uri.'_vName"  id="'.$uri.'_vName"  class="'.$uri.'_vName required input_rows1" size="30" />';
                $o .="             </td>
                                </tr>
                                <tr>
                                    <td width='20%'>Dapartement</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_vDapartemen_export' id='".$uri."_vDapartemen_export'></span>
                                    </td>
                                </tr>

                            </tbody>
                        </table>";
                $o .= " </div>";

                $o .= '<script language="text/javascript">
                            $(document).ready(function() {
                                var config1 = {
                                    source: function( request, response) {
                                        $.ajax({
                                            url: "'.$url1.'",
                                            dataType: "json",
                                            data: {
                                                term: request.term,
                                            },
                                            beforeSend: function(){
                                                $( "#'.$id.'" ).val("");
                                            },

                                            success: function( data ) {
                                                response( data );
                                            }
                                        });
                                    },
                                    select: function(event, ui){
                                        $( "#'.$id.'" ).val(ui.item.id);
                                        $( "#'.$uri.'_vName" ).val(ui.item.value);
                                        $( "#'.$uri.'_vDapartemen_export" ).text(ui.item.dep_v);
                                        $( "#'.$uri.'_iDapartemen_export" ).val(ui.item.dep_id);
                                        return false;
                                    },
                                    minLength: 2,
                                    autoFocus: true,
                                };

                                $( "#'.$uri.'_vName" ).livequery(function() {
                                    $( this ).autocomplete(config1);
                                });

                            });
                      </script>';

                return $o;
            }
            function updateBox_export_konfirm_req_refor_cInisiator_export($field, $id, $value, $rowData) {
                $sql = "SELECT e.`cNip`, e.`vName`, e.`iDepartementID`, m.`vDescription` FROM hrd.`employee` e
                    JOIN hrd.`msdepartement` m ON m.`iDeptID` = e.`iDepartementID`
                    WHERE e.`cNip` ='".$value."'";
                $dt = $this->db->query($sql)->row_array();
                $cnip = '';
                if(!empty($dt['vName'])){
                    $cnip = $value.'-'.$dt['vName'];
                }
                if(empty($dt['vDescription'])){
                    $dt['vDescription'] = '';
                }

                $url1 = base_url().'processor/reformulasi/export/konfirm/req/refor?action=getInisiator';
                $uri = 'export_req_refor';
                $o = "";
                $o   .= "<div style='
                                padding: 3px;
                                width: 500px;
                                border: 1px solid rgba(51, 23, 93, 0.2);
                                background-color: #FFF;'>";


                $o   .= "<table border='0' style='width: 100%;'>
                            <tbody>";
                $o  .="         <tr>
                                    <td width='20%'>Nama Inisiator</td>
                                    <td>:</td>
                                    <td width='75%'>";
                $o .= '         <input type="hidden" name="'.$field.'"  id="'.$id.'"  class="'.$id.' input_rows1 required" size="30" value="'.$value.'"/>';
                $o .= '         <input type="hidden" name="'.$uri.'_iDapartemen_export"  id="'.$uri.'_iDapartemen_export"  class="'.$uri.'_iDapartemen_export required input_rows1" size="30" value="'.$rowData['iDapartemen_export'].'"/>';
                if($rowData['iSubmit']==0){
                    $o .= '         <input type="text" name="'.$uri.'_vName"  id="'.$uri.'_vName"  class="'.$uri.'_vName required input_rows1" size="30" value="'.$cnip.'"/>';
                }else{
                    $o .= '         <input readonly type="text" name="'.$uri.'_vName2"  id="'.$uri.'_vName2"  class="'.$uri.'_vName required input_rows1" size="30" value="'.$cnip.'"/>';

                }
                $o .="             </td>
                                </tr>
                                <tr>
                                    <td width='20%'>Dapartement</td>
                                    <td>:</td>
                                    <td width='75%'>
                                        <span class='".$uri."_vDapartemen_export' id='".$uri."_vDapartemen_export'>".$dt['vDescription']."</span>
                                    </td>
                                </tr>

                            </tbody>
                        </table>";
                $o .= " </div>";

                $o .= '<script language="text/javascript">
                            $(document).ready(function() {
                                var config1 = {
                                    source: function( request, response) {
                                        $.ajax({
                                            url: "'.$url1.'",
                                            dataType: "json",
                                            data: {
                                                term: request.term,
                                            },
                                            beforeSend: function(){
                                                $( "#'.$id.'" ).val("");
                                            },

                                            success: function( data ) {
                                                response( data );
                                            }
                                        });
                                    },
                                    select: function(event, ui){
                                        $( "#'.$id.'" ).val(ui.item.id);
                                        $( "#'.$uri.'_vName" ).val(ui.item.value);
                                        $( "#'.$uri.'_vDapartemen_export" ).text(ui.item.dep_v);
                                        $( "#'.$uri.'_iDapartemen_export" ).val(ui.item.dep_id);
                                        return false;
                                    },
                                    minLength: 2,
                                    autoFocus: true,
                                };

                                $( "#'.$uri.'_vName" ).livequery(function() {
                                    $( this ).autocomplete(config1);
                                });

                            });
                      </script>';
                    return $o;

            }

            function insertBox_export_konfirm_req_refor_iDapartemen_export($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "52" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 52);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(52 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">52</span> karakter<br/>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_iDapartemen_export($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "52"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 52) {
                                            this.value = this.value.substring(0, 52);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(52 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">52</span> karakter<br/>';

                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_tAlasan_export($field, $id) {
                $return = '<textarea name="'.$field.'" id="'.$id.'" style="width: 240px; height: 50px;" size="250" maxlength ="250"></textarea>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 255);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(255 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">250</span> karakter<br/>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_tAlasan_export($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                    $return= '<label title="Note">'.nl2br($value).'</label>';
                }else{
                    if($rowData['iSubmit']==0){
                        $return = '<textarea name="'.$field.'" id="'.$id.'"  style="width: 240px; height: 50px;" size="250" maxlength ="250">'.nl2br($value).'</textarea>';
                    } else{
                        $return = '<textarea readonly name="'.$field.'" id="'.$id.'"  style="width: 240px; height: 50px;" size="250" maxlength ="250">'.nl2br($value).'</textarea>';
                    }
                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_dPermintaan_req_export($field, $id) {
                $return = '<input readonly type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.date("Y-m-d H:i:s").'"/>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_dPermintaan_req_export($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                    if($value=="0000-00-00" or empty($value) or $rowData['iSubmit']==0){
                        $value = date("Y-m-d H:i:s");
                    }
                    $return = '<input readonly type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_dPermintaan_bb_export($field, $id) {
                $return = '<input readonly type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.date("Y-m-d H:i:s").'"/>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_dPermintaan_bb_export($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                    if($value=="0000-00-00" or empty($value) or $rowData['iSubmit']==0){
                        $value = date("Y-m-d H:i:s");
                    }
                    $return = '<input readonly type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                }
                return $return;
            }


            function insertBox_export_konfirm_req_refor_iUjibe($field, $id) {
                $dt = array('0'=>'No','1'=>'Yes');
                $o = '<select class="input_rows1 required" name="'.$field.'" id="'.$id.'">';
                foreach ($dt as $t => $v) {
                    $o .= '<option value="'.$t.'">'.$v.'</option>';
                }
                $o .= '</select> <style>
                         #'.$id.'{
                             width:180px;
                        }
                      </style>';
                return $o;

            }
            function updateBox_export_konfirm_req_refor_iUjibe($field, $id, $value, $rowData) {

                if ($this->input->get('action') == 'view') {
                    $dt = array(''=>'No','0'=>'No','1'=>'Yes');
                    $o = $dt[$value];
                } else {
                    $dt = array('0'=>'No','1'=>'Yes');
                    $o ='';
                    $disab = '';
                    if($rowData['iSubmit']!=0){
                        $disab = ' disabled ';
                        $o .="<input type='hidden' name='".$field."' id='".$id."' value='".$value."'/>";
                    }

                    $o .= "<select ".$disab." name='".$field."' id='".$id."' class='required'>";

                    foreach ($dt as $t => $v) {
                           if ($value == $t) $selected = " selected";
                           else $selected = '';
                           $o .= "<option {$selected} value='".$t."'>".$v."</option>";
                        }
                    }
                $o .= '</select> <style>
                         #'.$id.'{
                             width:180px;
                        }
                      </style>';
                return $o;

            }


            function insertBox_export_konfirm_req_refor_iTeamPD($field, $id) {
                $sql = " SELECT p.`ireformulasi_team`, p.`vteam` FROM reformulasi.`reformulasi_team` p
                    WHERE p.`ldeleted` = 0 AND p.`vtipe` = 'PD'";
                $dt = $this->db->query($sql)->result_array();

                $o = '<select class="input_rows1 required" name="'.$field.'" id="'.$id.'">';
                $o .= '<option value="">--Select--</option>';
                foreach ($dt as $t) {
                    $o .= '<option value="'.$t['ireformulasi_team'].'">'.$t['vteam'].'</option>';
                }
                $o .= '</select> <style>
                         #'.$id.'{
                             width:180px;
                        }
                      </style>';
                return $o;

            }
            function updateBox_export_konfirm_req_refor_iTeamPD($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                    $sql = " SELECT p.`ireformulasi_team`, p.`vteam` FROM reformulasi.`reformulasi_team` p
                    WHERE p.`ldeleted` = 0 AND p.`vtipe` = 'PD' AND p.`ireformulasi_team`='".$value."'";
                    $query = $this->db->query($sql);
                    if ($query->num_rows() > 0) {
                        $row = $query->row();
                        $o = $row->vteam;
                    }
                } else {
                    $o ='';
                    $disab = '';
                    if($rowData['iSubmit']!=0){
                        $disab = ' disabled ';
                        $o .="<input type='hidden' name='".$field."' id='".$id."' value='".$value."'/>";
                    }

                    $o .= "<select ".$disab." name='".$field."' id='".$id."' class='required'>";
                    $o .= "<option value=''>Pilih</option>";
                    $sql = " SELECT p.`ireformulasi_team`, p.`vteam` FROM reformulasi.`reformulasi_team` p
                        WHERE p.`ldeleted` = 0 AND p.`vtipe` = 'PD'";
                    $query = $this->db->query($sql);
                    if ($query->num_rows() > 0) {
                        $result = $query->result_array();
                        foreach($result as $row) {
                               if ($value == $row['ireformulasi_team']) $selected = " selected";
                               else $selected = '';
                               $o .= "<option {$selected} value='".$row['ireformulasi_team']."'>".$row['vteam']."</option>";
                            }
                        }
                    }
                $o .= '</select> <style>
                         #'.$id.'{
                             width:180px;
                        }
                      </style>';
                return $o;

            }

            function insertBox_export_konfirm_req_refor_iTeamAndev($field, $id) {
                $sql = " SELECT p.`ireformulasi_team`, p.`vteam` FROM reformulasi.`reformulasi_team` p
                    WHERE p.`ldeleted` = 0 AND p.`vtipe` = 'AD' AND p.iTipe = 2";
                $dt = $this->db->query($sql)->result_array();

                $o = '<select class="input_rows1 required" name="'.$field.'" id="'.$id.'">';
                $o .= '<option value="">--Select--</option>';
                foreach ($dt as $t) {
                    $o .= '<option value="'.$t['ireformulasi_team'].'">'.$t['vteam'].'</option>';
                }
                $o .= '</select> <style>
                         #'.$id.'{
                             width:180px;
                        }
                      </style>';
                return $o;
            }
            function updateBox_export_konfirm_req_refor_iTeamAndev($field, $id, $value, $rowData) {
                $o="";
                if ($this->input->get('action') == 'view') {
                    $sql = " SELECT p.`ireformulasi_team`, p.`vteam` FROM reformulasi.`reformulasi_team` p
                    WHERE p.`ldeleted` = 0 AND p.`vtipe` = 'AD' AND p.`ireformulasi_team`='".$value."'";
                    $query = $this->db->query($sql);
                    if ($query->num_rows() > 0) {
                        $row = $query->row();
                        $o = $row->vteam;
                    }
                } else {
                    $o ='';
                    $disab = '';
                    if($rowData['iSubmit']!=0){
                        $disab = ' disabled ';
                        $o .="<input type='hidden' name='".$field."' id='".$id."' value='".$value."'/>";
                    }

                    $o .= "<select ".$disab." name='".$field."' id='".$id."' class='required'>";
                    $o .= "<option value=''>Pilih</option>";
                    $sql = " SELECT p.`ireformulasi_team`, p.`vteam` FROM reformulasi.`reformulasi_team` p
                        WHERE p.`ldeleted` = 0 AND p.`vtipe` = 'AD'  AND p.iTipe = 2";
                    $query = $this->db->query($sql);
                    if ($query->num_rows() > 0) {
                        $result = $query->result_array();
                        foreach($result as $row) {
                               if ($value == $row['ireformulasi_team']) $selected = " selected";
                               else $selected = '';
                               $o .= "<option {$selected} value='".$row['ireformulasi_team']."'>".$row['vteam']."</option>";
                            }
                        }
                    }
                $o .= '</select> <style>
                         #'.$id.'{
                             width:180px;
                        }
                      </style>';
                return $o;
            }

            function insertBox_export_konfirm_req_refor_iSubmit($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_iSubmit($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_cApproval_ats_inisiator($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_cApproval_ats_inisiator($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 50) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_vRemark_ats_inisiator($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "200" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 200);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(200 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">200</span> karakter<br/>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_vRemark_ats_inisiator($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "200"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 200) {
                                            this.value = this.value.substring(0, 200);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(200 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">200</span> karakter<br/>';

                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_dApproval_ats_inisiator($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"});
                             </script>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_dApproval_ats_inisiator($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").datepicker({
                                    changeMonth:true,
                                    changeYear:true,
                                    dateFormat:"yy-mm-dd"
                                });
                             </script>';
                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_iApproval_ats_inisiator($field, $id) {
                $return ='';
                $return .= '
                            <script type="text/javascript">
                                $("label[for=\''.$id.'\']").hide();
                                $("label[for=\''.$id.'\']").next().css("margin-left",0);
                            </script>
                        ';
                $return .= '<div></div>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_iApproval_ats_inisiator($field, $id, $value, $rowData) {
                if(($value <> 0) || (!empty($value))){
                    $sql_dtapp = "SELECT * FROM reformulasi.`export_req_refor` a JOIN hrd.employee b on b.cNip=a.cApproval_ats_inisiator
                    WHERE a.`lDeleted` = 0 AND a.iexport_req_refor = '".$rowData['iexport_req_refor']."'";
                    $row = $this->db->query($sql_dtapp)->row_array();

                    if($value==2){
                        $st='<p style="">Approved';
                        $ret= $st.' oleh '.$row['vName'].' pada '.$row['dApproval_ats_inisiator'].'</br> Alasan: '.$row['vRemark_ats_inisiator'].'</p>';
                    }
                    elseif($value==1){
                        $st='<p style="color:red;">Rejected';
                        $ret= $st.' oleh '.$row['vName'].' pada '.$row['dApproval_ats_inisiator'].'</br> Alasan: '.$row['vRemark_ats_inisiator'].'</p>';
                    }
                }
                else{
                    $ret='Waiting for Approval';
                }
                $ret .= "<input type='hidden' name='".$field."' id='".$id."'  value='".$value."'/>";
                return '<i>'.$ret.'</i>';
            }

            function insertBox_export_konfirm_req_refor_dCreate($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"});
                             </script>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_dCreate($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").datepicker({
                                    changeMonth:true,
                                    changeYear:true,
                                    dateFormat:"yy-mm-dd"
                                });
                             </script>';
                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_cCreated($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_cCreated($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 50) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_dupdate($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"});
                             </script>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_dupdate($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").datepicker({
                                    changeMonth:true,
                                    changeYear:true,
                                    dateFormat:"yy-mm-dd"
                                });
                             </script>';
                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_cUpdate($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_cUpdate($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 50) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_lDeleted($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                return $return;
            }
            function updateBox_export_konfirm_req_refor_lDeleted($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value;
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                     this.value = this.value.replace(/[^0-9\.]/g,"");
                                });
                             </script>';
                }
                return $return;
            }

            function insertBox_export_konfirm_req_refor_cPicFormulator($field, $id) {
                $url6 = base_url().'processor/reformulasi/export/konfirm/req/refor?action=searchcNip';
                $o = "<script type='text/javascript'>
                                $(document).ready(function() {
                                    $('#".$id."_').live('keyup', function(e) {
                                        var config = {
                                            source: '".$url6."',
                                            select: function(event, ui){
                                                $('#".$id."').val(ui.item.id);
                                                $('#".$id."_').val(ui.item.value);
                                                return false;
                                            },
                                            minLength: 2,
                                            autoFocus: true,
                                            };
                                        $('#".$id."_').autocomplete(config);
                                        $(this).keypress(function(e){
                                            if(e.which != 13) {
                                                $('#".$id."').val('');
                                            }
                                        });
                                        $(this).blur(function(){
                                            if($('#".$id."').val() == '') {
                                                $(this).val('');
                                            }
                                        });

                                    });

                                });
                          </script>";
                $o   .= '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value=""/>';
                $o   .= '<input type="text" name="'.$field.'_"  id="'.$id.'_"  class="input_rows1 " size="30" maxlength = "50"  value=""/>';
                return $o;
            }
            function updateBox_export_konfirm_req_refor_cPicFormulator($field, $id, $value, $rowData) {
                $vn = "SELECT e.`vName` FROM hrd.`employee` e WHERE e.`cNip` = '".$value."'";
                $vName = $this->db->query($vn)->row_array();
                if(empty($vName['vName'])){
                    $vName['vName'] = '-';
                }
                if ($this->input->get('action') == 'view') {
                     $o= $value.' - '.$vName['vName'];
                }else{
                    $url6 = base_url().'processor/reformulasi/export/konfirm/req/refor?action=searchcNip&iTeamPD='.$rowData['iTeamPD'];
                    $o = "<script type='text/javascript'>
                                    $(document).ready(function() {
                                        $('#".$id."_').live('keyup', function(e) {
                                            var config = {
                                                source: '".$url6."',
                                                select: function(event, ui){
                                                    $('#".$id."').val(ui.item.id);
                                                    $('#".$id."_').val(ui.item.value);
                                                    return false;
                                                },
                                                minLength: 2,
                                                autoFocus: true,
                                                };
                                            $('#".$id."_').autocomplete(config);
                                            $(this).keypress(function(e){
                                                if(e.which != 13) {
                                                    $('#".$id."').val('');
                                                }
                                            });
                                            $(this).blur(function(){
                                                if($('#".$id."').val() == '') {
                                                    $(this).val('');
                                                }
                                            });

                                        });

                                    });
                              </script>";
                    $o   .= '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                    $o   .= '<input type="text" name="'.$field.'_"  id="'.$id.'_"  class="input_rows1 " size="30" maxlength = "50"  value="'.$value.' - '.$vName['vName'].'"/>';
                }


                return $o;
            }

                //Ini Merupakan Standart Approve yang digunakan di erp

                function approve_view() {
                    $echo = '<script type="text/javascript">
                                 function submit_ajax(form_id) {
                                    return $.ajax({
                                        url: $("#"+form_id).attr("action"),
                                        type: $("#"+form_id).attr("method"),
                                        data: $("#"+form_id).serialize(),
                                        success: function(data) {
                                            var o = $.parseJSON(data);
                                            var last_id = o.last_id;
                                            var url = "'.base_url().'processor/reformulasi/export_req_refor";
                                            if(o.status == true) {
                                                $("#alert_dialog_form").dialog("close");
                                                     $.get(url+"?action=update&id="+last_id, function(data) {
                                                     $("div#form_export_req_refor").html(data);

                                                });

                                            }
                                                reload_grid("grid_export_req_refor");
                                        }

                                     })
                                 }
                             </script>';
                    $echo .= '<h1>Approve</h1><br />';
                    $echo .= '<form id="form_export_req_refor_approve" action="'.base_url().'processor/reformulasi/export_req_refor?action=approve_process" method="post">';
                    $echo .= '<div style="vertical-align: top;">';
                    $echo .= 'Remark :
                            <input type="hidden" name="iexport_req_refor" value="'.$this->input->get('iexport_req_refor').'" />
                            <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                            <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                            <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                            <textarea name="vRemark"></textarea>
                    <button type="button" onclick="submit_ajax(\'form_export_req_refor_approve\')">Approve</button>';

                    $echo .= '</div>';
                    $echo .= '</form>';
                    return $echo;
                }

                function approve_process() {
                    $post = $this->input->post();
                    $cNip= $this->user->gNIP;
                    $vName= $this->user->gName;
                    $iexport_req_refor = $post['iexport_req_refor'];
                    $vRemark = $post['vRemark'];
                    $lvl = $post['lvl'];

                    //Letakan Query Update approve disini
                    $this->db->where('iexport_req_refor', $post['iexport_req_refor']);
                    $this->db->update('reformulasi.export_req_refor', array('iApproval_ats_inisiator'=>2,'cApproval_ats_inisiator'=>$cNip,'dApproval_ats_inisiator'=>date('Y-m-d H:i:s'),'vRemark_ats_inisiator'=>$vRemark));

                    //Email inHere

                    $data['status']  = true;
                    $data['last_id'] = $post['iexport_req_refor'];
                    return json_encode($data);
                }




                //Ini Merupakan Standart Reject yang digunakan di erp

                function reject_view() {
                    $echo = '<script type="text/javascript">
                                 function submit_ajax(form_id) {
                                    var remark = $("#export_req_refor_remark").val();
                                    if (remark=="") {
                                        alert("Remark tidak boleh kosong ");
                                        return
                                    }

                                    return $.ajax({
                                        url: $("#"+form_id).attr("action"),
                                        type: $("#"+form_id).attr("method"),
                                        data: $("#"+form_id).serialize(),
                                        success: function(data) {
                                            var o = $.parseJSON(data);
                                            var last_id = o.last_id;
                                            var url = "'.base_url().'processor/reformulasi/export_req_refor";
                                            if(o.status == true) {
                                                $("#alert_dialog_form").dialog("close");
                                                     $.get(url+"?action=update&id="+last_id, function(data) {
                                                     $("div#form_export_req_refor").html(data);

                                                });

                                            }
                                                reload_grid("grid_export_req_refor");
                                        }

                                     })
                                 }
                             </script>';
                    $echo .= '<h1>Reject</h1><br />';
                    $echo .= '<form id="form_export_req_refor_reject" action="'.base_url().'processor/reformulasi/export_req_refor?action=reject_process" method="post">';
                    $echo .= '<div style="vertical-align: top;">';
                    $echo .= 'Remark :
                            <input type="hidden" name="iexport_req_refor" value="'.$this->input->get('iexport_req_refor').'" />
                            <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                            <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                            <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                            <textarea name="vRemark"></textarea>
                    <button type="button" onclick="submit_ajax(\'form_export_req_refor_reject\')">Reject</button>';

                    $echo .= '</div>';
                    $echo .= '</form>';
                    return $echo;
                }



                function reject_process() {
                    $post = $this->input->post();
                    $cNip= $this->user->gNIP;
                    $vName= $this->user->gName;
                    $iexport_req_refor = $post['iexport_req_refor'];
                    $lvl = $post['lvl'];
                    $vRemark = $post['vRemark'];

                    $this->db->where('iexport_req_refor', $post['iexport_req_refor']);
                    $this->db->update('reformulasi.export_req_refor', array('iSubmit'=>0,'iRejected'=>1,'cUpdate'=>$cNip,'dupdate'=>date('Y-m-d H:i:s'),'vRemar_re'=>$vRemark));
                    //Letakan Query Update approve disini

                    //Email inHere

                    $data['status']  = true;
                    $data['last_id'] = $post['iexport_req_refor'];
                    return json_encode($data);
                }



            //Standart Setiap table harus memiliki dCreate , cCreated, dupdate, cUpdate
            function before_insert_processor($row, $postData) {
                $postData['dCreate'] = date('Y-m-d H:i:s');
                $postData['cCreated']=$this->user->gNIP;

                if($postData['isdraft']==true){
                    $postData['iSubmitPD']=0;
                }
                else{
                    $postData['iSubmitPD']=1;
                }

                return $postData;


            }
            function before_update_processor($row, $postData) {
                $postData['dupdate'] = date('Y-m-d H:i:s');
                $postData['cUpdate'] = $this->user->gNIP;

                if($postData['isdraft']==true){
                    $postData['iSubmitPD']=0;
                }
                else{
                    $postData['iSubmitPD']=1;
                }

                return $postData;
            }
            function after_update_processor($fields, $id, $postData) {
                if( $postData['iSubmitPD']==1){
                    $sqlHead = "SELECT s.`vRequest_no`, s.iexport_request_sample FROM reformulasi.`export_request_sample` s
                        WHERE s.`lDeleted` = 0 AND s.`iTujuan_request`=1 AND s.`iexport_req_refor` = '".$id."' LIMIT 1";
                    $head = $this->db->query($sqlHead)->row_array();
                    if(!empty($head['vRequest_no'])){

                        $sqlU = "UPDATE reformulasi.`export_request_sample` SET
                            cRequestor = '".$postData['cPicFormulator']."' ,
                            iSubmit = 1,
                            iApprove_pd = 2,
                            cApprove_pd = '".$this->user->gNIP."',
                            dApprove_pd = '".date('Y-m-d')."',
                            vRemark = 'Approve, when konfirm request reformulasi'
                            WHERE iexport_request_sample = '".$head['iexport_request_sample']."'";
                            $this->db->query($sqlU);

                        $sqlMail = "SELECT m.`vTo`,m.`vCc` FROM reformulasi.`mailsparam` m WHERE m.`cVariable` LIKE '%export_permintaan_sample_app%' AND m.`lDeleted` = 0";
                        $mail = $this->db->query($sqlMail)->row_array();

                        if(empty($mail['vTo'])){
                            $mail['vTo'] = $this->user->gNIP;
                        }
                        $toMail2 = $postData['cPicFormulator'];
                        $toMail1 = $mail['vTo'];
                        if(empty($mail['vCc'])){
                            $mail['vCc'] = $this->user->gNIP;
                        }

                        $subject1="Permintaan Bahan Baku: No Request ".$head['vRequest_no'];
                        $subject2="Konfirmasi Request Refor: No Request ".$head['vRequest_no'];
                        $content1="
                        Diberitahukan bahwa telah ada ada Permintaan Bahan Baku dari Proses Request Reformulasi Export,
                            dengan rincian sebagai berikut :<br><br>";
                        $content2="
                        Diberitahukan bahwa telah ada ada Konfirmasi dari Proses Request Reformulasi Export,
                            dengan rincian sebagai berikut :<br><br>";

                            $sqlDta ="SELECT s.`vRequest_no`,rw.`vnama`,sd.`raw_id`,sd.`vSatuan`,sd.`vSpesifikasi`,sd.`iJumlah` FROM reformulasi.`export_req_refor` r
                                JOIN reformulasi.`export_request_sample` s ON r.`iexport_req_refor` = s.`iexport_req_refor`
                                JOIN reformulasi.`export_request_sample_detail` sd ON sd.`iexport_request_sample` = s.`iexport_request_sample`
                                JOIN plc2.`plc2_raw_material` rw ON sd.`raw_id` = rw.`raw_id`
                                WHERE s.`lDeleted` = 0 AND s.`iTujuan_request`=1 AND sd.`lDeleted` = 0  AND r.`iexport_req_refor` = '".$id."'";

                        $content.="<table width='80%' border='1'>

                                    <tr>
                                        <td width='5%'><b>No</b></td>
                                        <td width='45%'><b>Nama Material</b></td>
                                        <td width='10%'><b>Satuan</b></td>
                                        <td width='15%'><b>Spesifikasi</b></td>
                                        <td width='5%'><b>Jumlah</b></td>
                                    </tr>";
                            $dtaTampil = $this->db->query($sqlDta)->result_array();
                            $noUrut = 0;
                            foreach ($dtaTampil as $dt) {
                                $noUrut++;
                                $content.="<tr>
                                                <td width='5%'>".$noUrut."</td>
                                                <td width='45%'>".$dt['vnama']."</td>
                                                <td width='10%'>".$dt['vSatuan']."</td>
                                                <td width='15%'>".$dt['vnama']."</td>
                                                <td width='5%'>".$dt['iJumlah']."</td>
                                            </tr>";
                            }

                        $content.="</table><br/>
                        Demikian, mohon segera follow up  pada aplikasi ERP Reformulasi. Terimakasih.<br><br><br>
                        Post Master";
                        $this->sess_auth->send_message_erp($this->uri->segment_array(), $toMail1, $mail['vCc'], $subject1, $content1.' '.$content);
                        $this->sess_auth->send_message_erp($this->uri->segment_array(), $toMail2, $mail['vCc'], $subject2, $content2.' '.$content);
                    }
                }
            }

            function after_insert_processor($fields, $id, $postData) {
                if( $postData['iSubmitPD']==1){
                    $sqlHead = "SELECT s.`vRequest_no`, s.iexport_request_sample FROM reformulasi.`export_request_sample` s
                        WHERE s.`lDeleted` = 0 AND s.`iTujuan_request`=1 AND s.`iexport_req_refor` = '".$id."' LIMIT 1";
                    $head = $this->db->query($sqlHead)->row_array();
                    if(!empty($head['vRequest_no'])){

                        //Update Ke Formulator
                        $sqlU = "UPDATE reformulasi.`export_request_sample` SET
                            cRequestor = '".$postData['cPicFormulator']."' ,
                            iSubmit = 1,
                            iApprove_pd = 2,
                            cApprove_pd = '".$this->user->gNIP."',
                            dApprove_pd = '".date('Y-m-d')."',
                            vRemark = 'Approve, when konfirm request reformulasi'
                            WHERE iexport_request_sample = '".$head['iexport_request_sample']."'";
                            $this->db->query($sqlU);

                        $sqlMail = "SELECT m.`vTo`,m.`vCc` FROM reformulasi.`mailsparam` m WHERE m.`cVariable`
                        LIKE '%export_permintaan_sample_app%' AND m.`lDeleted` = 0";
                        $mail = $this->db->query($sqlMail)->row_array();

                        if(empty($mail['vTo'])){
                            $mail['vTo'] = $this->user->gNIP;
                        }
                        $toMail2 = $postData['cPicFormulator'];
                        $toMail1 = $mail['vTo'];
                        if(empty($mail['vCc'])){
                            $mail['vCc'] = $this->user->gNIP;
                        }

                        //$subject="Permintaan Bahan Baku: No Request ".$head['vRequest_no'];
                        $subject1="Permintaan Bahan Baku: No Request ".$head['vRequest_no'];
                        $subject2="Konfirmasi Request Refor: No Request ".$head['vRequest_no'];
                        $content1="
                        Diberitahukan bahwa telah ada ada Permintaan Bahan Baku dari Proses Request Reformulasi Export,
                            dengan rincian sebagai berikut :<br><br>";
                        $content2="
                        Diberitahukan bahwa telah ada ada Konfirmasi dari Proses Request Reformulasi Export,
                            dengan rincian sebagai berikut :<br><br>";

                            $sqlDta ="SELECT s.`vRequest_no`,rw.`vnama`,sd.`raw_id`,sd.`vSatuan`,sd.`vSpesifikasi`,sd.`iJumlah` FROM reformulasi.`export_req_refor` r
                                JOIN reformulasi.`export_request_sample` s ON r.`iexport_req_refor` = s.`iexport_req_refor`
                                JOIN reformulasi.`export_request_sample_detail` sd ON sd.`iexport_request_sample` = s.`iexport_request_sample`
                                JOIN plc2.`plc2_raw_material` rw ON sd.`raw_id` = rw.`raw_id`
                                WHERE s.`lDeleted` = 0 AND s.`iTujuan_request`=1 AND sd.`lDeleted` = 0  AND r.`iexport_req_refor` = '".$id."'";

                        $content.="<table width='80%' border='1'>

                                    <tr>
                                        <td width='5%'><b>No</b></td>
                                        <td width='45%'><b>Nama Material</b></td>
                                        <td width='10%'><b>Satuan</b></td>
                                        <td width='15%'><b>Spesifikasi</b></td>
                                        <td width='5%'><b>Jumlah</b></td>
                                    </tr>";
                            $dtaTampil = $this->db->query($sqlDta)->result_array();
                            $noUrut = 0;
                            foreach ($dtaTampil as $dt) {
                                $noUrut++;
                                $content.="<tr>
                                                <td width='5%'>".$noUrut."</td>
                                                <td width='45%'>".$dt['vnama']."</td>
                                                <td width='10%'>".$dt['vSatuan']."</td>
                                                <td width='15%'>".$dt['vnama']."</td>
                                                <td width='5%'>".$dt['iJumlah']."</td>
                                            </tr>";
                            }

                        $content.="</table><br/>
                        Demikian, mohon segera follow up  pada aplikasi ERP Reformulasi. Terimakasih.<br><br><br>
                        Post Master";
                        $this->sess_auth->send_message_erp($this->uri->segment_array(),$toMail1, $mail['vCc'], $subject1, $content1.' '.$content);
                        $this->sess_auth->send_message_erp($this->uri->segment_array(),$toMail2, $mail['vCc'], $subject2, $content2.' '.$content);
                    }
                }
            }

            function manipulate_update_button($buttons, $rowData) {
                //Load Javascript In Here
                // if ($this->input->get('action') == 'view') {
                //     unset($buttons['update']);
                // }
                // else{

                // }

                // return $buttons;

                if ($this->input->get('action') == 'view') {
                    unset($buttons['update_back']);
                    unset($buttons['update']);
                }
                else{
                    $cNip= $this->user->gNIP;

                    $js = $this->load->view('export/js/export_konfirm_req_refor_js');
                    $update = '<button onclick="javascript:update_btn_back(\'export_konfirm_req_refor\', \''.base_url().'processor/reformulasi/export/konfirm/req/refor?company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\', this)" class="ui-button-text icon-save" id="button_update_export_konfirm_req_refor">Update & Submit</button>';
                    $updatedraft = '<button onclick="javascript:update_draft_btn(\'export_konfirm_req_refor\', \''.base_url().'processor/reformulasi/export/konfirm/req/refor?company_id='.$this->input->get('company_id').'&draft=true&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\', this, true)" class="ui-button-text icon-save" id="button_save_export_konfirm_req_refor">Update as Draft</button>';

                    if($rowData['iSubmitPD']==0){
                        $buttons['update'] = $updatedraft.$update.$js;
                    }else{
                        unset($buttons['update_back']);
                        unset($buttons['update']);
                    }

                }

                return $buttons;
            }
            function upperInisiator($cNip,$cUpper){
                $sql = "SELECT e.`cUpper` FROM hrd.`employee` e WHERE e.`cNip` = '".$cNip."' LIMIT 1";
                $dt = $this->db->query($sql)->row_array();
                if(!empty($dt['cUpper'])){
                    if($dt['cUpper']==$cUpper){
                        return 1;
                    }else{
                        return 0;
                    }
                }else{
                    return 0;
                }
            }
            //Output
            public function output(){
                $this->index($this->input->get('action'));
            }
        }
