 
        <?php
        /* Generated by Sovdev 2 ERP CRUD Generator 2017-11-25 08:43:11 */
        /* Location: ./modules/reformulasi/controllers/lokal_req_ujibe.php */
        /* Please DO NOT modify this information : */ 
         
        if ( ! defined('BASEPATH')) exit('No direct script access allowed');
        class lokal_req_ujibe extends MX_Controller {
            function __construct() {
                parent::__construct();
                $this->load->library('auth_local');
                $this->db = $this->load->database('formulasi', false, true);
                $this->dbset = $this->load->database('reformulasi', true);
                $this->user = $this->auth_local->user();
                $this->load->library('lib_utilitas');
            }
            function index($action = '') {
                $action = $this->input->get('action');
                //Bikin Object Baru Nama nya $grid      
                $grid = new Grid;
                $grid->setTitle('REQUEST UJI BE');
                $grid->setTable('reformulasi.local_req_ujibe');      
                $grid->setUrl('lokal_req_ujibe');
                $grid->setFormUpload(TRUE);


                //List Table
              /*  $grid->addList('vNo_req_refor','cNo_formula','cIteno','vBatch_no','cInisiator','dRequest','iteam_pd','vAlasan_refor','iSubmit','iStatus','iStatus_proses','cApproval','vRemark','dApproval','iSubmit_terima','cFormulator','dUji_be','dFinish_ujibe','dHasil_ujibe','vFilename_ujibe','dApproval_pd','cNip_approval'); */

                $grid->addList('itemas.c_itnam','local_req_refor.vAlasan_refor','local_req_refor.iStatus','local_req_refor.vNo_req_refor','lokal_refor_skala_trial.vnoFormulasi'); 

              /*  $grid->addList('local_req_refor.cIteno','local_req_refor.vBatch_no','local_req_refor.cInisiator','iSubmit');*/
                $grid->setSortBy('dupdate');
                $grid->setSortOrder('DESC');

                $grid->addFields('vNo_req_refor','cIteno','vnoFormulasi','cInisiator','idept_id','vAlasan_refor','details','iteam_pd','dRequest','cApproval','cFormulator','lbl','dUji_be','dHasil_ujibe','vupload','iapp_pd');
               
               $grid->setJoinTable('reformulasi.lokal_refor_skala_trial', 'lokal_refor_skala_trial.ilokal_refor_skala_trial = reformulasi.local_req_ujibe.ilokal_refor_skala_trial', 'inner');
                $grid->setJoinTable('reformulasi.local_req_refor', 'local_req_refor.iLocal_req_refor = reformulasi.lokal_refor_skala_trial.iLocal_req_refor', 'inner');
                $grid->setJoinTable('sales.itemas', 'itemas.c_iteno = reformulasi.local_req_refor.cIteno', 'inner');

                $grid->setQuery('local_req_refor.iUji_be ', 1); 
                $grid->setQuery('local_req_refor.lDeleted = 0 ', null); 
     
              
                $grid->setWidth('vNo_req_refor', '50');
                $grid->setAlign('vNo_req_refor', 'left');
                $grid->setLabel('vNo_req_refor','Nomor Request');

                $grid->setWidth('local_req_refor.vNo_req_refor', '100');
                $grid->setAlign('local_req_refor.vNo_req_refor', 'left');
                $grid->setLabel('local_req_refor.vNo_req_refor','Nomor Request');

                $grid->setWidth('vnoFormulasi', '100');
                $grid->setAlign('vnoFormulasi', 'left');
                $grid->setLabel('vnoFormulasi','Nomor Formula');

                $grid->setWidth('lokal_refor_skala_trial.vnoFormulasi', '100');
                $grid->setAlign('lokal_refor_skala_trial.vnoFormulasi', 'left');
                $grid->setLabel('lokal_refor_skala_trial.vnoFormulasi','Nomor Formula');


                $grid->setWidth('cIteno', '100');
                $grid->setAlign('cIteno', 'left');
                $grid->setLabel('cIteno','Nama Finish Good');

                $grid->setWidth('itemas.c_itnam', '300');
                $grid->setAlign('itemas.c_itnam', 'left');
                $grid->setLabel('itemas.c_itnam','Nama Finish Good');

                $grid->setLabel('lbl', '&nbsp&nbsp');

       /*         $grid->setWidth('vBatch_no', '100');
                $grid->setAlign('vBatch_no', 'left');
                $grid->setLabel('vBatch_no','No Batch');

                $grid->setWidth('local_req_refor.vBatch_no', '100');
                $grid->setAlign('local_req_refor.vBatch_no', 'left');
                $grid->setLabel('local_req_refor.vBatch_no','No Batch');*/
            
                $grid->setWidth('cInisiator', '100');
                $grid->setAlign('cInisiator', 'left');
                $grid->setLabel('cInisiator','Nama Inisator');
            
                $grid->setWidth('idept_id', '100');
                $grid->setAlign('idept_id', 'left');
                $grid->setLabel('idept_id', 'Departement');

                $grid->setWidth('iteam_pd', '100');
                $grid->setAlign('iteam_pd', 'left');
                $grid->setLabel('iteam_pd', 'Team PD');

                $grid->setWidth('dRequest', '100');
                $grid->setAlign('dRequest', 'left');
                $grid->setLabel('dRequest','Tgl Request Reformulasi');

                $grid->setWidth('vAlasan_refor', '100');
                $grid->setAlign('vAlasan_refor', 'left');
                $grid->setLabel('vAlasan_refor','Alasan Reformulasi');

                $grid->setWidth('local_req_refor.vAlasan_refor', '200');
                $grid->setAlign('local_req_refor.vAlasan_refor', 'left');
                $grid->setLabel('local_req_refor.vAlasan_refor','Alasan Reformulasi');

                $grid->setWidth('cApproval', '100');
                $grid->setAlign('cApproval', 'left');
                $grid->setLabel('cApproval','Approval Atasan Inisiator');

                $grid->setWidth('cFormulator', '100');
                $grid->setAlign('cFormulator', 'left');
                $grid->setLabel('cFormulator','PIC Formulator');

                $grid->setWidth('dUji_be', '30');
                $grid->setAlign('dUji_be', 'left');
                $grid->setLabel('dUji_be','Tanggal Uji BE');
            

          
                $grid->setWidth('dHasil_ujibe', '100');
                $grid->setAlign('dHasil_ujibe', 'left');
                $grid->setLabel('dHasil_ujibe','Tgl Hasil Uji BE');
            
                $grid->setWidth('vFilename_ujibe', '100');
                $grid->setAlign('vFilename_ujibe', 'left');
                $grid->setLabel('vFilename_ujibe','File Uji BE');
            
                $grid->setWidth('dApproval_pd', '100');
                $grid->setAlign('dApproval_pd', 'left');
                $grid->setLabel('dApproval_pd','Tanggal Approval PD');
            
                $grid->setWidth('cNip_approval', '100');
                $grid->setAlign('cNip_approval', 'left');
                $grid->setLabel('cNip_approval','Nama Approval PD');

                $grid->setWidth('iapp_pd', '100');
                $grid->setAlign('iapp_pd', 'left');
                $grid->setLabel('iapp_pd','Approval PD');

                $grid->setWidth('iStatus', '100');
                $grid->setAlign('iStatus', 'left');
                $grid->setLabel('iStatus','Status');

                $grid->setWidth('local_req_refor.iStatus', '100');
                $grid->setAlign('local_req_refor.iStatus', 'left');
                $grid->setLabel('local_req_refor.iStatus','Status');
                
            
                $grid->setWidth('iStatus_ujibe', '100');
                $grid->setAlign('iStatus_ujibe', 'left');
                $grid->setLabel('iStatus_ujibe','Status Uji BE');


            
                $grid->setWidth('iSubmit', '100');
                $grid->setAlign('iSubmit', 'left');
                $grid->setLabel('iSubmit','SUBMIT');
            
                $grid->setWidth('vupload', '100');
                $grid->setAlign('vupload', 'left');
                $grid->setLabel('vupload','File Upload');
            
                $grid->setWidth('vRemark', '100');
                $grid->setAlign('vRemark', 'left');
                $grid->setLabel('vRemark','REMARK');
            
      
          

                 //set search
                $grid->setSearch('local_req_refor.vNo_req_refor','itemas.c_itnam');

                $grid->setRequired('dUji_be','dHasil_ujibe','vFilename_ujibe'); 
                $grid->setGridView('grid');

                switch ($action) {
                    case 'json':
                            $grid->getJsonData();
                            break;
                    case 'view':
                            $grid->render_form($this->input->get('id'), true);
                            break;

                    case 'create':
                            $grid->render_form();
                            break;
                    case 'createproses':
                            $isUpload = $this->input->get('isUpload');
                            if($isUpload) {
                                $lastId=$this->input->get('lastId');
                                $path = realpath("files/reformulasi/local/lokal_uji_be");
                                if(!file_exists($path."/".$lastId)){
                                    if (!mkdir($path."/".$lastId, 0777, true)) { //id review
                                        die('Failed upload, try again!');
                                    }
                                }
                                $fKeterangan = array();
                                foreach($_POST as $key=>$value) {                       
                                    if ($key == 'file_keterangan_local_ujibe') {
                                        foreach($value as $k=>$v) {
                                            $fKeterangan[$k] = $v;
                                        }
                                    }
                                }
                                $i=0;
                                $sql=array();
                                foreach ($_FILES['fileupload_local_req_ujibe']["error"] as $key => $error) {
                                    if ($error == UPLOAD_ERR_OK) {
                                        $tmp_name = $_FILES['fileupload_local_req_ujibe']["tmp_name"][$key];
                                        $name =$_FILES['fileupload_local_req_ujibe']["name"][$key];
                                        $data['filename'] = $name;
                                        $data['dInsertDate'] = date('Y-m-d H:i:s');

                                            if(move_uploaded_file($tmp_name, $path."/".$lastId."/".$name)) {
                                                $sql[]="INSERT INTO reformulasi.file_lokal_hasil_ujibe (ilocal_req_ujibe, vFilename, vKeterangan, dcreate, ccreate) 
                                                        VALUES (".$lastId.",'".$data['filename']."','".$fKeterangan[$i]."','".$data['dInsertDate']."','".$this->user->gNIP."')";
                                                $i++;   
                                            }
                                            else{
                                                echo "Upload ke folder gagal";  
                                            }
                                    }
                                }
                                foreach($sql as $q) {
                                    try {
                                    $this->dbset->query($q);
                                    }catch(Exception $e) {
                                    die($e);
                                    }
                                }
                                $r['message']="Data Berhasil Disimpan";
                                $r['status'] = TRUE;
                                $r['last_id'] = $this->input->get('lastId');                    
                                echo json_encode($r);
                            }else{
                                echo $grid->saved_form();
                            }
                            break;
            case 'download':
                $this->download($this->input->get('file'));
                break;

            case 'delete':
                echo $grid->delete_row();
                break;
            case 'update':
                $grid->render_form($this->input->get('id'));
                break;
            case 'getspname':
                echo $this->getSpname();
                break;
            case 'view':
                $grid->render_form($this->input->get('id'),TRUE);
                break;
            case 'updateproses':
                $isUpload = $this->input->get('isUpload');
                $post=$this->input->post();
                $iujibe=$post['lokal_req_ujibe_ilocal_req_ujibe'];
                $path = realpath("files/reformulasi/local/lokal_uji_be");
                if(!file_exists($path."/".$iujibe)){
                    if (!mkdir($path."/".$iujibe, 0777, true)) { //id review
                        die('Failed upload, try again!');
                    }
                }
                $fKeterangan = array(); 
                $fileid='';
                foreach($_POST as $key=>$value) {
                                        
                    if ($key == 'file_keterangan_local_ujibe') {
                        foreach($value as $y=>$u) {
                            $fKeterangan[$y] = $u;
                        }
                    }
                    if ($key == 'iUjibe_file') {
                        $i=0;
                        foreach($value as $k=>$v) {
                            if($i==0){
                                $fileid .= "'".$v."'";
                            }else{
                                $fileid .= ",'".$v."'";
                            }
                            $i++;
                        }
                    }
                }
                if($isUpload) { 
                    if($fileid!=''){
                        $tgl= date('Y-m-d H:i:s');
                        $sql1="update reformulasi.file_lokal_hasil_ujibe set ldeleted=1, dupdate='".$tgl."', cupdate='".$this->user->gNIP."' where ilocal_req_ujibe='".$iujibe."' and iUjibe_file not in (".$fileid.")";
                        $this->dbset->query($sql1);
                    }else{
                        $tgl= date('Y-m-d H:i:s');
                        $sql1="update reformulasi.file_lokal_hasil_ujibe set ldeleted=1, dupdate='".$tgl."', cupdate='".$this->user->gNIP."' where ilocal_req_ujibe='".$iujibe."'";
                        $this->dbset->query($sql1);
                    }
                    $i=0;
                    if (isset($_FILES['fileupload_local_ujibe']))  {
                        foreach ($_FILES['fileupload_local_ujibe']["error"] as $key => $error) {
                            if ($error == UPLOAD_ERR_OK) {
                                $tmp_name = $_FILES['fileupload_local_ujibe']["tmp_name"][$key];
                                $name =$_FILES['fileupload_local_ujibe']["name"][$key];
                                $data['filename'] = $name;
                                $data['dInsertDate'] = date('Y-m-d H:i:s');

                                    if(move_uploaded_file($tmp_name, $path."/".$iujibe."/".$name)) {
                                        $sql[]="INSERT INTO reformulasi.file_lokal_hasil_ujibe (ilocal_req_ujibe, vFilename, vKeterangan, dcreate, ccreate) 
                                                VALUES (".$iujibe.",'".$data['filename']."','".$fKeterangan[$i]."','".$data['dInsertDate']."','".$this->user->gNIP."')";
                                        $i++;   
                                    }
                                    else{
                                        echo "Upload ke folder gagal";  
                                    }
                            }
                        }
                        foreach($sql as $q) {
                            try {
                            $this->dbset->query($q);
                            }catch(Exception $e) {
                            die($e);
                            }
                        }
                    }

                    $r['message']='Data Berhasil di Simpan';
                    $r['status'] = TRUE;
                    $r['last_id'] = $this->input->get('lastId');                
                    echo json_encode($r);
                    exit();
                }  else {
                    $fileid='';
                    foreach($_POST as $key=>$value) {
                        if ($key == 'iUjibe_file') {
                            $i=0;
                            foreach($value as $k=>$v) {
                                if($i==0){
                                    $fileid .= "'".$v."'";
                                }else{
                                    $fileid .= ",'".$v."'";
                                }
                                $i++;
                            }
                        }
                    }
                    if($fileid!=''){
                        $tgl= date('Y-m-d H:i:s');
                        $sql1="update reformulasi.file_lokal_hasil_ujibe set ldeleted=1, dupdate='".$tgl."', cupdate='".$this->user->gNIP."' where iUjibe_file='".$iujibe."' and iUjibe_file not in (".$fileid.")";
                        $this->dbset->query($sql1);
                    }else{
                        $tgl= date('Y-m-d H:i:s');
                        $sql1="update reformulasi.file_lokal_hasil_ujibe set ldeleted=1, dupdate='".$tgl."', cupdate='".$this->user->gNIP."' where iUjibe_file='".$iujibe."'";
                        $this->dbset->query($sql1);
                    }
                    echo $grid->updated_form();
                }
                break;
                case 'approve':
                    echo $this->approve_view();
                    break;
                case 'approve_process':
                    echo $this->approve_process();
                    break;
                case 'reject':
                    echo $this->reject_view();
                    break;
                case 'reject_process':
                    echo $this->reject_process();
                    break;
                case 'getemployee':
                    echo $this->getEmployee();
                    break;
                case 'getdetailsMR':
                    echo $this->getdetailsMR();
                    break;
                default:
                    $grid->render_grid();
                    break;
                }
            }


            /*Modify main grid value*/
         /*   function listBox_lokal_req_ujibe_iStatus_ujibe($value) {
                if($value=0){
                    $r='Draft - Need to Submit';
                }else{
                    $r='Submited';
                }
                return $r;
            }*/

            /*function listBox_lokal_req_ujibe_iStatus($value) {
                if($value=0){
                    $r='Draft - Need to Submit';
                }else{
                    $r='Submited';
                }
                return $r;
            }*/

            //Create Manipulate Field 

            //Jika Ingin Menambahkan Seting grid seperti button edit enable dalam kondisi tertentu
            /* 
            function listBox_Action($row, $actions) {
                if ($row->vNo_Or<>'' || $row->vNo_Or<>NULL) { 
                        unset($actions['edit']);
                }
                return $actions;
            } 
            */
           
                       /*Maniupulasi Gird end*/
            function listBox_Action($row, $actions) {
                if($row->iSubmit<>0){
                    unset($actions['delete']);
                }
                if($row->iapp_pd<>0){
                    unset($actions['edit']);
                }
                return $actions; 

            }



             /*Maniupulasi Gird Start*/
            function getEmployee() {
                $term = $this->input->get('term');
                $sql='select de.vDescription,em.cNip as cNIP, em.vName as vName from plc2.plc2_upb_team_item it
                        inner join plc2.plc2_upb_team te on it.iteam_id= te.iteam_id
                        inner join hrd.employee em on em.cNip=it.vnip
                        inner join hrd.msdepartement de on de.iDeptID=em.iDepartementID 
                        where em.vName like "%'.$term.'%" and te.vtipe="PD" AND it.ldeleted=0 order by em.vname ASC';
                $dt=$this->db->query($sql);
                $data = array();
                if($dt->num_rows>0){
                    foreach($dt->result_array() as $line) {
            
                        $row_array['value'] = trim($line['vName']);
                        $row_array['id']    = $line['cNIP'];
            
                        array_push($data, $row_array);
                    }
                }
                echo json_encode($data);
                exit;
            }

           
            

            function downloaduji($filename) {
                    $this->load->helper('download');        
                    $name = $_GET['fileuji'];
                    $id = $_GET['id'];
                    $path = file_get_contents('./files/reformulasi/local/'.$id.'/'.$name);   
                    force_download($name, $path);
                }


            function listBox_lokal_req_ujibe_iSubmit($value, $pk, $name, $rowData) {
                    $ret="Draft-Need Submit";
                    if($rowData->iSubmit==1){
                        if($rowData->iapp_pd==0){
                            $ret="Submited-Waiting Approval";
                        }elseif($rowData->iapp_pd==2){
                            $ret="Approved";
                        }else{
                            $ret="NULL";
                        }
                    }
                    return $ret;
                }

            function insertBox_lokal_req_ujibe_vNo_req_refor($field, $id) {
                    $return = '<script>
                                    $( "button.icon_pop" ).button({
                                        icons: {
                                            primary: "ui-icon-newwin"
                                        },
                                        text: false
                                    });
                                    function browse_iupb_id(){
                                        browse(\''.base_url().'processor/reformulasi/lokal/req/ujibe/browse?field=lokal_req_ujibe&modul_id='.$this->input->get('modul_id').'\',\'List Request Reformulasi\');
                                    }
                                </script>';
                    $return .= '<input type="hidden" name="isdraft" id="isdraft">';
                    $return .= '<input type="hidden" name="lokal_req_ujibe_ilokal_refor_skala_trial" id="lokal_req_ujibe_ilokal_refor_skala_trial" class="input_rows1 required" />';
                    $return .= '<input type="text" name="'.$id.'_dis" disabled="TRUE" id="'.$id.'_dis" class="input_rows1 required" size="20" />';
                    $return .= '&nbsp;<button class="icon_pop"  onclick="browse_iupb_id()" type="button">&nbsp;</button>';
                    
                    return $return;
                }

            function updateBox_lokal_req_ujibe_vNo_req_refor($field, $id, $value, $rowData) {
                    $dt=$this->getrefordata($rowData['ilokal_refor_skala_trial']);
                    if ($this->input->get('action') == 'view') { 
                        $return= $dt['vNo_req_refor']; 

                    }else{

                      $return = '<script>
                        $( "button.icon_pop" ).button({
                            icons: {
                                primary: "ui-icon-newwin"
                            },
                            text: false
                        });
                        function browse_iupb_id(){
                            browse(\''.base_url().'processor/reformulasi/lokal/req/ujibe/browse?field=lokal_req_ujibe&modul_id='.$this->input->get('modul_id').'\',\'List Request Reformulasi\');
                        }
                    </script>';
                        $return .= '<input type="hidden" name="isdraft" id="isdraft">';
                        $return .= '<input type="hidden" name="lokal_req_ujibe_ilokal_refor_skala_trial" id="lokal_req_ujibe_ilokal_refor_skala_trial" class="input_rows1 required" value="'.$rowData['ilokal_refor_skala_trial'].'" />';
                        $return .= '<input type="text" name="'.$id.'_dis" disabled="TRUE" id="'.$id.'_dis" class="input_rows1 required" size="20" value="'.$dt['vNo_req_refor'].'" />';
                        $return .= '&nbsp;<button class="icon_pop"  onclick="browse_iupb_id()" type="button">&nbsp;</button>';

                    } 
                    return $return;
                }   

 
               function insertBox_lokal_req_ujibe_vnoFormulasi($field, $id) {
                       $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20" />';
                    return $return;
                }


                function updateBox_lokal_req_ujibe_vnoFormulasi($field, $id, $value, $rowData) {
                $dt=$this->getrefordata($rowData['ilokal_refor_skala_trial']);
                $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20" value="'.$dt['vnoFormulasi'].'" />';
                return $return;
            }

                function insertBox_lokal_req_ujibe_cIteno($field, $id) {
                    $return = '<textarea name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1"></textarea>';
                    return $return;
                }

                function updateBox_lokal_req_ujibe_cIteno($field, $id, $value, $rowData) {
                    $dt=$this->getrefordata($rowData['ilokal_refor_skala_trial']);
                    $return = '<textarea name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1">'.$dt['c_itnam'].'</textarea>';
                    return $return;
                 }
            /*    function insertBox_lokal_req_ujibe_vBatch_no($field, $id) {
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20" />';
                    return $return;
                }

                 function updateBox_lokal_req_ujibe_vBatch_no($field, $id, $value, $rowData) {
                               $dt=$this->getrefordata($rowData['ilokal_refor_skala_trial']);
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20" value="'.$dt['vBatch_no'].'" />';
                    return $return;
                }*/
                
                function insertBox_lokal_req_ujibe_cInisiator($field, $id) {
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20" />';
                    return $return;
                }

                function updateBox_lokal_req_ujibe_cInisiator($field, $id, $value, $rowData) {
                    $dt=$this->getrefordata($rowData['ilokal_refor_skala_trial']);
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20" value="'.$dt['cInisiator'].'" />';
                    return $return;
                }

                function insertBox_lokal_req_ujibe_idept_id($field, $id) {
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20" />';
                    return $return;
                }

                function updateBox_lokal_req_ujibe_idept_id($field, $id, $value, $rowData) {
                     $dt=$this->getrefordata($rowData['ilokal_refor_skala_trial']);
                    $iAm['vdepartemen']="-";
                    if($dt['cInisiator']!=""){
                        $iAm = $this->whoAmI($dt['cInisiator']);
                    }
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20" value="'.$iAm['vdepartemen'].'" />';
                    return $return;
                }


                function insertBox_lokal_req_ujibe_vAlasan_refor($field, $id) {
                    $return = '<textarea name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1"></textarea>';
                    return $return;
                }

                function updateBox_lokal_req_ujibe_vAlasan_refor($field, $id, $value, $rowData) {
                        $dt=$this->getrefordata($rowData['ilokal_refor_skala_trial']);
                        $return = '<textarea name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1">'.$dt['vAlasan_refor'].'</textarea>';
                        return $return;
                    }

                function insertBox_lokal_req_ujibe_details($field, $id) {
                    $return = '---Pilih No Refor Terlebih Dahulu---';
                    return $return;
                }

                function updateBox_lokal_req_ujibe_details($field, $id, $value, $rowData) {
                   $dt['id']=$rowData['ilokal_refor_skala_trial'];
                    $d['post']=$dt;
                    $return =$this->load->view('local/jqgrid/details_req_ujibe',$d,true);;
                    return $return;
                }

                function insertBox_lokal_req_ujibe_iteam_pd($field, $id) {
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20"  />';
                    return $return;
                }


                function updateBox_lokal_req_ujibe_iteam_pd($field, $id, $value, $rowData) {
                    $iteam=array(0=>"NULL",1=>"Gunung Putri",2=>"Ulujami PD",3=>"Etercon");
                    $dt=$this->getrefordata($rowData['ilokal_refor_skala_trial']);
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20" value="'.$iteam[$dt['iteam_pd']].'" />';
                    return $return;
                }
                function insertBox_lokal_req_ujibe_dRequest($field, $id) {
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20"  />';
                    return $return;
                    }
                function updateBox_lokal_req_ujibe_dRequest($field, $id, $value, $rowData) {
                       $dt=$this->getrefordata($rowData['ilokal_refor_skala_trial']);
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20" value="'.$dt['dRequest'].'" />';
                    return $return;
                }

                function insertBox_lokal_req_ujibe_cApproval($field, $id) {
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20"  />';
                    return $return;
                }

                function updateBox_lokal_req_ujibe_cApproval($field, $id, $value, $rowData) {
                        $dt=$this->getrefordata($rowData['ilokal_refor_skala_trial']);
                        $val='';
                        if($dt['cApproval']!=''){
                            $ss=$this->whoAmI($dt['cApproval']);
                            $val=$ss['vName'];
                        }
                        $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20" value="'.$val.'" />';
                        return $return;
                    }

                function insertBox_lokal_req_ujibe_cFormulator($field, $id) {
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20"  />';
                    return $return;
                }

                function updateBox_lokal_req_ujibe_cFormulator($field, $id, $value, $rowData) {
                    $dt=$this->getrefordata($rowData['ilokal_refor_skala_trial']);
                    $val='';
                    if($dt['cFormulator']!=''){
                        $ss=$this->whoAmI($dt['cFormulator']);
                        $val=$ss['vName'];
                    }
                    $return = '<input type="text" name="'.$id.'" disabled="TRUE" id="'.$id.'" class="input_rows1" size="20" value="'.$val.'" />';
                    return $return;
                }

                function insertBox_lokal_req_ujibe_lbl($field, $id) {
                    $return = '<script>
                        $("label[for=\''.$id.'\']").css({"border": "1px solid #dddddd", "background": "#548cb6", "border-collapse": "collapse","width":"99%","font-weight":"bold","color":"#ffffff","text-shadow": "0 1px 1px rgba(0, 0, 0, 0.3)","text-transform": "uppercase"});
                    </script>';
                    return $return;
                }

                function updateBox_lokal_req_ujibe_lbl($field, $id) {
                    $return = '<script>
                        $("label[for=\''.$id.'\']").css({"border": "1px solid #dddddd", "background": "#548cb6", "border-collapse": "collapse","width":"99%","font-weight":"bold","color":"#ffffff","text-shadow": "0 1px 1px rgba(0, 0, 0, 0.3)","text-transform": "uppercase"});
                    </script>';
                    return $return;
                }



                function insertBox_lokal_req_ujibe_dUji_be($field, $id){
                    $return = '<input name="'.$id.'" id="'.$id.'" type="text" size="20" class="input_tgl datepicker required" style="width:130px"/>';
                     $return .=  '<script>
                                    $("#'.$id.'").datepicker({
                                        dateFormat:"yy-mm-dd",
                                        onClose: function( selectedDate ) {
                                            $("#lokal_req_ujibe_dHasil_ujibe").datepicker("option", "minDate", selectedDate );
                                        }

                                    });
                                </script>';
                    return $return;
                }

                 function updateBox_lokal_req_ujibe_dUji_be($field, $id, $value, $rowData) {

                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }else{
                        $return = '<input name="'.$id.'" id="'.$id.'" type="text" size="20" class="input_tgl datepicker required" value="'.$value.'" style="width:130px"/>';
                            $return .=  '<script>
                                            $("#'.$id.'").datepicker({dateFormat:"yy-mm-dd"});
                                        </script>';
                            return $return;

                    } 
                    return $return;
                }   
            

       
                function insertBox_lokal_req_ujibe_dHasil_ujibe($field, $id){
                      $return = '<input name="'.$id.'" id="'.$id.'" type="text" size="20" class="input_tgl datepicker required" style="width:130px"/>';
                    $return .=  '<script>
                                    $("#'.$id.'").datepicker({
                                        dateFormat:"yy-mm-dd",
                                        onClose: function( selectedDate ) {
                                            $("#lokal_req_ujibe_dUji_be").datepicker("option", "maxDate", selectedDate );
                                        }

                                    });
                                </script>';
                    return $return;

                }

                function updateBox_lokal_req_ujibe_dHasil_ujibe($field, $id, $value, $rowData) {
                   if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }else{
                        $return = '<input name="'.$id.'" id="'.$id.'" type="text" size="20" class="input_tgl datepicker required" value="'.$value.'" style="width:130px"/>';
                            $return .=  '<script>
                                            $("#'.$id.'").datepicker({dateFormat:"yy-mm-dd"});

                                        </script>';

                            return $return;

                    } 
                    return $return;
                }  
                function insertBox_lokal_req_ujibe_vupload($field, $id){
                    $data['get']=$this->input->get();
                    $ret=$this->load->view('local/jqgrid/details_file_ujibe',$data,TRUE);
                    return $ret;
                }

                function updateBox_lokal_req_ujibe_vupload($field, $id, $value, $rowData) {
                    $data['get']=$this->input->get();
                    $data['rowData']=$rowData;
                    $ret=$this->load->view('local/jqgrid/details_file_ujibe_edit',$data,TRUE);
                    return $ret;
                }
                function insertBox_lokal_req_ujibe_iapp_pd($field, $id){
                    $return='-';
                    return $return;
                }

                function updateBox_lokal_req_ujibe_iapp_pd($field, $id, $value, $rowData) {
                    $ret='Waiting for Approval';
                    if($rowData['iapp_pd']!=0){
                        if($rowData['cNip_approval'] != null){
                            $row = $this->db->get_where('hrd.employee', array('cNip'=>$rowData['cNip_approval']))->row_array();
                            if($rowData['iapp_pd']==2){$st="Approved";}elseif($rowData['iapp_pd']==1){$st="Rejected";} 
                            $ret= $st.' oleh '.$row['vName'].' ( '.$rowData['cNip_approval'].' )'.' pada '.$rowData['dApproval_pd'];
                        }
                        else{
                            $ret='Waiting for Approval';
                        }
                    }
                    return $ret;
                }

                function insertBox_lokal_req_ujibe_vFilename_ujibe($field, $id) {
                   $data['get']=$this->input->get();
                    $ret=$this->load->view('local/jqgrid/details_file_ujibe',$data,TRUE);
                    return $ret;

                }

               function updateBox_lokal_req_ujibe_vFilename_ujibe($field, $id){
                    $data['get']=$this->input->get();
                    $ret=$this->load->view('local/jqgrid/details_file_ujibe',$data,TRUE);
                    return $ret;
                } 
         
        
            //Standart Setiap table harus memiliki dCreate , cCreated, dupdate, cUpdate
            function before_insert_processor($row, $postData) {
                $postData['dCreate'] = date('Y-m-d H:i:s');
                $postData['cCreate'] =$this->user->gNIP;
                if($postData['isdraft']==true){
                    $postData['iSubmit']=0;
                }else{$postData['iSubmit']=1;} 
                return $postData;
            }

           /* function before_update_processor($row, $postData) {
                $postData['dupdate'] = date('Y-m-d H:i:s');
                $postData['cUpdate'] = $this->user->gNIP;
                return $postData; 
            }    */

            function before_update_processor($row, $postData) {
                $postData['dupdate'] = date('Y-m-d H:i:s');
                $postData['cupdate'] =$this->user->gNIP;
                    if($postData['isdraft']==true){
                        $postData['iSubmit']=0;
                    } 
                    else{$postData['iSubmit']=1;} 
                return $postData;

            }

            function after_insert_processor($row, $insertId, $postData){
            if($postData['iSubmit']){
                $dtrefor=$this->getrefordata($postData['ilokal_refor_skala_trial']);
                $getemail=$this->getemail($dtrefor);
                $to =$getemail['to'];
                $cc =$getemail['cc'];
                $iteam=array(0=>"NULL",1=>"Gunung Putri",2=>"Ulujami PD",3=>"Etercon");
                $subject="Refor - UJI BE: ".$dtrefor['vNo_req_refor'];
                $content="
                        Diberitahukan bahwa telah ada inputan pada proses UJI BE (aplikasi Reformulasi) dengan rincian sebagai berikut :<br><br>
                        <div style='width: 600px;padding: 10px;background : #cfd1cf;margin: 0px;'>
                                <table border='0' bgcolor='#cfd1cf' style='width: 600px;'>
                                        <tr>
                                                <td style='width: 110px;'><b>No Request</b></td><td style='width: 20px;'> : </td><td>".$dtrefor['vNo_req_refor']."</td>
                                        </tr>
                                        <tr>
                                                <td><b>Nama Usulan</b></td><td> : </td><td>".$dtrefor['c_itnam']."</td>
                                        </tr>
                                        <tr>
                                                <td><b>Team PD</b></td><td> : </td><td>".$iteam[$dtrefor['iteam_pd']]."</td>
                                        </tr>
                                </table>
                        </div>
                        <br/> 
                        Link Aplikasi : www.npl-net.com/erp <br>
                        Menu : Reformulasi - Transaksi - Uji BE
                        <br/> <br/> 
                        Demikian, mohon segera follow up  pada aplikasi ERP Reformulasi. Terimakasih.<br><br><br>
                        Post Master";
                $this->lib_utilitas->send_email($to, $cc, $subject, $content);
            }
        }

            function after_update_processor($row, $insertId, $postData, $old_data) {
                if($postData['iSubmit']==1&&$old_data['iSubmit']==0){
                    $dtrefor=$this->getrefordata($postData['ilokal_refor_skala_trial']);
                    $getemail=$this->getemail($dtrefor);
                    $to =$getemail['to'];
                    $cc =$getemail['cc'];
                    $iteam=array(0=>"NULL",1=>"Gunung Putri",2=>"Ulujami PD",3=>"Etercon");
                    $subject="Refor - UJI BE: ".$dtrefor['vNo_req_refor'];
                    $content="
                            Diberitahukan bahwa telah ada inputan pada proses UJI BE (aplikasi Reformulasi) dengan rincian sebagai berikut :<br><br>
                            <div style='width: 600px;padding: 10px;background : #cfd1cf;margin: 0px;'>
                                    <table border='0' bgcolor='#cfd1cf' style='width: 600px;'>
                                            <tr>
                                                    <td style='width: 110px;'><b>No Request</b></td><td style='width: 20px;'> : </td><td>".$dtrefor['vNo_req_refor']."</td>
                                            </tr>
                                            <tr>
                                                    <td><b>Nama Usulan</b></td><td> : </td><td>".$dtrefor['c_itnam']."</td>
                                            </tr>
                                            <tr>
                                                    <td><b>Team PD</b></td><td> : </td><td>".$iteam[$dtrefor['iteam_pd']]."</td>
                                            </tr>
                                    </table>
                            </div>
                            <br/> 
                            Link Aplikasi : www.npl-net.com/erp <br>
                            Menu : Reformulasi - Transaksi - Uji BE
                            <br/> <br/> 
                            Demikian, mohon segera follow up  pada aplikasi ERP Reformulasi. Terimakasih.<br><br><br>
                            Post Master";
                   $this->lib_utilitas->send_email($to, $cc, $subject, $content);
                }   
            }

            function manipulate_insert_button($buttons) {

                    unset($buttons['save']);

                    $js = $this->load->view('local/js/lokal_ujibe_js');
                    $js .= $this->load->view('local/js/upload_js');
            
                    if($this->auth_local->is_manager()){
                        $x=$this->auth_local->dept();
                        $manager=$x['manager'];
                        if(in_array('PD', $manager)){
                            $type='PD';
                            $save_draft = '<button onclick="javascript:save_draft_btn_multiupload(\'lokal_req_ujibe\', \''.base_url().'processor/reformulasi/local/req/ujibe?draft=true\', this, true)" class="ui-button-text icon-save" id="button_save_draft_local_ujibe">Save as Draft</button>';
                            $save = '<button onclick="javascript:save_btn_multiupload(\'lokal_req_ujibe\', \''.base_url().'processor/reformulasi/local/req/ujibe?company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\', this)" class="ui-button-text icon-save" id="button_update_lokal_req_ujibe">Save &amp; Submit</button>';
                            
                            $buttons['save'] = $save_draft.$save.$js;
                        }else{$type='qq';}
                    }
                    else{
                        $x=$this->auth_local->dept();
                        $team=$x['team'];
                        if(in_array('PD', $team)){
                            $type='PD';
                            $save_draft = '<button onclick="javascript:save_draft_btn_multiupload(\'lokal_req_ujibe\', \''.base_url().'processor/reformulasi/local/req/ujibe?draft=true\', this, true)" class="ui-button-text icon-save" id="button_save_draft_lokal_req_ujibe">Save as Draft</button>';
                            $save = '<button onclick="javascript:save_btn_multiupload(\'lokal_req_ujibe\', \''.base_url().'processor/reformulasi/local/req/ujibe?company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\', this)" class="ui-button-text icon-save" id="button_update_lokal_req_ujibe">Save &amp; Submit</button>';
                            $buttons['save'] = $save_draft.$save.$js;
                        }
                        else{$type='sq';}
                    }
                    //$buttons['save']=$type;
                    return $buttons;
                }


                function manipulate_update_button($buttons, $rowData) {


                //print_r($rowData);exit();
                    unset($buttons['update']);
                    //$js=$this->load->view('misc_util',array('className'=> 'local_ujibe_literatur_pd'), true);
                    
                    $js = $this->load->view('local/js/lokal_ujibe_js');
                    $js .= $this->load->view('local/js/upload_js');
                    $cNip=$this->user->gNIP;

                    $approve = '<button onclick="javascript:load_popup(\''.base_url().'processor/reformulasi/lokal/req/ujibe?action=approve&ilocal_req_ujibe='.$rowData['ilocal_req_ujibe'].'&cNip='.$cNip.'&status=1&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\')" class="ui-button-text icon-save" id="button_approve_lokal_req_ujibe">Approve</button>';
                    $reject = '<button onclick="javascript:load_popup(\''.base_url().'processor/reformulasi/lokal/req/ujibe?action=reject&iujibe_id='.$rowData['ilocal_req_ujibe'].'&cNip='.$cNip.'&status=2&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\')" class="ui-button-text icon-save" id="button_approve_lokal_req_ujibe">Reject</button>';

                    $update = '<button onclick="javascript:update_btn_back(\'lokal_req_ujibe\', \''.base_url().'processor/reformulasi/lokal/req/ujibe?company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\', this)" class="ui-button-text icon-save" id="button_update_lokal_req_ujibe">Update & Submit</button>';

                    $updatedraft = '<button onclick="javascript:update_draft_btn(\'lokal_req_ujibe\', \''.base_url().'processor/reformulasi/lokal/req/ujibe?company_id='.$this->input->get('company_id').'&draft=true&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').'\', this, true)" class="ui-button-text icon-save" id="button_save_lokal_req_ujibe">Update as Draft</button>';

                    if($this->auth_local->is_manager()){
                        $x=$this->auth_local->dept();
                        $manager=$x['manager'];
                        if(in_array('PD', $manager)){

                            $type='PD';
                            if($rowData['iSubmit']==0){//Kalau udah di update as submit, harusnya button approvenya muncul
                                $buttons['update']=$updatedraft.$update.$js;
                            }
                            elseif(($rowData['iSubmit']<>0)&&($rowData['iapp_pd']==0)){
                                $buttons['update']=$approve.$js;
                            }else{}
                        }else{

                            $type='';
                        }
                    }else{

                        $x=$this->auth_local->dept();
                        $team=$x['team'];
                        if(in_array('PD', $team)){
                            $type='PD';
                            if($rowData['iSubmit']==0){
                                $buttons['update']=$updatedraft.$update.$js;
                            }else{}
                        }else{
                            $type='';
                        }
                    }
                    return $buttons;
                }

                  
                function approve_view() {
                        $echo = '<script type="text/javascript">
                                     function submit_ajax(form_id) {

                                        return $.ajax({
                                            url: $("#"+form_id).attr("action"),
                                            type: $("#"+form_id).attr("method"),
                                            data: $("#"+form_id).serialize(),
                                            success: function(data) {
                                                var o = $.parseJSON(data);
                                                var last_id = o.last_id;                            
                                                if(o.status == true) {
                                                    $("#alert_dialog_form").dialog("close");
                                                        $.get(base_url+"processor/reformulasi/lokal/req/ujibe?action=view&id="+last_id+"&group_id="+o.group_id+"&modul_id="+o.modul_id, function(data) {
                                                             $("div#form_lokal_req_ujibe").html(data);
                                                        });
                                                    
                                                }
                                                    reload_grid("grid_lokal_req_ujibe");
                                            }
                                            
                                         })
                                     }
                                 </script>';
                        $echo .= '<h1>Approval</h1><br />';
                        $echo .= '<form id="form_lokal_req_ujibe_approve" action="'.base_url().'processor/reformulasi/lokal/req/ujibe?action=approve_process" method="post">';
                        $echo .= '<div style="vertical-align: top;">';
                        $echo .= 'Remark : 
                                <input type="hidden" name="ilocal_req_ujibe" value="'.$this->input->get('ilocal_req_ujibe').'" />
                                <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                                <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                                <textarea name="vRemark"></textarea>
                        <button type="button" onclick="submit_ajax(\'form_lokal_req_ujibe_approve\')">Approve</button>';
                            
                        $echo .= '</div>';
                        $echo .= '</form>';
                        return $echo;
                    }

                function approve_process(){
                    $post = $this->input->post();
                    $cNip= $this->user->gNIP;
                    $vRemark = $post['vRemark'];
                    $tApprove=date('Y-m-d H:i:s');
                    $sql="update reformulasi.local_req_ujibe set vRemark='".$vRemark."',cNip_approval='".$cNip."', dApproval_pd='".$tApprove."', iapp_pd=2 where ilocal_req_ujibe='".$post['ilocal_req_ujibe']."'";
                    $this->dbset->query($sql);

                    $sql1 = "select * from reformulasi.local_req_ujibe lab
                        JOIN reformulasi.lokal_refor_skala_trial re on re.ilokal_refor_skala_trial=lab.ilokal_refor_skala_trial
                        where lab.ilocal_req_ujibe='".$post['ilocal_req_ujibe']."'";
                    $dtm = $this->db->query($sql1)->row_array();

                    /*Cek Untuk Stabilita Pilot terlebih dahulu*/
                    $sqlcek='select * from reformulasi.lokal_refor_stabilita_pilot pi where pi.ldeleted=0 and pi.iapppd=2 and pi.ilokal_refor_skala_trial='.$dtm['ilokal_refor_skala_trial'];
                    $qcek=$this->dbset->query($sqlcek);
                    $next=8;
                    if($qcek->num_rows()>=1){
                        $next=13;
                    }
                    $sql2 = "UPDATE reformulasi.local_req_refor st SET st.iStatus_proses = ".$next." WHERE 
                                    st.iLocal_req_refor = '".$dtm['iLocal_req_refor']."'";
                    $this->db->query($sql2);

                    $data['group_id']=$post['group_id'];
                    $data['modul_id']=$post['modul_id'];
                    $data['status']  = true;
                    $data['last_id'] = $post['ilocal_req_ujibe'];
                    
                    return json_encode($data);
                }



                    function reject_view() {
                    $echo = '<script type="text/javascript">
                                 function submit_ajax(form_id) {
                                    var remark = $("#reject_lokal_req_ujibe_vRemark").val();
                                    if (remark=="") {
                                        alert("Remark tidak boleh kosong ");
                                        return
                                    }
                                    return $.ajax({
                                        url: $("#"+form_id).attr("action"),
                                        type: $("#"+form_id).attr("method"),
                                        data: $("#"+form_id).serialize(),
                                        success: function(data) {
                                            var o = $.parseJSON(data);
                                            var last_id = o.last_id;
                                            var url = "'.base_url().'processor/lokal/req/ujibe/";                             
                                            if(o.status == true) {
                                                
                                                $("#alert_dialog_form").dialog("close");
                                                     $.get(url+"?action=view&id="+last_id+"&group_id="+o.group_id+"&modul_id="+o.modul_id, function(data) {
                                                     $("div#form_lokal_req_ujibe").html(data);
                                                });
                                                
                                            }
                                                reload_grid("grid_lokal_req_ujibe");
                                        }
                                        
                                     })
                                
                                 }
                             </script>';
                    $echo .= '<h1>Reject</h1><br />';
                    $echo .= '<form id="form_lokal_req_ujibe_reject" action="'.base_url().'processor/reformulasi.local_req_ujibe/lokal/req/ujibe?action=reject_process" method="post">';
                    $echo .= '<div style="vertical-align: top;">';
                    $echo .= 'Remark : 
                            <input type="hidden" name="iujibe_id" value="'.$this->input->get('iujibe_id').'" />
                            <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                            <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                            <textarea name="vRemark"></textarea>
                    <button type="button" onclick="submit_ajax(\'form_lokal_req_ujibe\')">Reject</button>';
                        
                    $echo .= '</div>';
                    $echo .= '</form>';
                    return $echo;
                }             

                function reject_process () {
                        $post = $this->input->post();
                        $cNip= $this->user->gNIP;
                        $vRemark = $post['vRemark'];
                        $tApprove=date('Y-m-d H:i:s');
                        $sql="update reformulasi.local_req_ujibe set vRemark='".$vRemark."',cNip_approval='".$cNip."', dApproval_pd='".$tApprove."', iapp_pd=1 where ilokal_req_ujibe='".$post['ilokal_req_ujibe']."'";
                        $this->dbset->query($sql);
                        $data['group_id']=$post['group_id'];
                        $data['modul_id']=$post['modul_id'];
                        $data['status']  = true;
                        $data['last_id'] = $post['iujibe_id'];
                        return json_encode($data);
                    }

                function download($filename) {
                    $this->load->helper('download');        
                    $name = $_GET['file'];
                    $id = $_GET['id'];
                    $path = file_get_contents('./files/reformulasi/local/lokal_uji_be/'.$id.'/'.$name);   
                    force_download($name, $path);
                }


            /*Function Pendukung*/
                function getrefordata($id=0){
                    $sql="select r.*,t.vnoFormulasi,i.c_itnam from reformulasi.lokal_refor_skala_trial t
                        join reformulasi.local_req_refor r on r.iLocal_req_refor=t.iLocal_req_refor
                        join sales.itemas i on i.c_iteno = r.cIteno
                        where t.ilokal_refor_skala_trial=".$id;
                    $ret=$this->dbset->query($sql)->row_array();
                    return $ret;
                }


                function whoAmI($nip){
                    $sql = 'select b.vDescription as vdepartemen,a.vName,a.cNip,a.vEmail
                            from hrd.employee a 
                            join hrd.msdepartement b on b.iDeptID=a.iDepartementID
                            where a.cNip ="'.$nip.'"
                            ';
                    $data = $this->db->query($sql);
                   if($data->num_rows()>=1){
                    $dt=$data->row_array();
                    return $dt;
                   }else{
                    return "0";
                   }
                }

                function getemail($dareq){
                    $iteam_pd=$dareq['iteam_pd'];
                    $return['to']='';
                    $return['cc']='';

                    /*Untuk Manager (To)*/
                    $sqlman='select * from reformulasi.reformulasi_team t where t.ireformulasi_team='.$iteam_pd;
                    $dman=$this->dbset->query($sqlman)->row_array();
                    if(count($dman)>=1){
                        $me=$this->whoAmI($dman['vnip']);
                        $return['to']= $me['vEmail'];
                    }

                    /*Untuk Team (cc)*/
                    $sqlteam='select * from reformulasi.reformulasi_team_item i where i.ireformulasi_team='.$iteam_pd;
                    $dteam=$this->dbset->query($sqlteam);
                    if($dteam->num_rows()>=1){
                        $cc=array();
                        foreach ($dteam->result_array() as $kteam => $vteam) {
                            $me=$this->whoAmI($vteam['vnip']);
                            $cc[]=$me['vEmail'];
                        }
                        $ccr=array_unique($cc);
                        $return['cc']=implode(',',$ccr);
                    }
                    return $return;

                }

                function getdetailsMR(){// Untuk Menampilkan File yang sudah di upload di Uji BE
                   
                        $post=$this->input->get();
                        $sql_data='select * from reformulasi.file_lokal_hasil_ujibe f where f.ldeleted=0 and f.ilocal_req_ujibe='.$post['id'];// $post['id'] diambil dari get yang dikirm jqgrid
                        $q=$this->db->query($sql_data);
                        //echo $sql_data;
                        $rsel=array('vFilename','vKeterangan','iact');
                        $data = new StdClass;
                        $data->records=$q->num_rows();
                        $i=0;
                        foreach ($q->result() as $k) {
                            $n=$i+1;
                            $data->rows[$i]['id']=$n;
                            $z=0;
                            foreach ($rsel as $dsel => $vsel) {
                                $value = $k->vFilename; 
                                $linknya = 'No File';
                                if($value != '') {
                                    if (file_exists('./files/reformulasi/local/lokal_uji_be/'.$post['id'].'/'.$value)) {//Cek Letak File upload masih ada / tidak
                                        $link = base_url().'processor/reformulasi/lokal/req/ujibe?action=download&id='.$post['id'].'&file='.$value;//Arah Download File
                                        $linknya = '<a class="ui-button-text icon_cetak" href="javascript:;" onclick="window.location=\''.$link.'\'">Download</a>';
                                    }
                                    else {
                                        $linknya = 'File Deleted';
                                    }
                                }
                                if($vsel=="iact"){
                                    if($post['acc']!="view"){
                                        $dataar[$dsel]='<input type="hidden" class="num_rows_details_file_ujibe_edit" value="'.$n.'" /><button id="table_file_ujibe_details_edit_hapus" class="ui-button-text icon_hapus" style="width:75px" onclick="javascript:hapus_row_details_file_ujibe_edit('.$n.')" type="button">Hapus</button>'.$linknya.'<input type="hidden" name="iUjibe_file[]" value="'.$k->iUjibe_file.'"';
                                    }else{
                                        $dataar[$dsel]='<input type="hidden" class="num_rows_details_file_ujibe_edit" value="'.$n.'" />'.$linknya.'<input type="hidden" name="iUjibe_file[]" value="'.$k->iUjibe_file.'"';
                                    }
                                }else{
                                    $dataar[$z]=$k->{$vsel};
                                }
                                $z++;
                            }
                            $data->rows[$i]['cell']=$dataar;
                            $i++;
                        }
                        return json_encode($data);
                    }
                function output(){
                    $this->index($this->input->get('action'));
                }
            }